### ISSUE TITLE
passive queueDeclare resulting in 404, leaves channel open.

### ISSUE THREAD

**Issue by jameskeane** [rabbitmq/rabbitmq-server#10]
I have tested with two different clients, so this seems to be an issue with RabbitMQ itself.

Here is a trace, using the node-amqp library, where I also explicitly close the channel in the error handler, and get a channelCloseOK, but the channel stays open and is visible using rabbitmqctl list_channels. https://gist.github.com/e23bbeb8e5ae069f3e49

This is a pretty serious use case for us, and is leading to huge memory leaks in production.  In the order of tens of thousands of open channels a day.

**Comment by thejuan** [comment]
My reading of AMQP Spec is that no CloseOk is required when a channel is closed with an exception.
I would suggest this a bug in the server code?

https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf
2.2.3 No Confirmations
4.5 Channel Closure item 2

**Comment by michaelklishin** [comment]
Since this thread is from 2012, keep a couple of things in mind:

 * Things could have changed since then.
 * The AMQP 0-9-1 spec has known issues, inconsistencies and statements open to interpretation. Team RabbitMQ has an [entire errata document](http://www.rabbitmq.com/amqp-0-9-1-errata.html). It also has features that 10 year later can confidently be considered poorly thought out and in a couple of places RabbitMQ deviates to do what's more user-friendly.
 * If a particular behaviour is demonstrated by most popular client libraries, including those our team maintains, it is extremely unlikely that it's going to change by now. If something is a truly annoying behaviour, it has been reported plenty of times in the ~ 10 years since the 0-9-1 spec was last revised.

RabbitMQ sends clients a `channel.close-ok` in response to a `channel.close`, so why would clients not be required send a response when RabbitMQ initiates a close?

Anyhow, a quick glance at `rabbit_channel`/`rabbit_reader`, Java client and Bunny suggest that

 * A `channel.close-ok` is still required.
 * Java client and Bunny sent `channel.close-ok` as expected.
 * In Java client it has been the case [since at least Jan 2011](https://github.com/rabbitmq/rabbitmq-java-client/commit/4d8ba388a460c133be7b97ade0f233cf8b8f69f7) (very likely way earlier, it's just as early as things go for `ChannelN` in the current codebase)

So the reporter probably hasn't used one of the clients maintained by our team. `node-amqp` is known to be a terrible, buggy abandonware and we have been recommending avoiding it for years.
I cannot name a client that has caused more head scratching and false RabbitMQ bug accusations than node-amqp. Use [amqp.node](https://github.com/squaremo/amqp.node) instead.

**Comment by michaelklishin** [comment]
Any further comments about how the spec should be interpreted belong to the mailing list.
