### ISSUE TITLE
Prevent unbounded gc interval backoff

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#100]
Filing so that #99 makes it into release notes.

**Comment by noahhaon** [comment]
@dumbbell just a follow up, we have seen far worse performance in the rabbitmq-management stats collector under 3.6.0, to the point of consistently reaching backlogs in the tens of millions and rapidly hitting the memory high water mark or suffering an allocation failure and crash.  

After conversations w/ @michaelklishin on rabbitmq-users we suspect it may be due to this change.  Other work here https://github.com/rabbitmq/rabbitmq-management/pull/101 will hopefully mitigate the issue, but I thought you may be interested given your concerns on this issue.

**Comment by michaelklishin** [comment]
I highly doubt this change can affect event stats collector in any substantial way. Please stop speculating.

**Comment by noahhaon** [comment]
@michaelklishin Sorry, but you made that speculation yourself on the newsgroup.  There had been no other significant changes between 3.5.7 and 3.6.0 that could have caused this.  We are actively trying to engage a support contract with Pivotal and will ensure this issue is resolved in pre-sales.

**Comment by michaelklishin** [comment]
There are many issues with the event collector that lead to it not keeping up with the load but this has nothing to do with that. https://github.com/rabbitmq/rabbitmq-management/issues/41 provides much more information.

**Comment by michaelklishin** [comment]
@noahhaon except that I did not speculate and this is not the only change in the `3.6.0` cycle. Background GC runs every 30, 40, up to 240 (with this change) seconds while event collector has several GC runs per second under load.

I don't see any point in continuing this conversation. Interested parties should watch https://github.com/rabbitmq/rabbitmq-management/issues/41 and read comments there.
