### ISSUE TITLE
Shovel that uses TLS and Erlang 26 fails to starth

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#10439]
### Describe the bug

Using RabbitMQ 3.12.x and Erlang 26.1.2, if you configure a shovel to use TLS, it will fail to start with the following:

```
[error] <0.1484.0> Shovel 'shovel-test' failed to connect (URI: amqps://rmq1): {options,incompatible,[{verify,verify_peer},{cacerts,undefined}]}
```

### Reproduction steps

```
git clone https://github.com/lukebakken/docker-rabbitmq-tls-shovel.git
cd docker-rabbitmq-tls-shovel
make up
```

### Expected behavior

Shovel starts without error.

### Additional context

Erlang 26 is more strict in validating TLS/SSL options. The Erlang client must not be clearing out the `cacerts` TLS option, or perhaps some default changed in Erlang 26

**Comment by lukebakken** [comment]
This isn't actually a bug, but a "feature" of how Erlang 26 verifies options passed to `ssl:connect`

https://github.com/erlang/otp/issues/8066

In this particular RabbitMQ user's case, they did not correctly specify the CA certificate for the Shovel to use. In order to do so, the AMQPS URI must be used, or the `advanced.config` file, like this:

https://github.com/lukebakken/docker-rabbitmq-tls-shovel/blob/main/rmq0/advanced.config

```
[
    {amqp_client, [
        {ssl_options, [
            {cacertfile, "/etc/rabbitmq/ca_certificate.pem"},
            {certfile, "/etc/rabbitmq/client_rmq0_certificate.pem"},
            {keyfile, "/etc/rabbitmq/client_rmq0_key.pem"},
            {verify, verify_peer},
            {fail_if_no_peer_cert, false}
        ]}
    ]}
].
```

**Comment by heagssta** [comment]
I am having a similar issue in Windows 10 Clients.  Was on Erlang 25.2 on Windows, now on 26.2 and TLS no longer works.  this AMQPS shovel was working before the Elrang upgrade.  

 Same issue occurs on RabbitMQ v3.11.9 or v3.12.11 if Erlang 26.2 is installed.  I do have the cert info + pass in the rabbit.config, and in the advanced.config for the shovel, I am already using AMQPS.  I am getting the "failed to connect to source (URI: amqps:servername): {options, incompatible,[{verify,verify_peer},{cacerts,undefined}]}  I have tried removing and adding the verify_peer option and this message doesnt change on the client, I have spent days on this and haven't made any progress..  If the info is in the rabbit.config, I shouldnt have to add it to the shovel advanced.config, right?  this still seems like an issue.  I tried open ssl testing on the client and the server and I get a successful handshake.  I didnt see any SHA1 in my chain either.  Any help would be appreciated, thank you in advance.

**Comment by michaelklishin** [comment]
@heagssta instead of posting comments on an existing issue, consider starting a new discussion of type of Question and providing the details it asks for. Not a single sentence error description but a page or two of logs.

Erlang 26 has a different set of defaults for TLS clients. We do not guess in this community but very likely that's what affects your shovels.

There are many discussions and changes in different parts of RabbitMQ where a TLS client is used, a quick search for "Erlang 26 TLS peer verification" reveals

https://github.com/rabbitmq/rabbitmq-server/discussions/11283, https://github.com/rabbitmq/rabbitmq-server/discussions/11074, https://github.com/rabbitmq/rabbitmq-server/discussions/10890, 
https://github.com/rabbitmq/rabbitmq-server/discussions/11074,
https://github.com/rabbitmq/rabbitmq-server/pull/10916

Explicitly disabling peer verification (or using a certificate/key pair on the client side) should help.

We will not guess any further and we [will not troubleshoot TLS](https://github.com/rabbitmq/rabbitmq-server/blob/main/COMMUNITY_SUPPORT.md) for non-contributing and non-paying users. However, the methodology our team has been using for years to narrow down TLS connectivity issues [has been publicly documented](https://www.rabbitmq.com/docs/troubleshooting-ssl) for years, so anyone can do exactly what we would.

**Comment by michaelklishin** [comment]
[3.13.0 release notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.13.0) (a mandatory reading for anyone upgrading to 3.13.x, the only community supported version until 4.0 ships) have a TLS Defaults section that says…

> Starting with Erlang 26, client side [TLS peer certificate chain verification](https://www.rabbitmq.com/docs/ssl#peer-verification) settings are enabled by default in most contexts:
> from federation links to shovels to TLS-enabled LDAP client connections.
> 
> If using TLS peer certificate chain verification is not practical or necessary, it can be disabled.
> Please refer to the docs of the feature in question, for example,
> this one [on TLS-enabled LDAP client](http://rabbitmq.com/docs/ldap/#tls) connections.

Relevant doc sections for shovels are

 * [One](https://www.rabbitmq.com/docs/shovel#tls)
 * [Two](https://www.rabbitmq.com/docs/uri-query-parameters)

**Comment by michaelklishin** [comment]
I have [updated](https://github.com/rabbitmq/rabbitmq-server/commit/8ab0d4cf682df984948ace4ec6503edf67b9a74d) 3.13.0 and 4.0.0 release notes to be more explicit that this Erlang 26 TLS client default change affects shovels.

**Comment by michaelklishin** [comment]
I have also [added a visible note to several doc guides](https://github.com/rabbitmq/rabbitmq-website/commit/e057dbddd7a65269df885d2807b13f593fde85d6):

 * Shovels
 * Dynamic Shovels
 * Federation
 * LDAP
 * Supported Erlang versions

Hopefully this TLS implementation default change will be easier to spot.
