### ISSUE TITLE
I can't find the version of rabbitmq-server without invoking sudo

### ISSUE THREAD

**Issue by knappe** [rabbitmq/rabbitmq-server#1076]
I'm attempting to script the installation of some plugins and I haven't found a workaround simply because the script would need sudo access to discover the version of rabbitmq-server installed.

I can't use `rabbitmqctl` either because it too requires `sudo`: `Only root or rabbitmq should run rabbitmqctl`.

Any suggestions on how I can find the version of rabbitmq-server running without the need for sudo?

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by knappe** [comment]
@michaelklishin This is an issue though.  Why can't I ask rabbitmq-server which version it is running?  That is a very reasonable expectation.  And I shouldn't have to invoke `sudo` to do it.

**Comment by michaelklishin** [comment]
`rabbitmqctl` itself does not require `sudo`. It entirely depends on the installation method. You can download the generic UNIX package, unpack it into your home directory and no  RabbitMQ CLI tool will require `sudo`.

If you use Debian or RPM packages, `sudo` is required. Not requiring `sudo` for administrative tools is a terrible idea and is a *much* more essential and common expectation from any operator.

There's HTTP API and `GET /api/overview` which includes server version. It returns a JSON response and can be used with `curl`.

Client libraries usually provide access to server properties, including version and platform (e.g. JDK or Ruby version). Opening a client connection certainly does not require `sudo`.

So yes, this is a question and not an issue AS DEFINED BY THIS TEAM. There is nothing actionable for our team to work on: you are just looking for help.

**Comment by michaelklishin** [comment]
I'm pretty tired of answering the same thing over and over but this is a better example than some others: what would constitute an issue?

 * a specific suggestion to add a new HTTP API endpoint that *only* returns server version.
 * a specific suggestion to add a new CLI tool that will be world executable in packages and will *only* return very basic server information (such as version). `rabbitmq-diagnostics` in `3.7.0` is closed to that

Something one of the engineers can assign and begin working on because there's a clear problem definition and enough information to at least get started.
