### ISSUE TITLE
Failed to create erlang.cookie when HOMEDRIVE is a network share

### ISSUE THREAD

**Issue by mlouage** [rabbitmq/rabbitmq-server#1077]
Hello

On my workstation my HOMEDRIVE is set to P:\  which is a network share. This is a corporte workstation so I cannot change this. From my understanding there have already been issues with this, I have read through the answers but I cannot get it to work. It would be nice if the setup of RabbitMQ could work this out.

Machine is Windows 10 Enterprise x64 1607
Home drive set to P:\ (\\Shares\Username\Personal)

I install Erlang 19.2 (x64) and RabbitMQ 3.6.6. Install  of the RabbitMQ service fails.
I stop the RabbitMQ service from the services list and set it to manual.
I copy .erlang.cookie from C:\Windows to P:\ and C:\Users\Username
I open an Administrator prompt
I try to remove the RabbitMQ service with rabbitmq-service remove. I get 3 times the message "The filename, directory name, or volume label syntax is incorrect." but in the end the service is removed.
I try to reinstall with rabbitmq-service install but it fails to create the erlang.cookie in P:\

Why? I already copied it there?

**Comment by mlouage** [comment]
Found a workaround. 

I disconnected all network drives and rebooted the workstation without a network cable. I made sure my HOMEDRIVE was now set to C: and HOMEPATH to \Users\username

Retried the steps to remove and install the service with the command line tools and now everything worked. Because my erlang.cookie was the same in systemroot, homedrive on C:\ and homedrive on P:\ the setup also works when I reboot the workstation with all network cables connected and network drives mapped again.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ does not create the cookie, the runtime does.

**Comment by pascaltozzi** [comment]
Actually the issue listed here is a privilege issue.
When you are installing the service of rabbitMQ on windows, the thread on your machine is running under the Administrator credential.

Open a console as administrator, go on your drive P: and try to create a file or folder.
The issue is that your network doesn't know the identity of your local administrator account as it's not a network account.

Thus your installer fail to copy the cookie to the HOMEDRIVE+HOMEPATH.
Funny thing is that your user has permission to create and move files there, just not as an administrator during an installation ;)

This isn't a RabbitMQ issue as michael pointed out.
Also, I believe the restriction of the homedrive and homepath is from Erlang and not rabbitmq.
It would be nice if erlang gave another alternative to point to the windir to get the cookie as during an installation on windows, the administrator has full access for read and write in that folder.

But this is the wrong section for such a bug report.

**Comment by michaelklishin** [comment]
Please take this to the mailing list.
