### ISSUE TITLE
Apply consumer topic permissions (if any) to queue.{bind, unbind}

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1099]
This is a continuation to #1085. It was never done there.

**Comment by acogoluegnes** [comment]
There are 3 pieces of info in a topic permission (the exchange, the type of the permission [`write` | `read`], and the value of the permission). If we map them to a binding:
 * exchange: the exchange targeted by the binding (only if it's a topic-typed exchange)
 * type of permission: `write` or `read`? `configure` would also make sense for this
 * value of permission: regex match against the binding routing key

It could also make sense to apply the check to `exchange.{bind, unbind}`.

**Comment by acogoluegnes** [comment]
Not sure a new `configure` permission type would make sense, at least the way it's working now with topics in MQTT and STOMP. When a MQTT/STOMP client starts listening on a topic, the topic security check is done upstream in the respective plugin, against `read`. At the AMQP level, a binding between the topic exchange and an exclusive queue is created. So if there was another security check against `configure` when the binding is created, the `read` and `configure` value (regular expression to check against the binding routing key) would have to be the same, which doesn't make much sense.
So the most suited permission type seems to be `read`.

**Comment by michaelklishin** [comment]
@acogoluegnes topics in MQTT and STOMP are built around the idea of reading and writing. However, binding is a different story. Currently {queue, exchange}.{bind, unbind} operations require a read permission on the source exchange: http://www.rabbitmq.com/access-control.html. I assume this is coherent with your thinking?

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, it is!

**Comment by acogoluegnes** [comment]
I just noticed the [lookup of the exchange](https://github.com/rabbitmq/rabbitmq-common/pull/176/files#diff-98224c82bfd7f4172da6a5adff2c42b0R1704) breaks an [integration test in the Java client](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/test/java/com/rabbitmq/client/test/functional/BindingLifecycle.java#L195). The test tries to unbind non-existing exchanges, so `basic.unbind` now fails instead of silently doing nothing.

I think we'd better off checking the exchange exists and skip the topic permission check if it does not, to stick to the previous behavior.
