### ISSUE TITLE
Exclude applications that are not RabbitMQ plugins from the list of plugins

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-server#1124]
Currently, this is the list of plugins when RabbitMQ starts:

```
  rabbitmq_recent_history_exchange
  rabbitmq_management_agent
  cowlib
  cowboy
  rabbitmq_web_dispatch
  amqp_client
  rabbitmq_management
  rabbitmq_mqtt
  rabbitmq_web_mqtt
  rabbitmq_amqp1_0
  rabbitmq_stomp
  sockjs
  rabbitmq_web_stomp
  rabbitmq_tracing
  rabbitmq_trust_store
  rabbitmq_consistent_hash_exchange
  rabbitmq_web_mqtt_examples
  rabbitmq_top
  rabbitmq_auth_backend_ldap
  rabbitmq_federation
  rabbitmq_shovel
  rabbitmq_shovel_management
  rabbitmq_auth_mechanism_ssl
  rabbitmq_sharding
  rabbitmq_jms_topic_exchange
  rabbitmq_event_exchange
  rabbitmq_federation_management
  rabbitmq_web_stomp_examples
```
sockjs, cowboy, cowlib should not be present in this list. All applications that do not depend on `rabbit` should be removed from this list.

**Comment by dumbbell** [comment]
This new requirement should be communicated clearly in the release notes as well as on the [plugins development documentation](http://www.rabbitmq.com/plugin-development.html). Probably even a mail on rabbitmq-users@.

I believe many third-party plugins do not depend on `rabbit` in their `Makefile` or `$plugin.app` because it was not possible a year ago, probably less (ie. before the release build was fixed to get rid of the broker depending on its plugins). So if third-party plugin developers do not modify their plugin, they won't be listed anymore.
