### ISSUE TITLE
Rabbitmq - CENTOS 7 - Cannot Start As A Service

### ISSUE THREAD

**Issue by jdc91** [rabbitmq/rabbitmq-server#1138]
I am trying to setup RabbitMQ 3.6.6 on my CentOS7 Server. I have installed using  latest-stable official RPMs 
- RMQ-rabbitmq-server-3.6.6-1.el7.noarch.rpm also 
- ERLANG-LIGHTWEIGHT-erlang-19.2.3-1.el7.centos.x86_64.rpm

I have further enabled all ports required for rmq and set the linux permissive bool.
And I can get RMQ to successfully start via cli command
` sudo rabbitmq-server` Which allows me to even access the management console

 But when I try to start using `sudo systemctl start rabbitmq-server` as a service I get this error

> Job for rabbitmq-server.service failed. See 'systemctl status rabbitmq-server.service' and 'journalctl -xn' for details.

Then when I run `systemctl status rabbitmq-server.service` I get this!
![image](https://cloud.githubusercontent.com/assets/3422709/23647959/8c6e882a-033e-11e7-905d-87ab319bdeab.png)

```
rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; enabled)
   Active: failed (Result: exit-code) since Tue 2017-03-07 13:50:31 IST; 13s ago
  Process: 29669 ExecStop=/usr/sbin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
  Process: 29362 ExecStart=/usr/sbin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 29362 (code=exited, status=1/FAILURE)

```
Why I cant I start RMQ as a service on this setup??

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Please take this to rabbitmq-users and post full server logs. It is impossible to suggest much with just this output.

**Comment by lalit65** [comment]
[root@lalitsource yum.repos.d]# systemctl status rabbitmq-server.service 
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/rabbitmq-server.service.d
           └─limits.conf
   Active: failed (Result: exit-code) since Fri 2018-07-06 01:12:18 IST; 1min 42s ago
  Process: 16270 ExecStop=/usr/lib/rabbitmq/bin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
  Process: 16155 ExecStart=/usr/lib/rabbitmq/bin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 16155 (code=exited, status=1/FAILURE)

Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: attempted to contact: [rabbit@lalitsource]
Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: rabbit@lalitsource:
Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: * unable to connect to epmd (port 4369) on lalitsource: timeout (timed out)
Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: current node details:
Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: - node name: 'rabbitmq-cli-60@lalitsource'
Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: - home dir: /var/lib/rabbitmq
Jul 06 01:12:18 lalitsource.in rabbitmqctl[16270]: - cookie hash: 9gQg7jaSnWAiFC3JXEukCg==
Jul 06 01:12:18 lalitsource.in systemd[1]: Failed to start RabbitMQ broker.
Jul 06 01:12:18 lalitsource.in systemd[1]: Unit rabbitmq-server.service entered failed state.
Jul 06 01:12:18 lalitsource.in systemd[1]: rabbitmq-server.service failed.
[root@lalitsource yum.repos.d]# systemctl start rabbitmq-server.service 
Job for rabbitmq-server.service failed because the control process exited with error code. See "systemctl status rabbitmq-server.service" and "journalctl -xe" for details.
[root@lalitsource yum.repos.d]#

**Comment by michaelklishin** [comment]
@lalit65 this is not a support forum.

> unable to connect to epmd (port 4369) on work: timeout (timed out)

strongly suggests that something (e.g. SELinux or a firewall) blocks traffic on the [inter-node communication port](https://www.rabbitmq.com/networking.html#selinux-ports).

**Comment by michaelklishin** [comment]
There's also a dedicated doc guide to [troubleshooting networking](http://www.rabbitmq.com/troubleshooting-networking.html) efficiently and with as little guessing as possible.
