### ISSUE TITLE
Excute "eval" by rabbitmqctl fail, but MQ is normal

### ISSUE THREAD

**Issue by baoyonglei** [rabbitmq/rabbitmq-server#1145]
The command to excute is "/usr/local/lib/rabbitmq/sbin/rabbitmqctl eval 'rabbit_nodes:is_running(node(), rabbit).'",  and the result is:

Error: unable to connect to node rabbit@rabbitmqNode1: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbitmqNode1]

rabbit@rabbitmqNode1:
  * connected to epmd (port 4369) on rabbitmqNode1
  * node rabbit@rabbitmqNode1 up, 'rabbit' application running

current node details:
- node name: 'rabbitmq-cli-22971@xxxxxxxxxx'
- home dir: xxxxxx/rabbitmq
- cookie hash: xxxxxxxxxxxxxx

the return code indicates the command excuted fail, but I saw the output inclues "'rabbit' application running".    How could this happen?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
See [How Nodes (and CLI tools) Authenticate to Each Other](http://www.rabbitmq.com/clustering.html). The app is running but `rabbitmqctl` fails to authentiate because its effective user doesn't have the same Erlang cookie file as the server.
