### ISSUE TITLE
Happy Eyeballs (as in dual stack)

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#115]
We should consider using [Happy Eyeballs](http://en.wikipedia.org/wiki/Happy_Eyeballs) for detecting which stack (IPv4/IPv6) to prefer in dual-stack environments.

**Comment by lhoguin** [comment]
https://www.rfc-editor.org/rfc/rfc8305

We can do much of it for the server as part of a discovery process. But the algorithm is done to make detection fast for browsers, and we don't need to go that far since we only need to do that at listener start (or maybe in rabbit_prelaunch). We can still reuse much of it though: we still need to open connections for proper detection anyway.

There might be some components or rabbit that would benefit from the full algorithm though, like for communication between clusters since there we have to worry about the full path not just the ability to listen to connections.

**Comment by michaelklishin** [comment]
Close to nine years later we haven't seen much need to revisit this particular part, so let's assume that we better spend out time elsewhere.
