### ISSUE TITLE
is it possible to add a relational database as a message storage 

### ISSUE THREAD

**Issue by waleedsaud** [rabbitmq/rabbitmq-server#1152]
adding a relational database as a message storage like:
mysql , postgresql , MS sql , oracle db, etc.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
No and while we are interested in making message store or at least parts of it pluggable, [external data stores are not as attractive as it may seem](https://www.rabbitmq.com/blog/2011/01/20/rabbitmq-backing-stores-databases-and-disks/).

**Comment by waleedsaud** [comment]
thank you.
