### ISSUE TITLE
Unable to un-tar pre-release tar files

### ISSUE THREAD

**Issue by raghav0110** [rabbitmq/rabbitmq-server#1154]
I've been trying to un-tar the pre-release tar.xz packages and I get this error:

tar xf rabbitmq-server-3.7.500.14.tar.xz
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now 

Seems like it might be corrupted? I can un-tar the package of an older release version using the same command.

**Comment by michaelklishin** [comment]
I cannot reproduce with `badtar 2.8.3` and `libarchive 2.8.3`. The way we compress tarballs hasn't changed since 3.6.0 and this is not a commonly reported issue.

**Comment by michaelklishin** [comment]
Please note for the future:

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.
