### ISSUE TITLE
any user can delete default exchange (amq.*) but no one can not recreate default exchanges

### ISSUE THREAD

**Issue by pruthaMunshi** [rabbitmq/rabbitmq-server#1163]
Question regarding default exchanges.

We observed that any user can delete default exchanges from curl command as well as from management UI but Neither user nor admin can create default exchanges back again.
We tried to create default exchange(amq.topic) via curl command with admin credentials for one of the existing user but we are getting error as below. 

<img width="1097" alt="screen shot 2017-03-28 at 6 20 04 pm" src="https://cloud.githubusercontent.com/assets/19156363/24431752/86ee6950-13e3-11e7-9b2f-5bacf45f0ee8.png">

So If any user deletes default exchanges. Is there any way to recreate those default exchanges ? If there is no way to re-create the default exchange then why rabbitmq server allows to delete default  exchanges via any user ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
The only way is to re-create the vhost. It should be [no longer possible to delete the default exchange](https://github.com/rabbitmq/rabbitmq-common/blob/stable/src/rabbit_channel.erl#L1248) in recent 3.6.x releases and master.

**Comment by michaelklishin** [comment]
Also, `amq.*` are not default exchange. The default exchange is something very specific in the protocol. Those are pre-declared exchanges. I don't think the spec prohibits their deletion but it does reserve declaration of `amq.*` exchanges and there are system exchanges that use that naming pattern.

The answer is still the same: you have to re-create the vhost. Use definitions export/import and Shovels if you need to move data out of it to a new vhost first.

**Comment by pruthaMunshi** [comment]
@michaelklishin Thank you so much for your valuable response I really appreciate it :)
