### ISSUE TITLE
RabbitMQ crashes when queue has many unacked messages last client disconnects

### ISSUE THREAD

**Issue by chernser** [rabbitmq/rabbitmq-server#1164]
I have direct exchange and queue. 
I have simple client [source](https://gist.github.com/chernser/8f79a0e103354edad87d71e24b5c52e3)
1. Connects to rmq servers
2. Declares queue and exchange 
3. calls basic consume, but do not consume them 
4. publishes 10k messages 
5. closes connection

I have virtual host with 1Gb RAM

When script ends and closes connection, rabbitmq crashes (just terminated) with next log: 

> =INFO REPORT==== 29-Mar-2017::11:00:06 ===
vm_memory_high_watermark set. Memory used:881321872 allowed:787377356

>=WARNING REPORT==== 29-Mar-2017::11:00:06 ===
memory resource limit alarm set on node rabbit@inf.

>**********************************************************
>*** Publishers will be blocked until this alarm clears ***
>**********************************************************

After that I need to restart the rabbitmq. 

My test client can produce 30k messages and more, but rabbitmq keeps running, until connection is closes.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by chernser** [comment]
Why the issue is closed? The link to forum is broken.

**Comment by michaelklishin** [comment]
There is no evidence of RabbitMQ "crashes" in the log, only that a memory alarm was triggered.

Abusive publishers or publishers that continuously outpace consumers is a topic that has been discussed numerous times on rabbitmq-users. Your options are:

 * Using durable queues and publishing messages as persistent (your code explicitly publishes them as transient, *instructing* RabbitMQ to keep them in memory as much as possible)
 * Lazy queues
 * [Reducing limits for alarms](http://www.rabbitmq.com/alarms.html)
 * Message and/or queue TTL
 * Exclusive queues

You don't need to restart RabbitMQ for alarms to clear you need to acknowledge messages or wait until [client connection is considered to be gone](http://www.rabbitmq.com/heartbeats.html).

**Comment by chernser** [comment]
Yes, I have to start the rabbitmq because is becomes in state "not running"

**Comment by michaelklishin** [comment]
@chernser I don't have much to add to the above. This is a pathological case of a messages published as transient piling up without a consumer. The consequences and ways to address this are fairly well known and are discussed multiple times each month on rabbitmq-users.

The "not running" state is [due to a resource alarm being in effect](http://www.rabbitmq.com/alarms.html).

**Comment by chernser** [comment]
@michaelklishin I mean, that server should not crash when consumer dies and queue has alot messages. I clearly understand, that we need to have limit and they are solving the problem. 
But, the root cause of this BUG seems in way queue is cleared or in wrong consumer termination logic (for example, when consumer dies, RMQ tries to fetch all messages from mnesia)

**Comment by michaelklishin** [comment]
@chernser please do read the options listed above and my explanation. Are you sure you really understand what's going on and not jumping to the conclusions too quickly? Are you sure that your problem is novel and is absolutely should be considered a RabbitMQ bug or can it be an unfortunate combination of your application's behaviour, resources available to your node and your interpretation of the outcome? You are so confident that you know what the root cause is, is it really the case or are you guessing (the "seems" part suggests you are).

You script tells RabbitMQ to keep 10K of 100kB messages in memory for as long as possible (`delivery_mode = 1`) and then you assume that a memory alarm with 1 GB of RAM total on the host is an issue with RabbitMQ. You're ignoring the fact that

 * You could have used a durable queue with messages published as persistent
 * Even then at some point a large number of unacknowledged messages will likely trigger an alarm
 * Consumer disconnects [are not detected immediately](http://www.rabbitmq.com/heartbeats.html) in distributed systems
 * You could have used a message TTL value
 * Not having consumers online for a long enough time means [you have to make tough choices](https://groups.google.com/d/msg/rabbitmq-users/c0Pq4yEavmw/wiPHpbpICwAJ) (or use a long term data store, which RabbitMQ isn't really meant to be)

**Comment by michaelklishin** [comment]
If you really investigated how persistence works ([docs](http://www.rabbitmq.com/memory.html), [internals](https://github.com/rabbitmq/internals)) you would have known that messages are not stored in Mnesia.

**Comment by michaelklishin** [comment]
In addition, your consumer [consumes without a QoS on its channel](https://gist.github.com/chernser/8f79a0e103354edad87d71e24b5c52e3#file-rabbittest-py-L30), which tells RabbitMQ to deliver messages to it as quickly as possible, and that means they are either kept in RAM or loaded from disk eagerly.

**Comment by michaelklishin** [comment]
The has drawn [quite a longer answer on rabbitmq-users](https://groups.google.com/d/msg/rabbitmq-users/Sl8So_xf4Vg/6sCJUJRDGAAJ).
