### ISSUE TITLE
can declare federation in the config file?

### ISSUE THREAD

**Issue by antimoth** [rabbitmq/rabbitmq-server#1168]
we using rabbitmq-2.8.6 and preparing to upgrade it to a later version, such as 3.6.5.
in our situation, federations are declared in the <rabbitmq.cofig> file, but docs for latest rabbitmq guide  us to make them work by using web management or rabbitmqctl.  so we no sure about that can declare federations in the config file?
can anyone gives an explicit answer, thks.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
You can't. `rabbitmqctl`, HTTP API or management UI, and [definitions import](http://www.rabbitmq.com/management.html) are the 4 options you have (the latter requires [federation-management](https://github.com/rabbitmq/rabbitmq-federation-management/)).
