### ISSUE TITLE
What certificate is required on client side to connect to RabbitMQ broker with SSL enabled ?

### ISSUE THREAD

**Issue by BugRaptor** [rabbitmq/rabbitmq-server#1177]
My RabbitMQ server is configured with SSL option verify = verify_none and fail_if_no_peer = false.

This way:
```
[
  {rabbit, [
     {ssl_listeners, [5671]},
     {ssl_options, [{cacertfile,"/path/to/testca/cacert.pem"},
                    {certfile,"/path/to/server/cert.pem"},
                    {keyfile,"/path/to/server/key.pem"},
                    {verify,verify_none},
                    {fail_if_no_peer_cert,false}]}
   ]}
].
```
The server certificate has been generated and signed with a Let's Encrypt intermediate certificate: [Let's Encrypt Authority X3 (IdenTrust cross-signed)](https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt)

I wrote a Windows C# .Net Client app connecting to the broker with SSL enabled on port #5671. The connection succeeds only if I have installed the Let's Encrypt intermediate certificate on the client computer's certificat store. 

If I remove this certificate from the client certificate store, the client fails to connect to the broker. (An exception is thrown).

Is that right ?

I thought it was not necessary to install specific certificates when deploying the client app... Was I wrong ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by BugRaptor** [comment]
Ok, Sorry for the misplacement. I copied myy question on the rabbitmq-user mailing list.

**Comment by ryanvgates** [comment]
@BugRaptor can you include a link to the discussion on the rabbitmq-user mailing list?

**Comment by lukebakken** [comment]
Hi @ryanvgates I believe this is the discussion:

https://groups.google.com/d/topic/rabbitmq-users/MzPje5n_U7A/discussion
