### ISSUE TITLE
man page for rabbitmqctl does not show any commands

### ISSUE THREAD

**Issue by oneiros-de** [rabbitmq/rabbitmq-server#1180]
The output of `man rabbitmqctl` lacks all commands for rabbitmqctl; they are in the file but are not displayed. 
An example:
```
COMMANDS
   Application and Cluster Management

           Stops the Erlang node on which RabbitMQ is running. To restart the node follow the instructions for Running the Server in the installation guide[1].

           If a pid_file is specified, also waits for the process specified there to terminate. See the description of the wait command below for details on
           this file.

           For example:

           rabbitmqctl stop

           This command instructs the RabbitMQ node to terminate.

           Stops the RabbitMQ application, leaving the Erlang node running.

           This command is typically run prior to performing other management actions that require the RabbitMQ application to be stopped, e.g.  reset.

           For example:

           rabbitmqctl stop_app

           This command instructs the RabbitMQ node to stop the RabbitMQ application.

           Starts the RabbitMQ application.

           This command is typically run after performing other management actions that required the RabbitMQ application to be stopped, e.g.  reset.

           For example:
```
This happens with the debian package for 3.6.5 from pivotal and the ubuntu package for 3.6.9 (also from pivotal).

I only checked the man page for rabbitmqctl; I suspect the other man pages have similar deficits.

**Comment by michaelklishin** [comment]
We will investigate.

In the meantime you can use [a Web version of the man page](https://www.rabbitmq.com/man/rabbitmqctl.1.man.html).

**Comment by dumbbell** [comment]
Hi @oneiros-de!

I see the bad rendering issue on various platforms (Debian, FreeBSD, OS X) too. Here is a description of my findings so far.

Currently, manpages are generated from a [DocBook source](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq_v3_6_9/docs/rabbitmqctl.1.xml) using xmlto(1) and stylesheets from [docbook-xsl](http://docbook.sourceforge.net/).

On my laptop, the man(7) output for the `stop` command is:
```
.HP \w'\fBstop\fR\ 'u \fBstop\fR [\fIpid_file\fR]
.RS 4
Stops the Erlang node on which RabbitMQ is running\&. To restart the node follow the instructions for
Running the Server
in the
\m[blue]\fBinstallation guide\fR\m[]\&\s-2\u[1]\d\s+2\&.
```

As you found out, the command name (`stop [pid_file]`) doesn't appear in the output:
![Bad rendering of the description list](https://cloud.githubusercontent.com/assets/159804/24998100/4935ab8e-2039-11e7-83df-0ca660a1c383.png)

Here is the description of the `.HP` macro in man(7), the markup language used here:
> HP
> Begin a paragraph whose initial output line is left-justified, but subsequent output lines are indented, with the following syntax:
>
>     .HP [width]

So the macro takes a single argument, but here, we give two:
* the width, `\w'\fBstop\fR\ 'u`
* the first line, `\fBstop\fR [\fIpid_file\fR]`

Therefore, the first "line" is swallowed by the macro. If I manually split that into two lines, like this:
```
.HP \w'\fBstop\fR\ 'u
\fBstop\fR [\fIpid_file\fR]
.RS 4
Stops the Erlang node on which RabbitMQ is running\&. To restart the node follow the instructions for
Running the Server
in the
\m[blue]\fBinstallation guide\fR\m[]\&\s-2\u[1]\d\s+2\&.
```

Then the manpage is rendered correctly:
![Correct rendering of the description list](https://cloud.githubusercontent.com/assets/159804/24998407/4e2f632c-203a-11e7-8368-a895acb4b89b.png)

I have docbook-xsl 1.76.1 installed, which is not the latest version. I tried with the latest, 1.79.1, but the problem is the same. mandoc(1) is used to render and display the manpage on FreeBSD, groff(1) on OS X and I have a hard time to follow which `*roff` is used on Debian Wheezy. Anyway, they all seem to be strict enough to not render that badly generated `.HP` macro.

I'm going to experiment a bit more with xmlto(1). But there could be other unnoticed rendering issues and my confidence in this toolchain is getting low. We may have to switch away from DocBook.
