### ISSUE TITLE
AMQP 1.0: should default max frame size be/reported as `unlimited`?

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#11838]
### Describe the bug

* Open an AMQP 1.0 connection without specifying max frame size. RabbitMQ will use `unlimited` internally.
* Use HTTP API to list connections, note that `frame_max` will be set to `unlimited` in the JSON response.

The AMQP 1.0 spec specifies that `max-frame-size` is an `uint`, so we should convert `unlimited` to `4294967295`, perhaps.

https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-open

The reason I noticed this is that I am using `EasyNetQ.Management.Client` to query the HTTP API, and this breaks the expected JSON schema when deserializing responses from the HTTP API. It's easy to work-around - we can specify a max frame size when opening a connection, but I suspect that returning `unlimited` isn't a good practice here.

### Expected behavior

Instead of `unlimited`, use `4294967295` in the response.

**Comment by michaelklishin** [comment]
I'd say it would be reasonable to use something much smaller than 4294967295 bytes (4 GiB) by default. Something comparable to the maximum message size plus some "extra padding" to make sure even the largest message can fit into a single frame with all the metadata, so, something like 24 MiB?

**Comment by ansd** [comment]
@lukebakken internally, RabbitMQ will use `unlimited` because the spec says:
>  If this field is not set it means that the peer does not impose any specific limit.

We can convert `unlimited` to uint max when this field is reported given that some HTTP API clients expect an integer here.

@michaelklishin its the client's choice whether it sets `max-frame-size` in its outgoing open frame and to what value the client sets this value. The question here is what RabbitMQ reports in its HTTP API when the client leaves this field unset.
