### ISSUE TITLE
Cost of creating and closing channel 

### ISSUE THREAD

**Issue by iammehrabalam** [rabbitmq/rabbitmq-server#1185]
Hi,
I am using nodejs rabbitmq client [https://github.com/squaremo/amqp.node](url) to publish event in queue. For this currently, I am closing and opening a channel for every event to publish.

My query is 
**what are the cost of creating and closing channel in rabbitmq for every single event to publish?**

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Opening a new channel is a round trip. So is closing a channel. There is absolutely no need to open a new channel for every message you publish. Channels are supposed to be reasonably long lived but can be closed due to a protocol exception (e.g. if you try to publish to an exchange that does not exist or re-declare a queue with mismatching parameters).
