### ISSUE TITLE
rabbit high memory for binaries while there are no messages in queue 

### ISSUE THREAD

**Issue by rom-stratoscale** [rabbitmq/rabbitmq-server#1193]
Cannot explain why - from what I understand, binaries are referenced by messages in queue.
I have almost no messages, I even purged the queues. But still, the memory used by binaries stays high.
Any explanation?

[root@stratonode_c1n0 ~]# rabbitmqctl status
Status of node 'rabbit@stratonode_c1n0.node.strato' ...
[{pid,26013},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.5.1"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.5.1"},
      {webmachine,"webmachine","1.10.3-rmq3.5.1-gite9359c7"},
      {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.5.1-git680dba8"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.5.1"},
      {rabbit,"RabbitMQ","3.5.1"},
      {mnesia,"MNESIA  CXC 138 12","4.11"},
      {os_mon,"CPO  CXC 138 46","2.2.14"},
      {inets,"INETS  CXC 138 49","5.9.8"},
      {amqp_client,"RabbitMQ AMQP Client","3.5.1"},
      {xmerl,"XML parser","1.3.6"},
      {sasl,"SASL  CXC 138 11","2.3.4"},
      {stdlib,"ERTS  CXC 138 10","1.19.4"},
      {kernel,"ERTS  CXC 138 10","2.16.4"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:12:12] [async-threads:30] [hipe] [kernel-poll:true]\n"},
 {memory,
     [{total,905836864},
      {connection_readers,9558376},
      {connection_writers,2105608},
      {connection_channels,12461448},
      {connection_other,20718984},
      {queue_procs,38772384},
      {queue_slave_procs,0},
      {plugins,1144784},
      {other_proc,14630992},
      {mnesia,1707992},
      {mgmt_db,13784872},
      {msg_index,332632},
      {other_ets,2270360},
      {binary,744367816},
      {code,20237564},
      {atom,4000425},
      {other_system,19742627}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,19999211520},
 {disk_free_limit,50000000},
 {disk_free,8971374592},
 {file_descriptors,
     [{total_limit,99900},
      {total_used,722},
      {sockets_limit,89908},
      {sockets_used,719}]},
 {processes,[{limit,1048576},{used,9088}]},
 {run_queue,0},
 {uptime,380114}]

![image](https://cloud.githubusercontent.com/assets/5699571/25370171/90a99c94-2991-11e7-9dfc-f90465fc3186.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with.

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server and client versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thanks you.

**Comment by michaelklishin** [comment]
Consider searching rabbitmq-users archives before posting questions. See rabbitmq-top and upgrade to Erlang 19, where binary heap collection is a lot more proactive (this means upgrading RabbitMQ from 3.5.1, which is not a bad idea anyway).
