### ISSUE TITLE
tcp connection succeeded but erlang distribution failed

### ISSUE THREAD

**Issue by sandeeppalla** [rabbitmq/rabbitmq-server#1197]
Hi,

Observing below error in rabbitMQ server.
Error:
  * connected to epmd (port 4369) on SERVER1-1
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: hostname mismatch?
  * suggestion: is the cookie set correctly?
  * suggestion: is the Erlang distribution using TLS?

RabbitMQ 3.5.7 and Erlang version 19.1 installed on CentOS operation system.

Can you help me with how to resolve this.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with.

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server and client versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thanks you.

**Comment by michaelklishin** [comment]
`rabbitmqctl` already provides 3 options which you posted:

```
suggestion: hostname mismatch?
suggestion: is the cookie set correctly?
suggestion: is the Erlang distribution using TLS?
```

9 times out of 10 it's due to a Erlang cookie (a shared secret) mismatch. See How Nodes (and CLI tools) Authenticate to Each Other: the Erlang Cookie [in documentation](http://www.rabbitmq.com/clustering.html).

This is one of the most common questions that's been discussed numerous times on rabbitmq-users and elsewhere on the Web.

**Comment by sandeeppalla** [comment]
Thank you very much for your reply michael.

Can you help me with how to troubleshot " times out of 10 it's due to a Erlang cookie (a shared secret) mismatch" .
I am new to this RabbitMQ.

Regards,
Sandeep Palla

**Comment by michaelklishin** [comment]
@sandeeppalla please do read the docs and the above comment. This is not a support venue. There is plenty of existing threads and a mailing list solely dedicated to questions and discussions.
