### ISSUE TITLE
"Key exists" error when reading MQTT data

### ISSUE THREAD

**Issue by yckim1** [rabbitmq/rabbitmq-server#1199]
"Key exists" error during service using Rabbitmq's MQTT Plugin
We were sending messages using MQTT and receiving them using MQTT and did not use message ID
The error log refers to the attached file.

 - rabbitmq version : rabbitmq_server-3.6.4
 - erlang version : otp_src_19.0
 - os information : Linux tb-101.vclinux.dev 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
![image](https://cloud.githubusercontent.com/assets/28076134/25464172/ccf7f010-2b35-11e7-92ed-00cd0dd646ba.png)

**Comment by michaelklishin** [comment]
How can we reproduce this?

**Comment by michaelklishin** [comment]
Also, please test against 3.6.9 as 3.6.4 isn't getting any more updates.

**Comment by lukebakken** [comment]
@michaelklishin - I thought I'd provide details of how I tried to reproduce this issue:

* Built RabbitMQ and the MQTT plugin using the umbrella project & deps checked out on the `rabbitmq_v3_6_4` tag
* Started via `cd deps/rabbitmq_mqtt; make run-broker`. In order to aid in debugging, I also added `redbug` to the code path via the console.
* Ran [this sample code](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/simple/main.go), only modifying the connection to use `localhost` and the `Subscribe()` / `Publish()` arguments to specify `1` for QoS. Everything ran fine, as expected.
* Modifed the code [in this branch](https://github.com/eclipse/paho.mqtt.golang/compare/master...lukebakken:lrb/rabbitmq-server_1199) to send more messages, not wait for responses, and use the same `MessageID` value. I thought that perhaps this value is the same that is inserted [here](https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/src/rabbit_mqtt_processor.erl#L366). Running this modified code doesn't reproduce the issue, though.
* I used `redbug` to ensure that `{1, 1}` is returned by [`delivery_qos`](https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/src/rabbit_mqtt_processor.erl#L335):
    ```
    (rabbit@localhost)3> redbug:start(30000, 25, "rabbit_mqtt_processor:delivery_qos->return").
    {214,1}
                         
    % 13:29:39 <0.398.0>({rabbit_mqtt_reader,init,1})
    % rabbit_mqtt_processor:delivery_qos(<<"amq.ctag-7XdwG_ahNl3-sKR0s85v1w">>, [{<<"x-mqtt-publish-qos">>,byte,1},{<<"x-mqtt-dup">>,bool,false}], {proc_state,#Port<0.7412>,

    % TRIMMED
                         
    % 13:29:39 <0.398.0>({rabbit_mqtt_reader,init,1})
    % rabbit_mqtt_processor:delivery_qos/3 -> {1,1}
    ```
* `next_msg_id()` does in fact increment the current message id in the process state, so at this point I'm left scratching my head. I wonder if there is something about the client library used by @yckim1 that does not follow the MQTT protocol spec. You can see in the attached screenshot that QoS has a value of `1`, which requires a message id (["packet identifier"](http://www.hivemq.com/blog/mqtt-essentials-part-4-mqtt-publish-subscribe-unsubscribe)) .

**Comment by michaelklishin** [comment]
@lukebakken thanks. Yes, it would be great to see some code that triggers this, even after a period of time.

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-mqtt/issues/132 since this repo is not concerned with MQTT.
