### ISSUE TITLE
RabbitMQ Server v3.6.9 does not honor `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` when used to set Erlang Cookie

### ISSUE THREAD

**Issue by LeeFowlerCU** [rabbitmq/rabbitmq-server#1206]
The `rabbitmq-server` script does not honor a value of `-setcookie <cookie>` for the `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` environment variable.

Steps to reproduce:
1. Pull RabbitMQ 3.6.9 Docker Image:
`docker pull rabbitmq:3.6.9`
2. Bash into a docker container from that image:
`docker run --rm -ti rabbitmq:3.6.9 /bin/bash`
3. Set RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS environment variable
`export RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-setcookie QWERTY'`
4. Run `rabbitmq-server` and observe that `.erlang.cookie` has an incorrect value written to it
`rabbitmq-server -detached`
`cd ~`
`cat .erlang.cookie`

**Comment by michaelklishin** [comment]
When there is no `~/.erlang.cookie` it will be created with a generated value, not the previous value from the command line.

**Comment by michaelklishin** [comment]
The above is how the Erlang VM works; RabbitMQ does not manage the cookie or affect what it value is when it is generated.

**Comment by michaelklishin** [comment]
The value is respected:

```
RABBITMQ_ALLOW_INPUT=1 RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-setcookie QWERTY' rabbitmq-server
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:128] [hipe] [kernel-poll:true] [dtrace]

Eshell V8.3  (abort with ^G)
(rabbit@mercurio)1>
              RabbitMQ 3.6.9. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /Users/antares/Tools/rabbitmq/generic/var/log/rabbitmq/rabbit@mercurio.log
  ######  ##        /Users/antares/Tools/rabbitmq/generic/var/log/rabbitmq/rabbit@mercurio-sasl.log
  ##########
              Starting broker...
 completed with 16 plugins.

(hit Enter twice to drop into an Erlang shell)

(rabbit@mercurio)1> erlang:get_cookie().
'QWERTY'
```

**Comment by LeeFowlerCU** [comment]
I'm curious as to why `~/.erlang.cookie` would be written to the filesystem if the cookie is passed to the VM as a command line parameter.

**Comment by michaelklishin** [comment]
That's a good question. I verified that it is indeed the case, I suspect that the VM unconditionally generates the file if it's not there. Perhaps someone on the erlang-questions list can answer this.

I'd recommend generating/populating the file instead of using `-setcookie` as the latter is visible in `ps` output and can be captured by tools without a lot of privileges, intentionally or not.

**Comment by LeeFowlerCU** [comment]
@michaelklishin Thanks for your help. That does indeed seem to be the best course of action here.

**Comment by michaelklishin** [comment]
I don't see any explanation in http://erlang.org/doc/reference_manual/distributed.html, and `-setcookie` on the command line is the same as calling `erlang:set_cookie/2` after the node starts, which according to the docs is the function used to set the cookie from the cookie file.

Since both methods eventually call the same built-in function, I doubt there is a big idea behind this behavior, more likely that the VM flag was introduced at a later point e.g. for developer convenience.

**Comment by michaelklishin** [comment]
Interestingly, http://erlang.org/documentation/doc-5.4.3/doc/reference_manual/distributed.html contains this piece:

> If the node is started without the command line flag, then the node will create the cookie from the contents of the file $HOME/.erlang.cookie,
> where $HOME is the user's home directory.
> If the file does not exist, it will be created and contain a random character sequence.

That doc guide is from an OTP release which is about 13 years old. So it is possible that at some point things did work the way you expect. Looks like the docs have been edited since then. Figuring out why will take some code archeology :/

**Comment by michaelklishin** [comment]
Here's the same guide from 19.3: http://erlang.org/documentation/doc-8.3/doc/reference_manual/distributed.html#id88372. So yes, the guide is there but the wording is different.

**Comment by LeeFowlerCU** [comment]
It's the default behavior of the Erlang VM to create the `erlang.cookie` file if no `-setcookie` argument is supplied on the command line, which is why it's interesting that it would be both respectful of the `-setcookie` supplied by the `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` environment variable AND also creating the `.erlang.cookie` file as well.

**Comment by michaelklishin** [comment]
@LeeFowlerCU I understand but I don't have an explanation.

Also note that the cookie can be set programmatically, in fact, our next gen CLI tools have a command line switch for setting it because it can be more convenient or obvious to some.

Therefore the number of possible scenarios (and possible reasons for confusion) is greater than 2 :)

**Comment by binarin** [comment]
Can it be the prelaunch process at https://github.com/rabbitmq/rabbitmq-server/blob/4ca58835cf227703a9fc8953d8d089571fbf6461/scripts/rabbitmq-server#L83 ? Looks like it don't get `_ERL_ARGS` but still tries to start a named node.

**Comment by michaelklishin** [comment]
@binarin good find. Yes, that process may be very short lived but will still create the cookie.
