### ISSUE TITLE
perf-test result is not expected

### ISSUE THREAD

**Issue by a2888409** [rabbitmq/rabbitmq-server#1207]
Hello,
       Recently, i have doing some performence test with rabbitmq, and using official tool [rabbitmq-perf-test](https://github.com/rabbitmq/rabbitmq-perf-test).But in some cases, the result is not meet our expected.The Details can be seen as follows:
       In every experiment, We started 50 producers and 200 consumers, the producer perf-test param can be seen as follows:
    'name': 'benchmark',
    'type': 'simple',
    'uri': 'amqp://aaa:bbb@10.153.92.16:5672',
    'params': [{
        'time-limit': 600,
        'producer-count': 200,
        'min-msg-size': 100,
        'auto-ack': true,
        'routing-key':'testKey',
        'queue-names': ['benchmarkqueue']
    }]
   as you can see , we use autoAck mode, and message size is 100Byte, and only declared one queue. Consumer's param can be seen as follows:
      [{
    'name': 'benchmark',
    'type': 'simple',
    'uri': 'amqp://aaa:bbb@10.153.92.16:5672',
    'params': [{
        'time-limit': 600,
        'consumer-count': 200,
        'min-msg-size': 100,
        'routing-key':'testKey',
        'auto-ack': true,
        'queue-names': ['benchmarkqueue']
    }]
}]
       FirstLy, we run perf-test on virtual machines with 4 vCPUs and 8GB of RAM, the average sent rate is 21653/s.
       Secondly,  we run perf-test on virtual machines with 8 vCPUs and 16GB of RAM, the average sent rate actually is 12310/s. We expect the performence in 8 vCPUS' machine is better than the 4 vCpus. But it seems  8-core CPU performance is worse than the performance of the 4-core CPU.
       It makes me very confused, Coud you please give me some suggestion about what is wrong in my performence test?
       Appreciate  you reply.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
A single queue can only use one CPU core on the hot code path. If a workload absolutely cannot be adapted to use multiple queues (it's a rare scenario), [rabbitmq-sharding](https://github.com/rabbitmq/rabbitmq-sharding/) can be used to trade off total ordering for parallelism (provided enough cores).

It is also important whether PerfTest runs on the same node as RabbitMQ, what scheduler binding type in the Erlang VM is used, and so on. This is mailing list material.
