### ISSUE TITLE
Dead letter exchange policy not being set

### ISSUE THREAD

**Issue by kamranahmedse** [rabbitmq/rabbitmq-server#1212]
If I set `dead-letter-exchange` explicitly when creating a queue, it works;  but I am unable to set it using the policy.

I have tried to add the policy through the admin panel as well as `rabbitmqctl` and it doesn't seem to work with either of them.

```
rabbitmqctl set_policy email_dlx_po ".*" '{"dead-letter-exchange": "email_dead_ex"}' --priority 1 --apply-to queues
```

Am I missing something here?

**Comment by corey-aloia** [comment]
@kamranahmedse curious what the solution for this was? I seem to be having the same issue. I can set the dlx via the queue argument when creating the queue, but when doing via a policy, it does not seem to work

**Comment by kamranahmedse** [comment]
@corey-aloia I don't remember unfortunately. I am not sure if [something in the docs helped](https://www.rabbitmq.com/dlx.html#using-optional-queue-arguments).

**Comment by corey-aloia** [comment]
@kamranahmedse I've over the docs and tried everything :( maybe I re-open the bug. For now I am enabling via a queue argument:
`rabbitmqadmin declare queue name=$CONSUMER_QUEUE_NAME queue_type=quorum arguments='{"x-dead-letter-exchange":"'$DEAD_LETTER_EXCHANGE'"}'`

And this works and I can see the messages in my dlx queue, but if I declare the queue without the arguments, and instead create a policy:
`rabbitmqadmin declare policy name=dlx definition='{"dead-letter-exchange": "'$DEAD_LETTER_EXCHANGE'"}' pattern=".*" apply-to=queues`

It doesn't work. Anyway, I might have to reopen a similar bug..... just strange that yours if from 6 years ago and I seem to have the exact same issue

**Comment by corey-aloia** [comment]
@kamranahmedse figured it out, will post here in case it helps someone in the future: I had assumer rabbitmq would merge policies, and that the priority was only for conflicting policies. As it turns out, if you have a wildcard policy that you want to set on all queues, and then a queue specific policy that you only want for 1 queue, rabbitmq will still only apply the policy with the highest priority. Even if the policy don't overlap in anyway. Shame. It would make sense to merge these IMO otherwise you end up copying-pasting your general policy if you also want a queue-specici policy

**Comment by michaelklishin** [comment]
@corey-aloia FWIW this was an intentional design decision.

[Operator Policies](https://rabbitmq.com/parameters.html#operator-policies) can be abused to serve as a default, even though they are there to allow human operators to put some guardrails in place.
