### ISSUE TITLE
ha-mode nodes breaks mirroring

### ISSUE THREAD

**Issue by quixoten** [rabbitmq/rabbitmq-server#1219]
I'm using ha-mode nodes to shuffle queues around in my rabbitmq cluster to balance the load. I've found a couple scenarios that break. 

Rabbitmq Version: 3.6.9
Erlang Version: 18.2
Cluster size: 5

All tests start out with a single policy of:

```
ha-two queues .* {"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"} 100
```

Each test then adds a policy in the form of:

```
test_policy full_queue_name {"ha-mode":"nodes","ha-params":[polciy_nodes],"ha-sync-mode":"automatic"} 200
```

| current nodes | policy nodes | resulting nodes | active policy |result |
| --- | --- |--- | --- | --- |
| 2, 4 | 1, 3 | 1, 4| ha-two (expected test_policy) | :skull_and_crossbones: |
| 2, 1 | 2, 3 | 2, 3| test_policy | :white_check_mark: |
| 2, 3 | 4, 3 | 3, 4| test_policy | :warning: |
| 3, 4 | 2, 1 | 2, 4| ha-two (expected test_policy) | :skull_and_crossbones: |

:skull_and_crossbones: did not apply the policy and ignores further policy changes
:warning: applied the policy but did not honor node order
:white_check_mark: result matched expectations

I also can pretty reliably get in situations where a policy remains applied to a queue even after the policy itself is deleted. I've found rolling restarts across the entire cluster the only way to recovery from this state.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Only one policy is in effect at a time. If multiple policies have the same priority, assume that the effective one will be picked at random.

**Comment by michaelklishin** [comment]
Please post actual `rabbitmqctl` (or HTTP API) calls when you post this to rabbitmq-users.

```
ha-two queues .* {"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"} 100
```

uses positional arguments and that's not how priorities are specified to `rabbitmqctl set_policy`. This could be a typo or a misunderstanding of the CLI, that's why we must have an actual shell transcript.

**Comment by michaelklishin** [comment]
Of course, it's quite easy to verify if the policies have the priorities you think they do: `rabbitmqctl list_policies`.

**Comment by quixoten** [comment]
Yeah, that output is from the list_policies command. I used

```
sudo rabbitmqctl set_policy test_policy "full_queue_name" '{"ha-mode":"nodes","ha-params":["node1","node2"],"ha-sync-mode":"automatic"}' --priority 200 --apply-to queues
```

to apply the test policy

**Comment by quixoten** [comment]
Here's a link to the forum post: https://groups.google.com/forum/#!topic/rabbitmq-users/lFjy51tPZsM
