### ISSUE TITLE
Releases links are removed too quickly

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-server#1230]
When 3.6.10 RC2 was posted, the links for RC1 were removed right way.  We rely on those links to build Vagrant boxes and AMIs.  Is it possible to keep the links alive for X days and publish a rule for when they will be removed.

**Comment by michaelklishin** [comment]
We will consider it.

**Comment by michaelklishin** [comment]
We can keep two most recent milestone releases for 3.6.x (current stable release series). For 3.7.x it makes a lot less sense because the number of people relying on those milestones is really small.

What we would like to avoid is having a lot of preview releases that make it more difficult to find a GA one on GitHub unless you have a direct link.
