### ISSUE TITLE
Error after reboot

### ISSUE THREAD

**Issue by AlexCppns** [rabbitmq/rabbitmq-server#1236]
I am getting the following error after a reboot of the server:

```
Got response code 500 with body {"error":"Internal Server Error","reason":"{error,\n {exit,\n {{function_clause,\n [{rabbit_mgmt_stats_tables,index,\n [#Ref<0.2533122261.1431961603.168973>],\n [{file,\"src/rabbit_mgmt_stats_tables.erl\"},{line,154}]},\n {rabbit_mgmt_stats,blank,0,\n [{file,\"src/rabbit_mgmt_stats.erl\"},{line,318}]},\n {rabbit_mgmt_stats,sum,1,\n [{file,\"src/rabbit_mgmt_stats.erl\"},{line,133}]},\n {rabbit_mgmt_db,overview_sum,2,\n [{file,\"src/rabbit_mgmt_db.erl\"},{line,635}]},\n {rabbit_mgmt_db,'-handle_call/3-lc$^1/1-0-',2,\n [{file,\"src/rabbit_mgmt_db.erl\"},{line,247}]},\n {rabbit_mgmt_db,handle_call,3,\n [{file,\"src/rabbit_mgmt_db.erl\"},{line,247}]},\n {gen_server2,handle_msg,2,\n [{file,\"src/gen_server2.erl\"},{line,1028}]},\n {proc_lib,wake_up,3,[{file,\"proc_lib.erl\"},{line,257}]}]},\n {gen_server2,call,\n [{global,rabbit_mgmt_db},\n {get_overview,all,{no_range,no_range,no_range,no_range}},\n infinity]}},\n [{gen_server2,call,3,[{file,\"src/gen_server2.erl\"},{line,340}]},\n {rabbit_misc,with_exit_handler,2,\n [{file,\"src/rabbit_misc.erl\"},{line,504}]},\n {rabbit_mgmt_wm_overview,to_json,2,\n [{file,\"src/rabbit_mgmt_wm_overview.erl\"},{line,65}]},\n {webmachine_resource,resource_call,3,\n [{file,\"src/webmachine_resource.erl\"},{line,186}]},\n {webmachine_resource,do,3,\n [{file,\"src/webmachine_resource.erl\"},{line,142}]},\n {webmachine_decision_core,resource_call,1,\n [{file,\"src/webmachine_decision_core.erl\"},{line,48}]},\n {webmachine_decision_core,decision,1,\n [{file,\"src/webmachine_decision_core.erl\"},{line,558}]},\n {webmachine_decision_core,handle_request,2,\n [{file,\"src/webmachine_decision_core.erl\"},{line,33}]}]}}\n"}
```

I emptied the queues but that didnt change anything...

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
You can disable management plugin with `rabbitmq-plugins disable rabbitmq_management --offline` (has to be done on all nodes) and then re-enable it once the node starts. That's about as much as I can recommend from a single stack trace.

**Comment by michaelklishin** [comment]
Actually, so there is no evidence that this prevents node startup as it comes from an HTTP API handler for `GET /api/overview`. However, disabling and re-enabling the plugin should reset all of its state. Other ways to reset the plugin (e.g. in versions older than 3.6.7) are [documented](http://www.rabbitmq.com/management.html).

**Comment by AlexCppns** [comment]
@michaelklishin Thanks for the quick reply. I have tried to disable/enable the plugins without luck. I am trying to gather more information and make a post in the Google Group
