### ISSUE TITLE
Update RABBITMQ_SERVER_ERL_ARGS default value in documentation

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#1240]
As mentioned in [ERL-430](https://bugs.erlang.org/browse/ERL-430?focusedCommentId=12366&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12366), setting `RABBITMQ_SERVER_ERL_ARGS` should replace the standard arguments, but because it's added before `+K true`, it has no effect on kernel polling.

**Comment by michaelklishin** [comment]
This is intentional. Almost always those who disable kernel polling do so by accident.

**Comment by gerhard** [comment]
Should there be a different flag to disable kernel polling?

**Comment by michaelklishin** [comment]
Why would anyone want to disable kernel polling (other than cases such as ERL-430)?

**Comment by michaelklishin** [comment]
There is `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` now but a lot of Stack Overflow threads and such use `RABBITMQ_SERVER_ERL_ARGS`, which means kernel polling, max process limit, [disabled] Nagle's algorithm will all be overwritten. Warnings in the log won't change much because as we know all too well now, users only read logs when things go south.

**Comment by gerhard** [comment]
In which case, updating the documentation which is outdated should be sufficient.

**Comment by gerhard** [comment]
👍
