### ISSUE TITLE
RabbitMQ: Control messages sent to subscribers

### ISSUE THREAD

**Issue by M22an** [rabbitmq/rabbitmq-server#1244]
I am using a subscription based consumer model for RabbitMQ. All messages are pushed to the same queue. The prefetch count is also set to 10 for all consumers. The messages in the queue are of different types.

I want a mechanism to tell RabbitMQ server to send only X number of messages of Type A and Y number of messages of Type B and Z number of messages of Type C to any consumer at any given instant.

I know that I can achieve this by having three different queues to hold different types of messages and have all consumers connect to the queues using different prefetch counts.

I am looking for a way to achieve the same using a single queue and provide some conditions that RabbitMQ server can check before sending messages to consumers.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
There is no way to do that with a single queue. Use N queues for N types, and channel prefetch for consumers on each queue to limit the concurrent processing rate.

**Comment by M22an** [comment]
Thanks for your response @michaelklishin. I will use the google groups list going forward.
