### ISSUE TITLE
Slow enqueue messages to rabbitmq

### ISSUE THREAD

**Issue by haosdent** [rabbitmq/rabbitmq-server#1245]
Hi, we encounter a wired problem on rabbitmq: publish messages to rabbitmq is super slow.

We have queue A and queue B in rabbitmq-server. And we use celery with rabbitmq. The status of queues are 

| Queue Name | Ready Messages | Unacked Messages |
|--------------|------------------|---------------------|
| Queue A | 2 | 482,063 | 	
| Queue B | 3 | 31 | 

We have 3 rabbitmq-servers, they are deployed in HA mode, all the queues are durable. And we deploy 9 consumers (celery workers) in 9 separate servers (didn't run consumers in the same server with rabbitmq-servers).

When we publish the messages to Queue A, it is super slow which take more than 10s seconds. Sometimes it even takes more than 1 minute. We use tcpdump to track the packets between client side (celery.send_task) and rabbitmq-server. The client side ((celery.send_task)) indeed stuck more than 10 seconds when waiting for response from rabbitmq-server.

But at the meantime, publish the messages to Queue B is fast. And if we stop all the consumers, publish messages to Queue A would become fast as well. But if you start all consumers (9 consumers), publish messages to Queue A would stuck again.

We suspect it is because of network problems at first, but network should be fine according to ping/mtr result. All of them are located in the same private subnet. And we try to login rabbitmq servers and publish messages on rabbitmq servers directly, it is very slow when enqueue message as well. CPU/Memory/Disk IO/Network are fine in rabbitmq-servers/producer/consumer.

Is it a known issue? Anything I could help to troubleshoot this problem?

Our rabbitmq-servers are

```
ii  rabbitmq-server                    3.6.9-1                                    all          Multi-protocol messaging broker
```

Erlang version is

```
# dpkg -l|grep erlang
ii  esl-erlang                         1:19.3                                     amd64        Erlang
```

OS is

```
Ubuntu 16.04 (Kernel 4.4.0-21-generic)
```

Looking forward your response, thank you in advance.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by dnoya** [comment]
> Hi, we encounter a wired problem on rabbitmq: publish messages to rabbitmq is super slow.
> 
> We have queue A and queue B in rabbitmq-server. And we use celery with rabbitmq. The status of queues are
> 
> Queue Name	Ready Messages	Unacked Messages
> Queue A	2	482,063
> Queue B	3	31
> We have 3 rabbitmq-servers, they are deployed in HA mode, all the queues are durable. And we deploy 9 consumers (celery workers) in 9 separate servers (didn't run consumers in the same server with rabbitmq-servers).
> 
> When we publish the messages to Queue A, it is super slow which take more than 10s seconds. Sometimes it even takes more than 1 minute. We use tcpdump to track the packets between client side (celery.send_task) and rabbitmq-server. The client side ((celery.send_task)) indeed stuck more than 10 seconds when waiting for response from rabbitmq-server.
> 
> But at the meantime, publish the messages to Queue B is fast. And if we stop all the consumers, publish messages to Queue A would become fast as well. But if you start all consumers (9 consumers), publish messages to Queue A would stuck again.
> 
> We suspect it is because of network problems at first, but network should be fine according to ping/mtr result. All of them are located in the same private subnet. And we try to login rabbitmq servers and publish messages on rabbitmq servers directly, it is very slow when enqueue message as well. CPU/Memory/Disk IO/Network are fine in rabbitmq-servers/producer/consumer.
> 
> Is it a known issue? Anything I could help to troubleshoot this problem?
> 
> Our rabbitmq-servers are
> 
> ```
> ii  rabbitmq-server                    3.6.9-1                                    all          Multi-protocol messaging broker
> ```
> 
> Erlang version is
> 
> ```
> # dpkg -l|grep erlang
> ii  esl-erlang                         1:19.3                                     amd64        Erlang
> ```
> 
> OS is
> 
> ```
> Ubuntu 16.04 (Kernel 4.4.0-21-generic)
> ```
> 
> Looking forward your response, thank you in advance.

Hi @haosdent how are you?
We are having the same exact issue you were describing here, where when we stop consumers, we can publish without issues.

Were you able to fix this ?

**Comment by lukebakken** [comment]
@dnoya if you'd like assistance, you should ask here:

https://groups.google.com/g/rabbitmq-users

...or here: https://github.com/rabbitmq/rabbitmq-server/discussions

You **MUST** include the information that @michaelklishin requested in this comment: https://github.com/rabbitmq/rabbitmq-server/issues/1245#issuecomment-305862301
