### ISSUE TITLE
RabbitMQ 4.0 (AMQP 1.0) Erlang Client 

### ISSUE THREAD

**Issue by ono** [rabbitmq/rabbitmq-server#12510]
### Is your feature request related to a problem? Please describe.

Congratulations to the team on RabbitMQ 4.0 Release 🎉 

I am a maintainer of the [Elixr RabbitMQ client](https://github.com/pma/amqp). I am wondering how I can help to introduce this version to the Elixir community.

- Are you planning to update [amqp_client](https://hex.pm/packages/amqp_client) for AMQP 1.0?
- Or will the client strategy be completely different, e.g., will it be a different client library with different APIs?
- Or would you recommend building the Elixir library independently from the Erlang library?
- Or do you plan to build an official Elixir library by yourself so a community version won't be needed?

Any suggestions, insights, views and advice are welcome. Thank you!

### Describe the solution you'd like

N/A

**Comment by michaelklishin** [comment]
Now that 4.0.x is moving closer to official Erlang 27 support (the known issues are on the Erlang/OTP side), there would be an important enough reason to fixing publishing to Hex.

**Comment by ansd** [comment]
Thank you @ono for maintaining the Elixir client.

> Are you planning to update [amqp_client](https://hex.pm/packages/amqp_client) for AMQP 1.0?

No, because:
* [amqp_client](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/amqp_client) is the AMQP 0.9.1 client
* [amqp10_client](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/amqp10_client) is an AMQP 1.0 client that can talk to any AMQP 1.0 broker
* [rabbitmq_amqp_client](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_amqp_client) wraps the `amqp10_client` with RabbitMQ specific features and is therefore an AMQP 1.0 client used specifically with RabbitMQ.

> Or will the client strategy be completely different, e.g., will it be a different client library with different APIs?

Yes, see answer above.

> Or would you recommend building the Elixir library independently from the Erlang library?

I think writing a new Elixir library which wraps [rabbitmq_amqp_client](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_amqp_client) and [amqp10_client](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/amqp10_client) makes most sense to me.

> Or do you plan to build an official Elixir library by yourself so a community version won't be needed?

Not at this point. We are currently developing clients for:
* Java
* .NET
* Go

**Comment by ono** [comment]
@ansd I see. That makes sense. Is there a plan to release rabbitmq_amqp_client and amqp10_client to Hex? Even RC version would be useful. Thanks!

**Comment by michaelklishin** [comment]
@ono we need to resume releases for `amqp_client` (the AMQP 0-9-1 we have up on Hex) first.

**Comment by michaelklishin** [comment]
[`4.0.3`](https://hex.pm/packages/amqp_client/4.0.3) (built on Erlang 26.x) is up on Hex.pm.

**Comment by ono** [comment]
Great news!

I have a few questions.

- amqp_client 4.0.3 is compatible for both RabbitMQ 3.x and 4.x
  - I thought RabbitMQ 4.x supports only AMQP 1.0 but that's just my misunderstanding and it still supports 0.9.1
  - Do you have any data 0.9.1 v.s. 1.0?
  - Is there any functionality RabbitMQ 4.0 supports only with AMQP 1.0?
- amqp10_client has been fully tested with RabbitMQ 4.0.3?
  - Asking because [README](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/amqp10_client) mention Shovel plugin

Thanks!

**Comment by michaelklishin** [comment]
@ono `amqp_client` 4.x will be able to connect and perform all key operations even to RabbitMQ 2.0 from 2009 or so.

`amqp10_common` is what AMQP 1.0 shovels use under the hood.

**Comment by ansd** [comment]
> I thought RabbitMQ 4.x supports only AMQP 1.0 but that's just my misunderstanding and it still supports 0.9.1

RabbitMQ 4.x supports both AMQP 1.0 and AMQP 0.9.1.

> Do you have any performance comparison data 0.9.1 v.s. 1.0?

Yes, see https://www.rabbitmq.com/blog/tags/amqp-1-0

> Is there any functionality RabbitMQ 4.0 supports only with AMQP 1.0?

Yes, see https://www.rabbitmq.com/blog/tags/amqp-1-0 and https://www.rabbitmq.com/docs/next/amqp#amqp-10-features

> amqp10_client has been fully tested with RabbitMQ 4.0.3?

This client has been tested against RabbitMQ 4.0.3.

**Comment by ono** [comment]
Fantastic. Thank you @michaelklishin and @ansd !!
