### ISSUE TITLE
erlnag.cookies in Active Directory

### ISSUE THREAD

**Issue by eocron** [rabbitmq/rabbitmq-server#1256]
Trying to install management plugin to version 3.6.10:

> rabbitmq-plugins enable rabbitmq_management

This leads me to error:

> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> Error: Failed to initialize erlang distribution: {{shutdown,
>                                                    {failed_to_start_child,
>                                                     auth,
>                                                     {"Failed to create cookie fi
> le 'z:/.erlang.cookie': eacces",
>                                                      [{auth,init_cookie,0,
>                                                        [{file,"auth.erl"},
>                                                         {line,286}]},
>                                                       {auth,init,1,
>                                                        [{file,"auth.erl"},
>                                                         {line,140}]},
>                                                       {gen_server,init_it,6,
>                                                        [{file,
>                                                          "gen_server.erl"},
>                                                         {line,328}]},
>                                                       {proc_lib,
>                                                        init_p_do_apply,3,
>                                                        [{file,"proc_lib.erl"},
>                                                         {line,247}]}]}}},
>                                                   {child,undefined,
>                                                    net_sup_dynamic,
>                                                    {erl_distribution,
>                                                     start_link,
>                                                     [['rabbitmq-cli-66',
>                                                       shortnames],
>                                                      false]},
>                                                    permanent,1000,supervisor,
>                                                    [erl_distribution]}}.
> 

Found out that my Z: drive is virtual and point to some \\example\share\home
Because HOMEDIR and HOMEPATH is set through ActiveDirectory I can't change it. And in some cases like copying files from it I get (Access denied).
Found answer about just cutting in half network cable - Im through RDP and this will just lead to disconnect.

Right now it seems like bug to me. I can't do anything, though if I start/stop/install service, I get:

> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> C:\Program Files\erl8.3\erts-8.3\bin\erlsrv: Service RabbitMQ stopped.

Im completely lost at how this cookies are used, nether do I care about it's existance, hot to deal with this error?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
[This rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/erlang$20cookie$20Windows$20Z$20drive%7Csort:relevance/rabbitmq-users/NOHN5d8D_AE/4kEkhoMq8cQJ) discusses more or less the same scenario.

**Comment by michaelklishin** [comment]
As to how the cookie is used, see [How Nodes and CLI Tools Authenticate to Each Other](http://www.rabbitmq.com/clustering.html).
