### ISSUE TITLE
RabbitMQ node won't rejoin the cluster upon docker container restart.

### ISSUE THREAD

**Issue by lnshi** [rabbitmq/rabbitmq-server#1271]
I have RabbitMQ cluster with three nodes(all in docker container): `rabbit@rabbitmq_server_0`, `rabbit@rabbitmq_server_1` and `rabbit@rabbitmq_server_2`, on both `1` and `2` I run `rabbitmqctl join_cluster rabbit@rabbitmq_server_0`, it works properly.

But when I tried to restart `rabbit@rabbitmq_server_2`, it restarted properly, and through the logs on `rabbit@rabbitmq_server_0` I see:

```
=INFO REPORT==== 21-Jun-2017::13:00:38 ===
rabbit on node rabbit@rabbitmq_server_2 down

=INFO REPORT==== 21-Jun-2017::13:00:38 ===
node rabbit@rabbitmq_server_2 down: connection_closed

=INFO REPORT==== 22-Jun-2017::00:31:04 ===
node rabbit@rabbitmq_server_2 up
```

and the `rabbitmqctl cluster_status` on `rabbit@rabbitmq_server_0` also showed three nodes properly,

but through the management UI I saw that: `rabbit@rabbitmq_server_2 Node not running`

and checked `rabbit@rabbitmq_server_2` by `rabbitmqctl cluster_status` also cannot see other nodes.

**That means upon container restart, the node won't rejoin the cluster properly.**

And on `rabbit@rabbitmq_server_2` when I tried to manually rejoin the cluster by using:

```
rabbitmqctl stop_app

rabbitmqctl join_cluster rabbit@rabbitmq_server_0
```

I got this error:

```
Error: {inconsistent_cluster,"Node rabbit@rabbitmq_server_0 thinks it's clustered with node rabbit@rabbitmq_server_2, but rabbit@rabbitmq_server_2 disagrees"}
```

Did I do anything wrong?

oh, and I use this image: [3.6.10-management-alpine](https://hub.docker.com/r/library/rabbitmq/tags/)

**Comment by lukebakken** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.
