### ISSUE TITLE
badarith error in rabbit_mirror_queue_mode_exactly module prevents node from starting

### ISSUE THREAD

**Issue by choyuri** [rabbitmq/rabbitmq-server#1273]
I was testing a 3-node cluster with pause_minority setting
in my partition testing, one node was partitioned from the rest of the cluster
queues have ha-param=2, ha-mode=exactly

when the partition is over node fails to restart due to following error
I was able to manually restart after removing ha policy on the queues

CRASH REPORT==== 19-Jun-2017::20:43:45 ===
  crasher:
    initial call: rabbit_prequeue:init/1
    pid: <0.14464.6>
    registered_name: []
    exception exit: {badarith,
                        [{rabbit_mirror_queue_mode_exactly,
                             suggested_queue_nodes,5,
                             [{file,
                                  "src/rabbit_mirror_queue_mode_exactly.erl"},
                              {line,39}]},
                         {rabbit_mirror_queue_misc,update_mirrors,1,
                             [{file,"src/rabbit_mirror_queue_misc.erl"},
                              {line,410}]},
                         {rabbit_amqqueue_process,update_ha_mode,1,
                             [{file,"src/rabbit_amqqueue_process.erl"},
                              {line,1465}]},
                         {rabbit_amqqueue_process,handle_cast,2,
                             [{file,"src/rabbit_amqqueue_process.erl"},
                              {line,1266}]},
                         {gen_server2,handle_msg,2,
                             [{file,"src/gen_server2.erl"},{line,1048}]},
                         {proc_lib,wake_up,3,
                             [{file,"proc_lib.erl"},{line,257}]}]}
      in function  gen_server2:terminate/3 (src/gen_server2.erl, line 1161)
    ancestors: [<0.14463.6>,rabbit_amqqueue_sup_sup,rabbit_sup,<0.10432.6>]
    messages: []
    links: [<0.14463.6>,<0.18465.6>,#Port<0.101930>]
    dictionary: [{process_name,
                      {rabbit_amqqueue_process,
                          {resource,<<"/">>,queue,
                              <<"in.chat.direct.9afbe290-293f-4a64-af8a-70a9ad6c3b81">>}}},
                  {{"/var/lib/rabbitmq/mnesia/rabbit@ip-10-0-11-134.us-west-2.compute.internal/queues/9USP8HUTZHDV25DJOKJLJ7JXW/journal.jif",
                    fhc_file},
                   {file,1,true}},
                  {fhc_age_tree,
                      {1,
                       {{-576458861882078463,#Ref<0.0.7.14580>},
                        true,nil,nil}}},
                  {guid,{{417043421,4290476972,3794328430,261293640},0}},
                  {rand_seed,
                      {#{max => 288230376151711743,
                         next => #Fun<rand.8.41921595>,type => exsplus,
                         uniform => #Fun<rand.9.41921595>,
                         uniform_n => #Fun<rand.10.41921595>},
:

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by choyuri** [comment]
apolgoies.. 
but this is a bug in the rabbit_mirror_queue_mode_exactly module that prevents rabbit node from restarting in certain conditions

the bug is in 
file,"src/rabbit_mirror_queue_mode_exactly.erl"}, {line,39}

is this ticket closed because it's not considered a bug?

thanks

**Comment by michaelklishin** [comment]
@choyuri this ticket is closed because we don't have enough information to work with.

> Our team is multiple orders of magnitude smaller than the RabbitMQ community.
> Please help others help you by providing a way to reproduce the behavior you're
> observing, or at least sharing as much relevant information as possible on the list
