### ISSUE TITLE
memory (binary) consumption without any load

### ISSUE THREAD

**Issue by ornoone** [rabbitmq/rabbitmq-server#1277]
hi, we run a rabbitmq-server in a docker (rabbitmq:3.6.10-management) on amazon aws. 

the rabbitmq server take more and more memory without any load. (0 msg/s, 9 connexion) 

![capture du 2017-06-29 17-39-23](https://user-images.githubusercontent.com/5380232/27696751-b92df0ea-5cf2-11e7-8ffd-a9711e6d1f91.png)

![capture du 2017-06-29 17-57-33](https://user-images.githubusercontent.com/5380232/27697448-9452b7cc-5cf4-11e7-8860-434229be3018.png)

our only load is a set of service which publish some message every 5 sec. the server will consume more memory, and after some day with this load, it will take ~488Mo.

the graphic shown is after a reboot, nothing appended but the restart of 2 services which was connected (out of 5). 

I don't understand how the «Memory details» show me 108 mb of binary, but the «Binary references» show a total of 104k. 

as i experiment it, it seem each service connected consume 24mo, is it possible that a service that fail to disconnect properly (docker kill) disallow to free his connection memory ?

setup : 
docker swarm with 3 nodes (2 micro and 1 nano)
the problem occur on the nano or micro.
the framework which connect to rabbitmq is nameko (python)

I well take more screen after some times to watch the evolution of this consumption.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
See rabbitmq-top as a source of additional information.

**Comment by michaelklishin** [comment]
If by "service" you mean a client (application), then connections from killed containers [won't be detected immediately](http://www.rabbitmq.com/heartbeats.html). Make sure your clients use a sensible heartbeat value.

Missed heartbeats, cleanly disconnected client connections, lost/abruptly closed TCP connections are logged by the server.

You can configure TCP keepalives as an additional measure and reduce TCP buffer size so that each connection uses less memory (at the cost of lower throughput). See [RabbitMQ Networking guide](http://www.rabbitmq.com/networking.html) for details.

Lastly, the 1st chart demonstrates total Erlang VM binary heap size. It can and does include things that are not — at least technically — part of RabbitMQ. The 2nd chart demonstrates how much
binary heap each group of RabbitMQ processes uses.

**Comment by ornoone** [comment]
thanks for your help. I will take time to inspect logs and closed connection warning, and will reopen with more data if I can't find out myself. (and with a reproduction steps)
