### ISSUE TITLE
High cluster slave memory usage during lazy queue sync

### ISSUE THREAD

**Issue by cuchac** [rabbitmq/rabbitmq-server#1279]
When syncing lazy queue with several millions of messages, memory consumption raises over 1.5GB. After sync, memory consumption is 150 MB.

We use lazy queues with ha-sync-mode=automatic and this problem results in blocked Rabbit once slave connects - sync get stuck because of memory alarm on slave and all publishing is blocked because of sync in progress.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Please post a way to reproduce to rabbitmq-users and we will investigate. There is a slight chance that this may be a yet another manifestation of https://github.com/rabbitmq/rabbitmq-common/issues/208 but we have very little information to tell.

Related issues were resolved in [3.5.2](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_5_2) and [3.6.1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_1).

As of 3.6.0 eager sync happens in batches of a configurable size. You can reduce it from 4096 (the default) to, say, 50 and see if that reduces peak RAM consumption. See Batch Synchronization in [mirroring docs](http://www.rabbitmq.com/ha.html).
