### ISSUE TITLE
In the process of a large number of messages being moved to the dead-letter queue due to TTL expiration, the RabbitMQ cluster crashed, resulting in the loss of some messages.

### ISSUE THREAD

**Issue by usernameisnull** [rabbitmq/rabbitmq-server#12856]
### Describe the bug

In the process of a large number of messages being moved to the dead-letter queue due to TTL expiration, the RabbitMQ cluster crashed, resulting in the loss of some messages.

### Reproduction steps

1. 2 queue vs 1 dead letter queue
2. each queue has 100000 messages
3. each message is durable and set random ttl, and 2 queues are durable  
![图片](https://github.com/user-attachments/assets/196e3567-6d21-444e-b04a-15eff66b90d6)
5. When you see the message that it has been transferred to DLQ due to TTL, **restart the entire cluster**
![图片](https://github.com/user-attachments/assets/b304ff1b-48b8-4bf8-8b1e-1ad648d2b94c)
6. When the cluster returns to normal, you can see that some messages are lost.
![图片](https://github.com/user-attachments/assets/b6286690-169d-40c1-9995-0d8cdc5cbcf0)
7. No consumers are involved in the whole process

### Expected behavior

Hope the message wasn't lost

### Additional context

rabbitmq version: 3.9.25
environ: kubernets
3 replicas

**Comment by mkuratczyk** [comment]
RabbitMQ 3.9 has been out of support for many years. Try to reproduce this with RabbitMQ 4.0 (and therefore classic queues v2, since only v2 is available in 4.0).

There's a pretty good chance things will work better just by upgrading. However, there's indeed no credit flow mechanism when dead lettering between classic queues. You can switch to quorum queues (even in a single-node environment potentially), since quorum queues do have more reliable dead-lettering in newer versions.
https://www.rabbitmq.com/blog/2022/03/29/at-least-once-dead-lettering

We are not going to investigate issues for such old versions.
