### ISSUE TITLE
Got response code 500 when i'm trying to login into WebLogin

### ISSUE THREAD

**Issue by Allan-Nava** [rabbitmq/rabbitmq-server#1289]
`Got response code 500 with body {"error":"Internal Server Error","reason":"{error,badarg,\n [{ets,lookup,[rabbit_user,<<\"admin\">>],[]},\n {rabbit_misc,dirty_read,1,[{file,\"src/rabbit_misc.erl\"},{line,386}]},\n {rabbit_auth_backend_internal,internal_check_user_login,2,\n [{file,\"src/rabbit_auth_backend_internal.erl\"},{line,121}]},\n {rabbit_access_control,try_authenticate,3,\n [{file,\"src/rabbit_access_control.erl\"},{line,88}]},\n {rabbit_access_control,'-check_user_login/2-fun-0-',4,\n [{file,\"src/rabbit_access_control.erl\"},{line,74}]},\n {lists,foldl,3,[{file,\"lists.erl\"},{line,1248}]},\n {rabbit_mgmt_util,is_authorized,6,\n [{file,\"src/rabbit_mgmt_util.erl\"},{line,134}]},\n {webmachine_resource,resource_call,3,\n [{file,\"src/webmachine_resource.erl\"},{line,186}]}]}\n"}`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
A table with users does not exist. RabbitMQ never deletes it, so we typically see scenarios like this when a node runs out of file descriptors during boot (e.g. after a restart).

See [Networking](http://www.rabbitmq.com/networking.html) and [Production Checklist](http://www.rabbitmq.com/production-checklist.html).
