### ISSUE TITLE
docker hub alpine images cannot be pulled

### ISSUE THREAD

**Issue by cocoonkid** [rabbitmq/rabbitmq-server#12942]
### Describe the bug

docker hub alpine images cannot be pulled

 ╰─λ docker pull rabbitmq:management-alpine

management-alpine: Pulling from library/rabbitmq
manifest for rabbitmq:management-alpine not found: manifest unknown: manifest unknown

### Reproduction steps

1. try pulling
2.
3.
...

### Expected behavior

able to pull

### Additional context

I tried from multiple machines. the normal images work.

**Comment by mkuratczyk** [comment]
We don't maintain those images, they are maintained by the Docker folks: https://github.com/docker-library/rabbitmq
Side note: we never use/test the alpine version of those image as far as I know. I guess they work well, otherwise we would have heard about that, but the ubuntu versions are definitely more popular and we use them reguarly.

**Comment by michaelklishin** [comment]
https://github.com/docker-library/rabbitmq/issues/747

**Comment by michaelklishin** [comment]
The Alpine version of the image had an [OS update](https://github.com/docker-library/rabbitmq/commit/0584c9d30e14c060a7fb677c5134f03da0d6a68d) two days ago and an Ubuntu version of 3.13 specifically then was upgraded to Ubuntu 24.04 https://github.com/docker-library/rabbitmq/pull/746 because they were affected by a regression in one of their dependencies on 22.04.

**Comment by michaelklishin** [comment]
We have an update from a Docker, Inc team.

The issue is not entirely specific to this image. Please see [1][2].

There is an ongoing technical operations call, so the issue is not being ignored, quite the contrary.

1. https://www.dockerstatus.com/
2. https://github.com/docker-library/docker/issues/519

**Comment by michaelklishin** [comment]
``` shell
docker pull rabbitmq:3
```

``` shell
docker pull rabbitmq:3.13.7
```

both work for me now.
