### ISSUE TITLE
Dead-letter undelivered messages in transient queues

### ISSUE THREAD

**Issue by smurfix** [rabbitmq/rabbitmq-server#1299]
My problem: I'm trying to implement a reliable RPC system that uses one queue per server, instead of per message type. (I have too many of those.)

Thus I use a common "rpc" exchange; the server creates a transient "rpc_RANDOM_UUID" queue and routes the messages it's interested in to that queue.

The problem: if/when the server dies, undelivered messages in that queue get lost.

I propose to extend the per-queue dead-lettering system so that untransmitted and unacked messages get requeued to the designated dead-letter queue when that happens.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
I't not clear whether "the server" here means a request/reply server or something else. Unroutable messages can be returned to the publisher (set the mandatory property to true when publishing). Unacknowledged messages are requeued to the same queue. [TTL can be used to dead letter them eventually](http://rabbitmq.com/ttl.html).

**Comment by smurfix** [comment]
To repeat,

* the message is delivered to a queue w/ auto-delete
* the AMQP client reads the message, then immediately dies.
* the queue thus gets auto-deleted.
* the message is lost.

I don't like lost messages.
I'd like the message to be dead-lettered (either by default, or optionally).

**Comment by michaelklishin** [comment]
@smurfix then perhaps you should not use auto-delete or exclusive queues and rely on TTL instead. This is not a discussion venue, sorry.
