### ISSUE TITLE
ENV variable should be defined: RABBITMQ_IO_THREAD_POOL_SIZE.

### ISSUE THREAD

**Issue by liaodalin19903** [rabbitmq/rabbitmq-server#1327]
I installed the `erlang-18.3.4.4-2.el7.x86_64` and `rabbitmq-server-3.6.5-1.el7.noarch` in my host machine(CentOS Linux release 7.2.1511 (Core) ), but can not start it.

```
 [root@ha-node3 system]# systemctl restart rabbitmq-server.service 
Job for rabbitmq-server.service failed because the control process exited with error code. See "systemctl status rabbitmq-server.service" and "journalctl -xe" for details.
[root@ha-node3 system]# journalctl -xe -l 
8月 10 13:31:39 ha-node3 sshd[4794]: Received disconnect from 116.31.116.41: 11:  [preauth]
8月 10 13:31:39 ha-node3 sshd[4794]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=116.31.116.41  user=root
8月 10 13:32:52 ha-node3 polkitd[1694]: Registered Authentication Agent for unix-process:4831:296349 (system bus name :1.22 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path 
8月 10 13:32:52 ha-node3 systemd[1]: Cannot add dependency job for unit epmd@0.0.0.0.socket, ignoring: Unit epmd@0.0.0.0.socket is masked.
8月 10 13:32:52 ha-node3 systemd[1]: Starting RabbitMQ broker...
-- Subject: Unit rabbitmq-server.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rabbitmq-server.service has begun starting up.
8月 10 13:32:52 ha-node3 rabbitmq-server[4836]: Error: ENV variable should be defined: RABBITMQ_IO_THREAD_POOL_SIZE.
8月 10 13:32:52 ha-node3 rabbitmq-server[4836]: Please check rabbitmq-env, rabbitmq-defaults, and /etc/rabbitmq/rabbitmq-env.conf script files
8月 10 13:32:52 ha-node3 systemd[1]: rabbitmq-server.service: main process exited, code=exited, status=78/n/a
8月 10 13:32:52 ha-node3 rabbitmqctl[4916]: /usr/lib/rabbitmq/bin/rabbitmqctl:行30: /usr/bin/erl: 成功
8月 10 13:32:52 ha-node3 systemd[1]: rabbitmq-server.service: control process exited, code=exited status=1
8月 10 13:32:52 ha-node3 systemd[1]: Failed to start RabbitMQ broker.
-- Subject: Unit rabbitmq-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rabbitmq-server.service has failed.
-- 
-- The result is failed.
8月 10 13:32:52 ha-node3 systemd[1]: Unit rabbitmq-server.service entered failed state.
8月 10 13:32:52 ha-node3 systemd[1]: rabbitmq-server.service failed.
8月 10 13:32:52 ha-node3 polkitd[1694]: Unregistered Authentication Agent for unix-process:4831:296349 (system bus name :1.22, object path /org/freedesktop/PolicyKit1/AuthenticationAge
8月 10 13:32:54 ha-node3 sshd[4989]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=116.31.116.41  user=root
8月 10 13:32:54 ha-node3 sshd[4989]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
8月 10 13:32:56 ha-node3 sshd[4989]: Failed password for root from 116.31.116.41 port 29372 ssh2
8月 10 13:32:56 ha-node3 sshd[4989]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"

```

And in the `/var/log/message`:

```
Aug 10 13:16:59 ha-node3 systemd: Starting RabbitMQ broker...
Aug 10 13:17:00 ha-node3 rabbitmq-server: Error: ENV variable should be defined: RABBITMQ_IO_THREAD_POOL_SIZE.
Aug 10 13:17:00 ha-node3 rabbitmq-server: Please check rabbitmq-env, rabbitmq-defaults, and /etc/rabbitmq/rabbitmq-env.conf script files
Aug 10 13:17:00 ha-node3 systemd: rabbitmq-server.service: main process exited, code=exited, status=78/n/a
Aug 10 13:17:00 ha-node3 rabbitmqctl: /usr/lib/rabbitmq/bin/rabbitmqctl:行30: /usr/bin/erl: 成功
Aug 10 13:17:00 ha-node3 systemd: rabbitmq-server.service: control process exited, code=exited status=1
Aug 10 13:17:00 ha-node3 systemd: Failed to start RabbitMQ broker.
Aug 10 13:17:00 ha-node3 systemd: Unit rabbitmq-server.service entered failed state.
Aug 10 13:17:00 ha-node3 systemd: rabbitmq-server.service failed.
Aug 10 13:17:38 ha-node3 systemd: Configuration file /usr/lib/systemd/system/wpa_supplicant.service is marked executable. Please remove executable permission bits. Proceeding anyway.

```

**Comment by michaelklishin** [comment]
[It is defined](https://github.com/rabbitmq/rabbitmq-server/blob/stable/scripts/rabbitmq-server#L142). Please use 3.6.10, the most recent release.

**Comment by liaodalin19903** [comment]
@michaelklishin  But, however, in my other centos 7.2 host machine all they all works perfect with `rabbitmq-server-3.6.5-1.el7.noarch `

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/cQ-ffDdrfX0).
