### ISSUE TITLE
Priority ignored by the Dead Letter Exchange queue

### ISSUE THREAD

**Issue by Noxalus** [rabbitmq/rabbitmq-server#1328]
Hello everyone.

I'm struggling with this problem, and for me it doesn't work as expected.

Here is my problem, I have 2 queues:

- `incoming_message` => where I push all messages that I want to process later
- `incoming_message_dlx` => where I push the message whose the processing failed

As you can supposed with its name, the `incoming_message_dlx` queue use the [Dead Letter Exchange](https://www.rabbitmq.com/dlx.html) feature, that means when the message expires, it will be requeue to my `incoming_message`.

What I try to achieve is to increase the `expiration` of messages each time the processing failed and that they are push to the DLX queue.

The problem is that even if a message expired, it will not be requeue to my `incoming_message` while it's not at the bottom (head) of the queue. So if there is a message with an expiration time of 7 days in the DLX queue and that we enqueue a new message with the expiration time of 5 seconds, this message will only be requeue to the `incoming_message` after 7 days + 5 seconds...

I've found on the documentation that I can use my DLX queue as a [priority queue](https://www.rabbitmq.com/priority.html) and put a priority on my messages according to the expiration time, but it doesn't work as expected, the priority seems to be ignored.

However, when I use the RabbitMQ admin (management plugin) and that I get the first message of the queue, it's always the one with the higher priority, but the "internal consumer" of the DLX queue seems to ignore this priority.

Am I doing something wrong?

*PS: I'm using RabbitMQ server version 3.6.10.*

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/cgzxHvteBo8)
