### ISSUE TITLE
Consider adding separate headers for original dead-lettering event ("x-death")

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1332]
Currently as messages are dead-lettered, the context is kept in a collection of events known as `x-deaths`. Headers exchange cannot match collections and therefore cannot be used with `x-deaths`.

Some would like to have original dead lettering to be a top-level set of headers as well, e.g. `x-original-death-reason`, `x-original-death-queue` and so on. This way such messages can be routed using a headers exchange.

**Comment by sylvainhubsch** [comment]
Hi Michael,
I have already wrote that feature some day; so would you consider to assign me this issue ?

**Comment by michaelklishin** [comment]
@sylvainhubsch we are already looking into it.

**Comment by michaelklishin** [comment]
@sylvainhubsch thank you for offering your help, by the way! We'd be happy to receive your feedback on a PR once it is up for QA.

**Comment by michaelklishin** [comment]
@sylvainhubsch if you're still interested in reviewing our proposed implementation for it, take a look at the PRs above :) Thank you!

**Comment by sylvainhubsch** [comment]
@michaelklishin Thank you Michael.
From what I have understood, those new headers are only set the first time, as keys names imply ? If this is the case, that would imply to treat such message the first time it has been dead. Would you consider valuable to track at the first level too, the count for each reasons ? I used to run such Rabbit versions at work (without exchange and queue info), which permits to write something like << if message has been killed 20 times because of rejected, then.... >>; that way, Rabbit has the ability to "detect" infinite loop of messages not consumed.
And by the way, from what I see, all headers beginnig with "x-" can't be matched at all (historically); for that, what I've done is to create a new operator "x-?eq K" where K CAN begin with anything (specially x-). But this is another subject :)

**Comment by sylvainhubsch** [comment]
PS : I just wanted to share what I did : https://github.com/sylvainhubsch/rabbitmq-server/commit/72d54225c33c58fd422ef04f782338c463a59ab4
(from my point of view, like discussed is #78, the "cycle detection problem" should be only based on loop counters given by death reasons; what could be improved, is to add the LAST (instead of the first/original) queue/exchange ! So that if we want to handle the "first" death, it is tantamount to what you propose...)
(I hope my english is good enough to be understood :/ )

**Comment by michaelklishin** [comment]
We are not trying to handle cycle detection here. The goal is to make it possible to route on the original dead lettering event attributes (using the headers exchange).
