### ISSUE TITLE
Server hangs starting up at searching for neighbors

### ISSUE THREAD

**Issue by mlapaglia** [rabbitmq/rabbitmq-server#1337]
A more verbose message should be sent when the server has less than 1GB available for the server to use. Currently starting a process hangs at "searching for neighbors" when the disk has less than 1GB left. No errors show up in the logs either.

https://stackoverflow.com/questions/25183290/celery-stuck-at-mingle-searching-for-neighbors-doesnt-get-to-ready-state

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Syncing data from peers is not directly related to how much disk space is available. Default [free disk space alarm threshold](http://www.rabbitmq.com/disk-alarms.html) is configurable and is 50 MB by default.

When a node detects it may need more file descriptors that the OS limit on start, it logs a warning.
See [Production checklist](http://www.rabbitmq.com/production-checklist.html) for recommended values (the default is an kernel setting, NOT a RabbitMQ one, unfortunately).

**Comment by michaelklishin** [comment]
Also, attempts to reach a peer to sync metadata tables from are logged as of at least 3.6.7, and so are retries, if any.
