### ISSUE TITLE
Lots of errors "Reason:     reached_max_restart_intensity"

### ISSUE THREAD

**Issue by xtender** [rabbitmq/rabbitmq-server#1342]
Hello,

We got lots of errors(rabbit@localhost-sasl.log was about 25GB) like this one:
```
=SUPERVISOR REPORT==== 25-Aug-2017::12:20:26 ===
     Supervisor: {<0.21360.5396>,rabbit_stomp_client_sup}
     Context:    child_terminated
     Reason:     {noproc,
                     {gen_event,call,
                         [rabbit_alarm,rabbit_alarm,
                          {register,<0.16487.5396>,
                              {rabbit_stomp_reader,conserve_resources,[]}},
                          infinity]}}
     Offender:   [{pid,<0.16487.5396>},
                  {name,rabbit_stomp_reader},
                  {mfargs,
                      {rabbit_stomp_reader,start_link,
                          [<0.350.5396>,
                           {acceptor,{0,0,0,0,0,0,0,0},61613},
                           #Port<0.195526545>,
                           {stomp_configuration,<<"guest">>,<<"guest">>,
                               false,false,false}]}},
                  {restart_type,intrinsic},
                  {shutdown,30000},
                  {child_type,worker}]


=SUPERVISOR REPORT==== 25-Aug-2017::12:20:26 ===
     Supervisor: {<0.21360.5396>,rabbit_stomp_client_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.16487.5396>},
                  {name,rabbit_stomp_reader},
                  {mfargs,
                      {rabbit_stomp_reader,start_link,
                          [<0.350.5396>,
                           {acceptor,{0,0,0,0,0,0,0,0},61613},
                           #Port<0.195526545>,
                           {stomp_configuration,<<"guest">>,<<"guest">>,
                               false,false,false}]}},
                  {restart_type,intrinsic},
                  {shutdown,30000},
                  {child_type,worker}]
```
What does that mean?

**Comment by xtender** [comment]
And also lots of errors like this one:

> =SUPERVISOR REPORT==== 25-Aug-2017::12:26:43 ===
>      Supervisor: {<0.11544.11>,amqp_channel_sup_sup}
>      Context:    shutdown_error
>      Reason:     shutdown
>      Offender:   [{nb_children,1},
>                   {name,channel_sup},
>                   {mfargs,
>                       {amqp_channel_sup,start_link,
>                           [direct,<0.11530.11>,
>                            <<"10.101.28.127:57984 -> 10.103.183.50:61613">>]}},
>                   {restart_type,temporary},
>                   {shutdown,brutal_kill},
>                   {child_type,supervisor}]
>

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
You have lots of messages because you had a lot of STOMP connections when your node hit an alarm and a process that is mean to handle alarms wasn't around. There can be clues as to why it had to terminate (or failed to start, although that should prevent node from starting) earlier in the log.
We have no logs and not even RabbitMQ version to look into if this may be something known => mailing list material.

**Comment by michaelklishin** [comment]
Forced channel shutdown reports (the `amqp_channel_sup_sup` ones) are not related and are almost certainly harmless.
