### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by ox123** [rabbitmq/rabbitmq-server#1344]
I am new to erlang and rabbitmq , When I compile the source of rabbitmq-server-3.6.1, I have encountered the following questions, I am appreciate anyone who can help me!!!
src/gm.erl:446: syntax error before: '/'
src/gm.erl:447: syntax error before: '/'
src/gm.erl:449: syntax error before: '/'
src/gm.erl:450: syntax error before: '/'
src/gm.erl:451: syntax error before: '/'
src/gm.erl:452: syntax error before: '/'
src/gm.erl:453: syntax error before: '/'
src/gm.erl:454: syntax error before: '/'
src/gm.erl:444: type txn_fun() is unused
src/gm.erl:554: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
src/gm.erl:1089: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
make[1]: *** [ebin/rabbit.app] Error 1
make: *** [app] Error 2
[2]-  Exit 2                  make

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Please start a rabbitmq-users thread and provide

 * A shell transcript of the steps you are taking
 * The Erlang/OTP version used

There were breaking changes in the type spec syntax between R16 and 18.0, and `gm.erl:446` in 3.6.1 [is a type spec definition](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq_v3_6_1/src/gm.erl#L446).

3.6.1 binary packages are also [available](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_1).

**Comment by michaelklishin** [comment]
The most recent version supported in the 3.6.1 days [was 18.x](http://www.rabbitmq.com/changelog.html).
