### ISSUE TITLE
no exchange 'null:null' in vhost '/' exception

### ISSUE THREAD

**Issue by baot** [rabbitmq/rabbitmq-server#1345]
Hi,

I receive the exception: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'null:null' in vhost '/', class-id=60, method-id=40)
when publish contract from rabbit java client with a valid exchange(means not null:null). Any suggestions for this? 

Issue on rabbit amqp java client version: 3.5.6, rabbitmq server version: 3.6.1
Thanks

**Comment by lukebakken** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.

At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thanks,
Luke
