### ISSUE TITLE
Support windows nanoserver

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-server#1349]
Please support windows nanoserver

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
@AceHack if you are asking for something to be supported, consider providing more than one line of information and explain *why* it is necessary in your opinion. Open source software maintainers are not always great at mind reading (or familiar with every single tool out there). It would really increase the likelihood of your issue being addressed, or even considered as a valid issue (see above).

**Comment by AceHack** [comment]
So I was able to get erlang and rabbitmq working on the latest preview of windows nanoserver insider edition. It's a bit kludgy but it's working!!!
I guess microsoft added whatever was missing in the latest edition to make things work.
Hope this image can help someone else.
You can type "build-image.cmd" to create the docker image
"run-containers.cmd" will startup two instance of rabbit one with host name "rabbitmq" and one with host name "joinmq"
One interesting thing here is the .erlang.cookie file. I had to do some playing to get the two rabbits to have the same .erlang.cookie file but not embed it in the image so it could be replaced at runtime.
"log-containers.cmd" will show you once the rabbit images have started fully.
"join-cluster.cmd" will join the two instances into a cluster.

It would be great to see an officially support windows docker container from rabbit

[rabbitmq-nanoserver-insider.zip](https://github.com/rabbitmq/rabbitmq-server/files/1286535/rabbitmq-nanoserver-insider.zip)
