### ISSUE TITLE
Please support official docker compose

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-server#1354]
It's currently left to the reader to figure out how to take RabbitMQ docker image and run it in a cluster and scale up and down.  Please create a recommended docker compose file that has best practices for clustering and scaling.  If this included also sharding that would be amazing.

**Comment by Gsantomaggio** [comment]
hi @AceHack 

There is this example here: https://github.com/rabbitmq/rabbitmq-autocluster/tree/master/examples/compose_consul_haproxy 

And also there are examples here: https://github.com/Gsantomaggio/rabbitmqexample/tree/master/cluster_docker_compose

About the second one, soon we will move the examples in the official repository.

**Comment by michaelklishin** [comment]
Thanks to @Gsantomaggio there are [several examples](https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable/examples) for Docker compose:

 * etcd
 * etcd + HAproxy
 * Consul + HAproxy

Plus a couple for Kubernetes.

They all use rabbitmq-autocluster because for "scaling up and down" to work, newly added nodes need to be able to discover their peers and that's the recommended way of doing it (and something that will ship in 3.7 as a [built-in feature with an extensible interface](http://next.rabbitmq.com/cluster-formation.html)).

I'd like to point out that scaling a realistic system usually involves understanding the workload, its limiting factors and how the apps (primarily consumers) scale as well, not just bumping a number. For example, if HAproxy is used, how do you scale it when publishers max out its network link? Are your apps prepared to use more than one connection endpoint? And so on.
I wish this part could be wrapped in a container.

**Comment by AceHack** [comment]
Thanks so much this is very helpful
