### ISSUE TITLE
Auto-delete/HA queues got stuck during upgrade

### ISSUE THREAD

**Issue by gilbsgilbs** [rabbitmq/rabbitmq-server#1360]
Hi,

During the upgrade from RabbitMQ 3.6.10 to 3.6.11 and from 3.6.11 to 3.6.12, some auto-delete HA queues got stuck.

Here is what showed Management API : 
![image](https://user-images.githubusercontent.com/3407667/30383280-aed31450-98a1-11e7-9de5-8790241dac9f.png)

These queues were invisible to `rabbitmqctl`, but it wasn't possible to create new queues with the same name.
```
Channel error on connection <0.23102.1> (x.x.x.x:19988 -> x.x.x.x:5672, vhost: 'foo', user: 'me'), channel 1:
operation queue.declare caused a channel exception not_found: failed to perform operation on queue 'queue_name' in vhost 'foo' due to timeout
```

It wasn't possible to delete the queue from management API either. I was able to delete the queue using this command (as stated [here](https://groups.google.com/forum/#!topic/rabbitmq-users/dgjikJDu_ZM)):
```
sudo rabbitmqctl eval 'Q = {resource, <<"foo">>, queue, <<"queue_name">>}, rabbit_amqqueue:internal_delete(Q).'
```

Here is the _maybe_stuck_ diagnostic from one of the two nodes (the other node is fine):
```
$ sudo rabbitmqctl eval "rabbit_diagnostics:maybe_stuck()."
2017-09-13 14:16:19 There are 1618 processes.
2017-09-13 14:16:19 Investigated 1 processes this round, 5000ms to go.
2017-09-13 14:16:20 Investigated 1 processes this round, 4500ms to go.
2017-09-13 14:16:20 Investigated 1 processes this round, 4000ms to go.
2017-09-13 14:16:21 Investigated 1 processes this round, 3500ms to go.
2017-09-13 14:16:21 Investigated 1 processes this round, 3000ms to go.
2017-09-13 14:16:22 Investigated 1 processes this round, 2500ms to go.
2017-09-13 14:16:22 Investigated 1 processes this round, 2000ms to go.
2017-09-13 14:16:23 Investigated 1 processes this round, 1500ms to go.
2017-09-13 14:16:23 Investigated 1 processes this round, 1000ms to go.
2017-09-13 14:16:24 Investigated 1 processes this round, 500ms to go.
2017-09-13 14:16:25 Found 1 suspicious processes.
2017-09-13 14:16:25 [{pid,<10217.26135.0>},
                     {registered_name,[]},
                     {current_stacktrace,
                         [{rabbit_mgmt_wm_exchange_publish,'-do_it/2-fun-0-',
                              8,
                              [{file,
                                   "src/rabbit_mgmt_wm_exchange_publish.erl"},
                               {line,76}]},
                          {rabbit_mgmt_util,with_channel,5,
                              [{file,"src/rabbit_mgmt_util.erl"},{line,782}]},
                          {rabbit_mgmt_util,with_decode,5,
                              [{file,"src/rabbit_mgmt_util.erl"},{line,662}]},
                          {rabbit_mgmt_wm_exchange_publish,accept_content,2,
                              [{file,
                                   "src/rabbit_mgmt_wm_exchange_publish.erl"},
                               {line,53}]},
                          {cowboy_rest,call,3,
                              [{file,"src/cowboy_rest.erl"},{line,976}]},
                          {cowboy_rest,process_content_type,3,
                              [{file,"src/cowboy_rest.erl"},{line,777}]},
                          {cowboy_protocol,execute,4,
                              [{file,"src/cowboy_protocol.erl"},{line,442}]}]},
                     {initial_call,{cowboy_protocol,init,4}},
                     {message_queue_len,0},
                     {links,[#Port<10217.49848>,<10217.2428.0>]},
                     {monitors,[{process,<10217.26159.0>}]},
                     {monitored_by,[<10217.26159.0>,<10217.26159.0>]},
                     {heap_size,75113}]
ok
```
(my node is still in this state and I don't know what to do with this)

Here is the HA policy that was in use:
```
{
"ha-mode": "all",
"ha-sync-mode": "automatic"
}
```

If you need further details, let me know. I still have staled queues against which I can run diagnostics.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
See server logs for unhandled exceptions.

**Comment by gilbsgilbs** [comment]
@michaelklishin Sorry for the noise 😕 . Let's continue [there](https://groups.google.com/forum/#!topic/rabbitmq-users/5hP0DkH_txA).

Nothing special in the server logs.
