### ISSUE TITLE
Disk util 100% using small load on RabbitMQ 

### ISSUE THREAD

**Issue by deslum** [rabbitmq/rabbitmq-server#1370]
Hello!

With a small load on the rabbitmq **iostat -x 3** showing util% >90%. I'm using a single node. 

System Ubuntu 16.04
Disk SATA

**rabbitmqctl status**

```
Status of node rabbit@test ...
[{pid,4073},
 {running_applications,
     [{rabbitmq_shovel_management,"Shovel Status","3.6.6"},
      {rabbitmq_management,"RabbitMQ Management Console","3.6.6"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.6"},
      {rabbitmq_shovel,"Data Shovel for RabbitMQ","3.6.6"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.6"},
      {rabbit,"RabbitMQ","3.6.6"},
      {os_mon,"CPO  CXC 138 46","2.4"},
      {webmachine,"webmachine","1.10.3"},
      {mochiweb,"MochiMedia Web Server","2.13.1"},
      {compiler,"ERTS  CXC 138 10","6.0.3"},
      {syntax_tools,"Syntax tools","1.7"},
      {ssl,"Erlang/OTP SSL application","7.3"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.6"},
      {rabbit_common,[],"3.6.6"},
      {xmerl,"XML parser","1.3.10"},
      {public_key,"Public key infrastructure","1.1.1"},
      {crypto,"CRYPTO","3.6.3"},
      {inets,"INETS  CXC 138 49","6.2"},
      {asn1,"The Erlang ASN1 compiler version 4.0.2","4.0.2"},
      {mnesia,"MNESIA  CXC 138 12","4.13.3"},
      {sasl,"SASL  CXC 138 11","2.7"},
      {stdlib,"ERTS  CXC 138 10","2.8"},
      {kernel,"ERTS  CXC 138 10","4.2"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:12:12] [async-threads:192] [kernel-poll:true]\n"},
 {memory,
     [{total,248857168},
      {connection_readers,2912352},
      {connection_writers,324912},
      {connection_channels,3783200},
      {connection_other,2821232},
      {queue_procs,33058840},
      {queue_slave_procs,0},
      {plugins,24563552},
      {other_proc,0},
      {mnesia,5297352},
      {mgmt_db,45723776},
      {msg_index,3770488},
      {other_ets,5471136},
      {binary,70140128},
      {code,27841629},
      {atom,1000601},
      {other_system,23569850}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"127.0.0.1"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,53953767014},
 {disk_free_limit,50000000},
 {disk_free,1868749840384},
 {file_descriptors,
     [{total_limit,119900},
      {total_used,105},
      {sockets_limit,107908},
      {sockets_used,100}]},
 {processes,[{limit,1048576},{used,4935}]},
 {run_queue,0},
 {uptime,1255},
 {kernel,{net_ticktime,60}}]
```

**iostat** 

<a href="https://ibb.co/nDqsw5"><img src="https://thumb.ibb.co/nDqsw5/1505867017108.jpg" alt="1505867017108" border="0"></a>

**iotop**

<a href="https://ibb.co/gfZo3k"><img src="https://thumb.ibb.co/gfZo3k/1505868038206.jpg" alt="1505868038206" border="0"></a>

**RabbitMQ Stat**

<a href="https://ibb.co/j8t99Q"><img src="https://thumb.ibb.co/j8t99Q/1505867056801.jpg" alt="1505867056801" border="0"></a>

How to reduce the load on the disk?

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
If you are confident that consumers will be able to keep up, you can choose to publish messages as transient (they can still be moved to disk but it will happen less frequently). I'd think twice before doing so because consumers do slow down or fail from time to time, resulting in a very quick message backlog build-up.

A much safer and likely more effective option would be to make your publishers compress message  payloads.

5 MB/s is not a particularly high rate, so provisioning a faster disk should be an option as well.

**Comment by michaelklishin** [comment]
Also note that the rate alone is not relevant. Disk I/O rate with be roughly message write rate * average message size. One operation per second with a 6 MB payload would produce a disk write rate comparable to what `top` reports.

**Comment by deslum** [comment]
Thank you. Asked a question here https://groups.google.com/forum/#!topic/rabbitmq-users/ti6mIBmZMuE
