### ISSUE TITLE
newly added cluster node cannot recieve new messages on mirrored queue

### ISSUE THREAD

**Issue by oscchun** [rabbitmq/rabbitmq-server#1373]
Hi, 
I'm using RMQ v3.6.6, 
setup cluster and mirrored policies with two nodes (ha-mode = all, not sync auto, sync batch size = 1) 
but one node is down. (with cli : rabbitmqctl stop_app)
then I declare mirrored queue on up-node and publish messages to queue.

while publishing messages, I awake up down-node with cli (rabbitmqctl start_app).

With management web console, showing like mirrored.

I expect that thogh I down one node (at first up-node), newly added node has messages after added. But the mirrored queue go wrong and the number of messages showing NaN.

Is it correct workflow?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
See [Stopping nodes and synchronization](http://www.rabbitmq.com/ha.html). Queue master promotion events are visibly logged. Please upgrade to 3.6.12 and describe the exact steps that can be used to reproduce your test on the mailing list.

**Comment by michaelklishin** [comment]
And please provide full server logs as well.
