### ISSUE TITLE
rotate_logs uses windows short file names and thus cannot be monitored

### ISSUE THREAD

**Issue by andymartin** [rabbitmq/rabbitmq-server#1395]
When I use rabbitmqctl rotate_logs on Windows it rotates into short filenames:
```
RABBIT~2.LOG.2017.10.15
RABBIT~1.LOG.2017.10.15
```
This is incorrect. As documented and as expected by the operating system, filenames should be:
```
rabbit@MARRISPRDFAB202.log.2017.10.15
rabbit@MARRISPRDFAB202-sasl.log.2017.10.15
```
This incorrect rotation makes log monitoring impossible as each log cannot be positively identified.

This is filed as an issue because it is incorrect behavior as specified by the documentation and as expected by the operating system:
> The RabbitMQ broker appends the contents of its log files to files _with names composed of the original name and the suffix_

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Windows is a special case. Other operating systems don't use short filenames. Windows uses it because of https://github.com/rabbitmq/rabbitmq-server/issues/493, which is a more problematic issue than this one. If someone is aware of a way to avoid both issues, let us know on rabbitmq-users.

**Comment by michaelklishin** [comment]
As #493 points out, the root of the problem is that paths are passed through batch files. Even with really skinny batch files we have in mind for the future, we currently are not aware of a way to completely avoid the issue and short filenames have been working quite well for close to two years now.

It might be a easier to find a way to [extend our new logging subsystem](http://next.rabbitmq.com/logging.html), say, to log to an external service exclusively. Using short paths for only a subset of directories might also be an option.

I don't think [overriding RABBITMQ_LOGS_BASE](http://www.rabbitmq.com/relocate.html) to point to an external location that does not use short filenames would change this behavior but it's quite a quick thing to try.

At this stage this belongs to rabbitmq-users.

**Comment by andymartin** [comment]
Informational addenda for those who might search on this issue in the future:

1. Disabling 8.3 filenames on the target volume does not solve the problem. 

2. Using env variables to specify 8.3-compliant filenames also does not work. That is:
```
RABBITMQ_LOGS=D:\Logging\rabbitmq.log
RABBITMQ_SASL_LOGS=D:\Logging\sasl.log
```
Still creates:
```
RABBIT~3.LOG
RABBIT~4.LOG
```

Will be awaiting 3.7 release to determine whether this can be resolved with new logging framework.
