### ISSUE TITLE
Two lxc nodes on  Physical machine.when I run two RabbitMQ nodes on the different lxc.The first one start successfully,but the second one failed to start.The RabbitMQ node log is:Failed to create thread:Resource temporarily unavaliable /usr/lib/rabbitmq/bin/rabbitmq-server:line 271 :7685 Aborted.The erl_carsh is:=erl_crash_dump:0.3 Tue Jul 25 15:58:43 2017 Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{ker System version: Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false].The RabbitMQ version is 3.6.10,the Eralng version is 19.3.6 .I am very confused about it,can anyone help me,thanks very much!

### ISSUE THREAD

**Issue by pengkeboy** [rabbitmq/rabbitmq-server#1416]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version
* Erlang version
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
* Client library version (for all libraries used)
* Operating system, version, and patch level

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by Ayanda-D** [comment]
😆
