### ISSUE TITLE
Two Erlang nodes can't run on different lxc nodes in one  Physical machine.

### ISSUE THREAD

**Issue by pengkeboy** [rabbitmq/rabbitmq-server#1417]
Two lxc nodes in one Physical machine.
when I run two RabbitMQ nodes on the different lxc.
The first one can start successfully,but the second one failed to start.

The RabbitMQ node log is :
~~~
Failed to create thread:Resource temporarily unavaliable /usr/lib/rabbitmq/bin/rabbitmq-server:line 271 :7685 Aborted.
~~~
The erl_crash_dump log is
~~~
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{ker
System version: Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]
Compiled: Fri Jun  9 10:21:15 2017
Taints: erl_tracer
Atoms: 6466
Calling Thread: scheduler:1
=scheduler:1
Scheduler Sleep Info Aux Work:
Current Port:
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK | NONEMPTY | UNKNOWN(134217728)
Current Process: <0.0.0>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | TRAP_EXIT | ON_HEAP_MSGQ
Current Process Program counter: 0x00007f046c85c2b8 (init:sleep/1 + 64)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007f04b3d127c0:SReturn addr 0x6C8586B0 (init:boot_loop/2 + 3560)
0x00007f04b3d127c8:SReturn addr 0x9025F8 (<terminate process normally>)

~~~

The RabbitMQ version is 3.6.10.
The Erlang version is 19.3.6 .

I am very confused about it,can anyone help me? 
Thanks very much!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
> Failed to create thread:Resource temporarily unavaliable
> {failed_to_start_child,net_kernel,{'EXIT',nodistribution}}

are the lines you are looking for.
