### ISSUE TITLE
could this happen one unacked message resend to all other consumers

### ISSUE THREAD

**Issue by Jacob201311** [rabbitmq/rabbitmq-server#1418]
## ENV
CentOS 6.0
MQ：3.5.2 
OTG：19.1

## PHENOMENON
1. 3 sever, with 9 consumers one server, consume 1 queue. ack required, prefech 1
2. C1(consumer 1) receive a message and handle it, the job process a very long time，the big message(600k size) contains 8w small job. The job handler method is a loop
3. About 50m later, bad thing happend, the message handled by C1 had been received by other 26 consumers，but how could this happen？

## IMAGE
![image](https://user-images.githubusercontent.com/5900706/32273363-30cf29cc-bed0-11e7-8fd4-b39ce2dcf0e6.png)

![image](https://user-images.githubusercontent.com/5900706/32264587-623339cc-bead-11e7-8c1e-a57c94780114.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
A single message can only be delivered to one consumer. If that consumer immediately requeues it or its channel is closed, it will be delivered to the next one, then the next one, and so on.
