### ISSUE TITLE
Rabbitmq 3.6 cannot start after change config file

### ISSUE THREAD

**Issue by mekhaba** [rabbitmq/rabbitmq-server#1420]
Hi to all, 
I have very hard problem concern configuration of rabbitmq, 
when I create rabbitmq.config in /etc/rabbitmq/ directory I will not problem, but when I do any change, event if simple like :  uncomment 
`%% {tcp_listeners, [5672]},`
the rabbitmq doesn't restart, 
Can you give me any ways to resolve this problem.
Thanks in advance :)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Without having the exact config file, node output and/or logs, even the core team cannot help you.

**Comment by Xanhou** [comment]
Had the same issue. Solved by doing the following:
1. Copy the config example.
2. Delete the two %% in front of the config line you want to add to the config, but not the space.
3. Delete the comma behind the config line

I only needed to change one line, but my guess is that you have to only remove the comma from the last entry.

ps. Im commenting on this because it poped up high in google for me, so hopefully the next person with the same issue sees this solution.

**Comment by lukebakken** [comment]
Thank you @Xanhou. Since this issue shows up in search results, I will provide the following steps for validating the syntax of the `rabbitmq.config` or `advanced.config` file. These are the Erlang term style configuration files, *not* the ini-style file that uses the `.conf` extension.

* Save your configuration in `/etc/rabbitmq/rabbitmq.config`
* Run the following command:

```
erl -noshell -eval 'io:format("~p~n", [file:consult("/etc/rabbitmq/rabbitmq.config")]).' -eval 'init:stop().'
```

You will either see output that begins with `{ok, ...}` indicating success, or a syntax error message.
