### ISSUE TITLE
The server is throwing error when the mosquitto_pub is trying to connect

### ISSUE THREAD

**Issue by kiraniyengar** [rabbitmq/rabbitmq-server#1432]
I have enabled the mqtt on the rabbitmq and trying to connect using the mosquitto_pub and mosquitto_sub, the clients are not getting connected, if I check the logs of the rabbitmq it is continuously throwing error, Attaching the log files for your reference

RabbitMQ Version - RabbitMQ 3.6.0
Client - Mosquitto_pub
OS - Windows 10 Pro

Plugins

 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   [failed to contact rabbit@FTSWL004 - status not shown]
 |/
[e ] amqp_client                       3.6.0
[  ] cowboy                            1.0.3
[  ] cowlib                            1.0.1
[e ] mochiweb                          2.13.0
[  ] rabbitmq_amqp1_0                  3.6.0
[  ] rabbitmq_auth_backend_ldap        3.6.0
[  ] rabbitmq_auth_mechanism_ssl       3.6.0
[  ] rabbitmq_consistent_hash_exchange 3.6.0
[  ] rabbitmq_event_exchange           3.6.0
[  ] rabbitmq_federation               3.6.0
[  ] rabbitmq_federation_management    3.6.0
[E ] rabbitmq_management               3.6.0
[e ] rabbitmq_management_agent         3.6.0
[  ] rabbitmq_management_visualiser    3.6.0
[E ] rabbitmq_mqtt                     3.6.0
[  ] rabbitmq_recent_history_exchange  1.2.1
[  ] rabbitmq_sharding                 0.1.0
[  ] rabbitmq_shovel                   3.6.0
[  ] rabbitmq_shovel_management        3.6.0
[  ] rabbitmq_stomp                    3.6.0
[  ] rabbitmq_tracing                  3.6.0
[e ] rabbitmq_web_dispatch             3.6.0
[  ] rabbitmq_web_stomp                3.6.0
[  ] rabbitmq_web_stomp_examples       3.6.0
[  ] sockjs                            0.3.4
[e ] webmachine                        git

[rabbit@FTSWL004.log](https://github.com/rabbitmq/rabbitmq-server/files/1501610/rabbit.FTSWL004.log)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
The connection fails to log in:

```
** Reason for termination == 
** {{case_clause,{error,not_allowed}},
    [{rabbit_mqtt_processor,process_login,4,
                            [{file,"src/rabbit_mqtt_processor.erl"},
                             {line,406}]},
     {rabbit_mqtt_processor,process_request,3,
                            [{file,"src/rabbit_mqtt_processor.erl"},
                             {line,81}]},
     {rabbit_mqtt_reader,process_received_bytes,2,
                         [{file,"src/rabbit_mqtt_reader.erl"},{line,224}]},
     {gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1049}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
```

Please upgrade to 3.6.14 first and then see the authentication section in [MQTT plugin docs](http://www.rabbitmq.com/mqtt.html) as well as guides on access control and virtual hosts in [the rest of documentation](http://www.rabbitmq.com/documentation.html) to get a more complete picture.
