### ISSUE TITLE
Consider an option to dead-letter rejected publishes

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1443]
Since version 3.7.0 RabbtitMQ queues have an option to reject publishes if a queue reaches it's limit.
Currently rejected messages are not dead-lettered, unlike messages dropped from the queue head.
Dead-lettering them will help if publisher confirms are not enabled or if the client does not know what to do with a rejected message.

**Comment by WGH-** [comment]
> Dead-lettering them will help if publisher confirms are not enabled or if the client does not know what to do with a rejected message.

To elaborate, publisher confirms don't give the information which queue overflowed. So you can't re-publish the message to that exact queue, only re-publish the message as a whole, which would lead to duplicates in other queues.

When message is dead-lettered, however, it includes the exact queue where they were dropped, so you can republish it back to exact same queue using the default direct exchange.

This trick can be used to implement sort of publisher flow control: once it notices own messages being dead-lettered, it can slow down producing until all dead-lettered message are successfully republished.

You can employ this trick with `drop-head`, but since messages are dropped from the front, you'll obviously end up with reordered messages. 

Moreover, using it for flow control is complicated by the fact that one publisher may get its own messages back even though it's some other publisher who overflowed the queue and needs to pause.

**Comment by michaelklishin** [comment]
@hairyhum @kjnilsson @dcorbacho thoughts?

**Comment by ansd** [comment]
> To elaborate, publisher confirms don't give the information which queue overflowed.

We could include the name of the queue that rejected the message (and even the reason why the message was rejected) in the `error` field of the `Rejected` outcome.

Done in  https://github.com/rabbitmq/rabbitmq-server/pull/15075
