### ISSUE TITLE
RabbitMQ getting a flood of connect, disconnect and reconnect of TCP

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [rabbitmq/rabbitmq-server#1448]
I have noticed in my Docker Swarm that after one of my containers that has a celery has missed a heartbeat and tried to send a task, it will then hang and I check my logs this is what is shown

```
=WARNING REPORT==== 12-Dec-2017::11:52:44 ===
closing AMQP connection <0.27756.1813> (10.0.1.44:57706 -> 10.0.1.33:5672, vhost: 'peter1_vhost', user: 'peter1'):
client unexpectedly closed TCP connection

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
connection <0.27588.1813> (10.0.1.44:57710 -> 10.0.1.33:5672): user 'peter1' authenticated and granted access to vhost 'peter1_vhost'

=WARNING REPORT==== 12-Dec-2017::11:52:44 ===
closing AMQP connection <0.27562.1813> (10.0.1.44:57708 -> 10.0.1.33:5672, vhost: 'peter1_vhost', user: 'peter1'):
client unexpectedly closed TCP connection

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
accepting AMQP connection <0.28103.1813> (10.0.1.44:57714 -> 10.0.1.33:5672)

=WARNING REPORT==== 12-Dec-2017::11:52:44 ===
closing AMQP connection <0.27588.1813> (10.0.1.44:57710 -> 10.0.1.33:5672, vhost: 'peter1_vhost', user: 'peter1'):
client unexpectedly closed TCP connection

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
connection <0.28103.1813> (10.0.1.44:57714 -> 10.0.1.33:5672): user 'peter1' authenticated and granted access to vhost 'peter1_vhost'

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
accepting AMQP connection <0.28178.1813> (10.0.1.44:57716 -> 10.0.1.33:5672)

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
connection <0.28178.1813> (10.0.1.44:57716 -> 10.0.1.33:5672): user 'peter1' authenticated and granted access to vhost 'peter1_vhost'

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
accepting AMQP connection <0.27644.1813> (10.0.1.44:57718 -> 10.0.1.33:5672)

=WARNING REPORT==== 12-Dec-2017::11:52:44 ===
closing AMQP connection <0.28178.1813> (10.0.1.44:57716 -> 10.0.1.33:5672, vhost: 'peter1_vhost', user: 'peter1'):
client unexpectedly closed TCP connection

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
connection <0.27644.1813> (10.0.1.44:57718 -> 10.0.1.33:5672): user 'peter1' authenticated and granted access to vhost 'peter1_vhost'

=INFO REPORT==== 12-Dec-2017::11:52:44 ===
accepting AMQP connection <0.28638.1813> (10.0.1.44:57720 -> 10.0.1.33:5672)

=WARNING REPORT==== 12-Dec-2017::11:52:44 ===
closing AMQP connection <0.28103.1813> (10.0.1.44:57714 -> 10.0.1.33:5672, vhost: 'peter1_vhost', user: 'peter1'):
client unexpectedly closed TCP connection

=WARNING REPORT==== 12-Dec-2017::11:52:44 ===
closing AMQP connection <0.27644.1813> (10.0.1.44:57718 -> 10.0.1.33:5672, vhost: 'peter1_vhost', user: 'peter1'):
client unexpectedly closed TCP connection
```

That serieis of connect, disconnect and reconnecting will just continue all throughout. It works normally on a normal Docker Engine in my local but not Docker Swarm cluster in the cloud.

PS.
- I am using 3.7 version of rabbitmq
- I am using 17.11 version of docker

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Check yours apps. Those are client connections, see [Connection Event Logging](http://www.rabbitmq.com/networking.html).

**Comment by Dean-Christian-Armada** [comment]
The question is why does it only occur when using Docker Swarm prdouction and not my local Docker

**Comment by michaelklishin** [comment]
@Dean-Christian-Armada we do not know anything about your applications, so we cannot possibly help. Logs, [Network Troubleshooting guide](http://www.rabbitmq.com/troubleshooting-networking.html) and a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) plus adding logging/metrics to your apps is what you should employ.

**Comment by michaelklishin** [comment]
One thing that's obvious to me from the log: apps connection and immediately *close TCP connection* (that does not count for disconnecting, as [Networking](https://www.rabbitmq.com/networking.html) explains). Which almost always indicates a failing app or an unhandled exception that causes it to exit very early on. Application-level monitoring and logs can prove this hypothesis. Don't guess, collect data instead.
