### ISSUE TITLE
Upgrade from 3.6 to 3.7: 

### ISSUE THREAD

**Issue by twentyfortytwenty** [rabbitmq/rabbitmq-server#1457]
Hello fellow rabbits,

In our development environment, we upgraded from 3.6 to 3.7. We are now facing a problem we did not see before with 3.6. Our stack is `RabbitMQ -> RabbitMQ STOMP -> RabbitMQ WEB STOMP -> NGINX` in the backend and `AngularJS -> stomp-websocket` in the frontend.

When the frontend is connecting to the stomp interface on port 15674, proxied by the nginx server, we are now seeing the following error:

`Failed to load https://dev-stomp/stomp/info?t=1513934445916: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dev-site' is therefore not allowed access. The response had HTTP status code 404.`

I could not find any particular change in the changelog which is related to this. Which component in the stack should fix this and how can this be done?

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
CORS support is available in [Web STOMP as of 3.6.0](https://github.com/rabbitmq/rabbitmq-web-stomp/issues/12). If it is a change in RabbitMQ itself, it's either [in the Web STOMP plugin](https://github.com/rabbitmq/rabbitmq-web-stomp/tree/v3.7.x) or due to our migration to Cowboy 2. Either way, it's a mere speculation because we have next to no details about the environment or a way to reproduce plus there's an external HTTP server/reverse proxy involved => mailing list material.
