### ISSUE TITLE
Temporarily increase logging limit when node is booting so that Lager doesn't drop important messages from boot steps and plugins

### ISSUE THREAD

**Issue by oneiros-de** [rabbitmq/rabbitmq-server#1471]
We have a node which logs

```
[warning] <0.32.0> lager_error_logger_h dropped 77 messages in the last second that exceeded the limit of 100 messages/sec
```

on boot.

Googling for this let to [this discussionon on lager](https://github.com/erlang-lager/lager/issues/180) and [this pull on lager](https://github.com/erlang-lager/lager/pull/411).

Perhaps RabbitMQ can avoid dropping log messages during startup.

**Comment by biiiipy** [comment]
We have the same issue

**Comment by michaelklishin** [comment]
I'm pretty sure we run a Lager version that includes https://github.com/erlang-lager/lager/pull/411. However, https://github.com/erlang-lager/lager/pull/411 will not necessarily make log message dropping disappear.

Before I explain what would be an improvement we should take a step back and ask ourselves what the warning means in the first place. Original Erlang/OTP logger (and any other logging library in any language) can be overwhelmed by the callers. When that happens, its memory usage baloons, sometimes to the point it can cause major issues for node stability. There is an entire chapter about this in Erlang in Anger.

Lager and some other logging tools avoid this by dropping some messages when they consider themselves to be overwhelmed.

RabbitMQ on boot can print quite a few things in a very short period of time, especially when debug logging is used. So some messages are dropped, which is not a problem in and of itself but it can mask log entries that are particularly important for investigations.

Since boot step messages are unlikely to really overwhelm the logger, we can temporarily bump the limit and then lower it to make sure all boot messages are logged.

**Comment by lukebakken** [comment]
@oneiros-de @biiiipy - could you please create the [`/etc/rabbitmq/advanced.config`](https://www.rabbitmq.com/configure.html#advanced-config-file) file with this content and restart your node?

```
[
    {lager, [
        {error_logger_hwm, 1024}
    ]}
].
```

Could you confirm that, with this setting, messages are not dropped when your node boots? The reason I ask is that I can't reproduce the dropped message scenario even with debug logging enabled. I am working on raising the `error_logger_hwm` limit temporarily during startup.

**Comment by oneiros-de** [comment]
@lukebakken I tested the setting; no change. The system is a VM with one core.

**Comment by biiiipy** [comment]
@lukebakken worked for me, but I had to add that config to ``rabbitmq.config`` file 

@oneiros-de check your log, if it says ``lager_error_logger_h dropped XX messages in the last second that exceeded the limit of 100 messages/sec`` then that means that you haven't successfully changed default 100 message limit

**Comment by lukebakken** [comment]
@biiiipy are you setting the configuration file name via an environment variable or via `/etc/rabbitmq/rabbitmq-env.conf`? The reason I ask is that RabbitMQ 3.7 and beyond uses an `ini`-compatible configuration format, as well as the old-style Erlang term format file (https://www.rabbitmq.com/configure.html).

**Comment by biiiipy** [comment]
@lukebakken no, we're just setting RABBITMQ_BASE variable. Not sure why ``advanced.config`` didn't work

**Comment by michaelklishin** [comment]
There is a section on [verifying configuration](http://www.rabbitmq.com/configure.html) in the docs. Anyhow, the logging rate watermark will be temporarily 10 times higher during boot as of 3.7.3.
