### ISSUE TITLE
Message consumption rate anomaly after restart

### ISSUE THREAD

**Issue by cachiama** [rabbitmq/rabbitmq-server#1476]
Hi,

Here at SuprNation we discovered an anomaly with message consumption rates on RabbitMQ. Our scenario involves consuming a pileup of small messages (containing single integer values) from a durable queue by a single consumer. We are bound by a single consumer as message order is crucial to our business case.

The consumption rate of messages is very fast if the first interaction after starting up RabbbitMQ, is message consumption. However, if message consumption is performed after publishing a given amount of durable messages (even after reductions and disk writes go down to 0), a significantly lower consumption rate is achieved.

The table below illustrates the rates achieved on my 2017 MacBook Pro (2.7 GHz Intel Core i7 processer, 16 GB RAM) development machine:

| Rabbit Version | Consumption rate after publishing finishes | Consumption rate after restart | Reduction Rate after publishing finishes | Reduction rate after restart |
|----------------|--------------------------------------------|--------------------------------|------------------------------------------|------------------------------|
| 3.7.2 (latest) | 12,800/s                                   | 18,400/s                       | 9,100,000/s                              | 14,400,00/s                  |
| 3.6.0          | 8,400/s                                    | 18,200/s                       | Unavailable                              | Unavailable                  |
| 3.5.0          | 5,500/s                                    | 18,200/s                       | Unavailable                              | Unavailable                  |

We tried this scenario on earlier versions to try to determine if this behaviour started after a particular release but unfortunately, this anomaly was still observed in version 3.5.0 which is the oldest docker image available.

A small [poc.zip](https://github.com/rabbitmq/rabbitmq-server/files/1632202/poc.zip) which replicates this behaviour is attached. The below are the steps to replicate.

- Install JRE, docker and docker-compose
- Start RabbitMQ by running `docker-compose stop && docker-compose rm -f && docker-compose up` in the root folder of the POC
- Run `com.suprnation.rabbit.Producer` class to produce 1.2M messages and wait for it to terminate.
- After the Producer stops producing, run the `com.suprnation.rabbit.Consumer` which will consume 500K messages.
- Keep note of the last console line which logs the overall message rate (Rate 1).
- Now restart RabbitMQ using `docker-compose stop && docker-compose rm -f && docker-compose up`
- Re-run `com.suprnation.rabbit.Consumer` and keep note of the last console line which logs the significantly overall message rate (Rate 2).
- Rate 2 will be significantly higher than Rate 1.

Could you please help us determine whether there is anything wrong with our setup, if this is expected behaviour, or if this is indeed an issue?

Thanks in advance,
Mark Anthony

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
After a certain number of enqueued messages queues have to move them to disk *and* deliver to consumers and those things are not entirely parallel. Paging out a lot of transient messages to disk is certainly a fairly expensive operation. It is possible to see how may messages are in memory/on disk/on disk after a forced page out on the queue page in management UI.

On top of that there are several other factors that are dynamic in nature and affect throughput:

 * TCP window scaling kicks in after a certain point
 * How the VM does scheduling (processes with spikes of activity will get less scheduler time after a certain point)

Please keep questions to rabbitmq-users.

**Comment by lukebakken** [comment]
Hi @cachiama -

If you decide to continue discussion on the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users), please also reproduce this issue outside of a Docker environment and report on what you observe. Also, I'm assuming that you are not using OS X in production so details about if you see this in your production environment and what operating system you use there will be valuable as well.

Thanks!

**Comment by cachiama** [comment]
Thank you for your comments. We have repeated the experiment on our Linux live environment and posted the results on https://groups.google.com/forum/#!topic/rabbitmq-users/POPqrNLNZrs. Spoiler alert the drop is still present.
