### ISSUE TITLE
[{key_missing,ackmode}] while using raabitmqadmin version 3.7.0

### ISSUE THREAD

**Issue by compengsamit** [rabbitmq/rabbitmq-server#1496]
After upgrading rabbitmq on our Debian server to latest 3.7 version, the following error is occurring:
<pre>
$ rabbitmqadmin get requeue=true queue=test_url_queue
*** [{key_missing,ackmode}]
</pre>

Environment:
Rabbitmq version: 3.7.0
Erlang version: 1.20.1
OS: Debian 9 (Stretch)

I checked online but could not get any solution.
Could you please provide a proper solution for this?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You are looking at [this change in rabbitmq-management](https://github.com/rabbitmq/rabbitmq-management/issues/68). You must use the same `rabbitmqadmin` version as ships with RabbitMQ, in other words, a 3.7.x version against a 3.7.x node and 3.6.15 against 3.6.15.
