### ISSUE TITLE
Rabbit MQ server stops responding. 

### ISSUE THREAD

**Issue by Rajesh1213** [rabbitmq/rabbitmq-server#1500]
ERROR – #<Bunny::Session>Got an exception when
receiving data: Connection reset by peer (Errno::ECONNRESET)

RMQ has lost it's connection to the application and the errors persist until
the resque-pool service is restarted.

This is occurring in production, this has started happening more frequently. 
Kindly please do the needful

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
> RMQ has lost it's connection to the application and the errors persist until
> the resque-pool service is restarted

RabbitMQ does not connect to applications, it's the other way around. Make sure that you have [connection recovery enabled](http://rubybunny.info/articles/error_handling.html) in Bunny, understand how it works and there are no proxies or load balancers with [low idle connection timeout](http://www.rabbitmq.com/heartbeats.html#tcp-proxies) as your first steps.

If you use Resque and your connections to RabbitMQ are short lived, make sure they are not leaked in your code and that RabbitMQ nodes have at least 15-20K of [file descriptors available](http://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections-open-file-handles-limit).

Lastly make sure you don't run on Erlang/TP 18.x since there are known bugs that can lead to node not accepting connection (although if restarting Resque helps then it doesn't seem to be an issue).

This is 100% mailing list material.
