### ISSUE TITLE
Rabbitmq consumer does not process/return processed message to client 

### ISSUE THREAD

**Issue by irfanjs** [rabbitmq/rabbitmq-server#1530]
hi,
i have created the publisher -  consumer "reply-to pattern" using rabbitmq tutorial 6 guide. 
the issue , publisher and consumer works fine when the publisher sends the message first time. for second time, consumer does not do anything. 
i am not sure wheather issue with replyTo queue. I am not using any exchange. 
basically, by using this url , i have developed my code : https://www.rabbitmq.com/tutorials/tutorial-six-java.html
please help ... 
please let me know where i can paste the code 

Regards,

**Comment by lukebakken** [comment]
Thank you for your time.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by irfanjs** [comment]
Thanks lukebakken.
i m using rabbitmq java library having version 1.5. 
there is no any exception and log also does not have any info....

i think once you have a look on code, you can easily understand where could be the issue. it might not take much time of yours ..
please let me know where i can paste the code ?

regards,

**Comment by lukebakken** [comment]
Please, post your question to the mailing list. If you would like to provide your code, creating a GitHub repository with it works great. Just be sure that everything that is necessary to build and run your code is in the repository.

**Comment by michaelklishin** [comment]
@irfanjs our public mailing list is [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).
