### ISSUE TITLE
some of mqtt client cannot connected with rabbitmq

### ISSUE THREAD

**Issue by hui6075** [rabbitmq/rabbitmq-server#1534]
Hi,

I have use Eclipse Paho MQTT Utility, paho.mqtt.golang, libmosquitto as the client to connect with rabbitmq, but only Eclipse Paho MQTT Utility can connect success.

paho.mqtt.golang return error:
Identifier rejected

libmosquitto return error:
Error: The connection was lost.

Could you give some help? I have enabled mqtt with allow_anonymous = true.
/etc/rabbitmq/rabbitmq.config:
[{rabbitmq_mqtt,
 {allow_anonymous, true}
}]

version:
rabbit,"RabbitMQ","3.1.5"
rabbitmq_mqtt,"RabbitMQ MQTT Adapter","3.1.5"
erlang_version,"Erlang/OTP 19 [erts-8.0]
OS:
Red Hat Enterprise Linux Server release 6.3
Linux 2.6.32-279.el6.x86_64

log:
=CRASH REPORT==== 27-Feb-2018::17:49:40 ===
  crasher:
    initial call: rabbit_mqtt_reader:init/1
    pid: <0.387.0>
    registered_name: []
    exception exit: {{badmatch,not_registered},
                     [{rabbit_mqtt_reader,stop,2,[]},
                      {gen_server2,handle_msg,2,[]},
                      {proc_lib,init_p_do_apply,3,
                                [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server2:terminate/3
    ancestors: [rabbit_mqtt_client_sup,rabbit_mqtt_sup,<0.284.0>]
    messages: []
    links: [<0.286.0>,#Port<0.12373>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 733
  neighbours:

=SUPERVISOR REPORT==== 27-Feb-2018::17:49:40 ===
     Supervisor: {local,rabbit_mqtt_client_sup}
     Context:    child_terminated
     Reason:     {{badmatch,not_registered},
                  [{rabbit_mqtt_reader,stop,2,[]},
                   {gen_server2,handle_msg,2,[]},
                   {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.387.0>},
                  {name,client},
                  {mfa,{rabbit_mqtt_reader,start_link,[]}},
                  {restart_type,temporary},
                  {shutdown,4294967295},
                  {child_type,worker}]

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The only piece of advice we have for 3.1.x is [upgrade](http://www.rabbitmq.com/upgrade.html). You are [dozens of releases and several years behind](http://www.rabbitmq.com/changelog.html).
