### ISSUE TITLE
RabbitMQ service started, but connect will fail.

### ISSUE THREAD

**Issue by LoveJenny** [rabbitmq/rabbitmq-server#1551]
We have a windows service which use RabbitMQ,  We have configured to dependence on RabbitMQ, and When RabbitMQ started, We try to connect, the connection will fail.

It's weired, The RabbitMQ service is started, but It doesn't ready to connect.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you..

**Comment by michaelklishin** [comment]
We can't suggests anything with the amount of information provided. Please help others help you by posting as many details as possible, including server logs and full exceptions to the mailing list.

http://www.rabbitmq.com/troubleshooting-networking.html documents a methodology we recommend for troubleshooting connectivity issues. Please start there.
