### ISSUE TITLE
Add service fabric Naming service to Peer Discovery Subsystem.

### ISSUE THREAD

**Issue by grantwar** [rabbitmq/rabbitmq-server#1554]
I'm trying to get RabbitMQ to work with the service fabric naming service, within a docker image (much like autocluster would have) with little luck. Could you please add this as an additional mechanism to or let me know if there is there anything in the pipeline regarding this feature.

**Comment by michaelklishin** [comment]
Our small team doesn't have the capacity to work on new peer discovery mechanisms in the near future. The community is welcome to develop whatever they need since most mechanisms are already plugins.

In addition we expect issues to have a certain amount of details and this one is really light on details. Feel free to start a rabbitmq-users thread about why it is necessary, what it might look like and who may be interesting in helping you develop this mechanism.

**Comment by SierraNL** [comment]
I would also like to see this implemented.

Looking at the other peer discovery plugins, like the AWS one, I believe this could also be implemented for Azure Service Fabric, using the API:
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-index

You can use containers in Service fabric, and give these containers a specific RabbitMQ service type, like the tags in the AWS plugin.
So you could make the plugin look for other RabbitMQ instances using the API to find instances of it's own service type.

I've never tried Erlang, so I'm not comfortable writing the plugin, but I could help gather the required information or do some testing.
