### ISSUE TITLE
Filtering data from queue.

### ISSUE THREAD

**Issue by abhisheksinghbanarasi** [rabbitmq/rabbitmq-server#1559]
how to get some part of messages from rabbitmq and get message on some prameters. here i do not want to create more than one queue.

For Example: If I want to message of id= 1, then i should be able to get meassage from rabbitm queue using that id.  And also i want to get only ids of a messages in the queue. I do not want to get all message. i need to get only some part of the message avaailable in the rabbitmq queue.
and delete message manually from queue by provididng ids of the message. for example- if i want to delete a message of specific id then i will call delete function and id as a parameter and this method will do rest of the thing like deleting entries fron the queue. silimar way i need to implement getting specific message by providing ids. like if i provide call a method with id as parameter then this method will provide the message from rabbitmq queue of provided id.

Thanks in advance.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [tutorial 2](http://www.rabbitmq.com/getstarted.html) and [the guide on consumer acknowledgements](http://www.rabbitmq.com/confirms.html). If that's not enough for your needs, you probably should use a database with a query language, not [just] RabbitMQ.
