### ISSUE TITLE
rabbitmq errors

### ISSUE THREAD

**Issue by prolen** [rabbitmq/rabbitmq-server#1560]
some errors occur after running for days.
some clients get errors such as AMQP 172.x.x.x is unreachable now and then, but its service is ok.

=CRASH REPORT==== 23-Feb-2018::14:30:24 ===
  crasher:
    initial call: rabbit_disk_monitor:init/1
    pid: <0.85.0>
    registered_name: rabbit_disk_monitor
    exception exit: {unparseable,"/bin/df: '/usr/local/lib/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@mq84619641': No such file or directory\n"}
      in function  gen_server:terminate/6 (gen_server.erl, line 737)
    ancestors: [rabbit_disk_monitor_sup,rabbit_sup,<0.77.0>]
    messages: []
    links: [<0.84.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 18982466
  neighbours:

=SUPERVISOR REPORT==== 23-Feb-2018::14:30:24 ===
     Supervisor: {local,rabbit_disk_monitor_sup}
     Context:    child_terminated
     Reason:     {unparseable,"/bin/df: '/usr/local/lib/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@mq84619641': No such file or directory\n"}
     Offender:   [{pid,<0.85.0>},
                  {name,rabbit_disk_monitor},
                  {mfargs,{rabbit_disk_monitor,start_link,[100000000]}},
                  {restart_type,{transient,1}},
                  {shutdown,4294967295},
                  {child_type,worker}]
=SUPERVISOR REPORT==== 23-Feb-2018::14:30:24 ===
     Supervisor: {local,rabbit_disk_monitor_sup}
     Context:    start_error
     Reason:     unsupported_platform
     Offender:   [{pid,{restarting,<0.85.0>}},
                  {name,rabbit_disk_monitor},
                  {mfargs,{rabbit_disk_monitor,start_link,[100000000]}},
                  {restart_type,{transient,1}},
                  {shutdown,4294967295},
                  {child_type,worker}]
=CRASH REPORT==== 23-Feb-2018::14:35:19 ===
  crasher:
    initial call: rabbit_reader:init/2
    pid: <0.3517.2>
    registered_name: []
    exception exit: {aborted,
                        {no_exists,[rabbit_runtime_parameters,cluster_name]}}
      in function  mnesia:abort/1 (mnesia.erl, line 310)
      in call from rabbit_runtime_parameters:lookup0/2
      in call from rabbit_runtime_parameters:value0/2
      in call from rabbit_reader:server_properties/1 (/usr1/mesos/data/slaves/14630586-f200-43ea-bba9-d42a707bbd6f-S267/frameworks/961fa35f-2c92-4fbd-af3e-b90e969bc459-2023/executors/mesos-jenkins-73f4a31394214adbbde1b3d345fa9618-OceanStorDJ_Pack/runs/235ff257-c6dc-4d88-84fd-02b5eb8e14dd/jenkins/workspace/p5, line 167)
      in call from rabbit_reader:start_connection/3 (/usr1/mesos/data/slaves/14630586-f200-43ea-bba9-d42a707bbd6f-S267/frameworks/961fa35f-2c92-4fbd-af3e-b90e969bc459-2023/executors/mesos-jenkins-73f4a31394214adbbde1b3d345fa9618-OceanStorDJ_Pack/runs/235ff257-c6dc-4d88-84fd-02b5eb8e14dd/jenkins/workspace/p5, line 921)
      in call from rabbit_reader:handle_input/3 (/usr1/mesos/data/slaves/14630586-f200-43ea-bba9-d42a707bbd6f-S267/frameworks/961fa35f-2c92-4fbd-af3e-b90e969bc459-2023/executors/mesos-jenkins-73f4a31394214adbbde1b3d345fa9618-OceanStorDJ_Pack/runs/235ff257-c6dc-4d88-84fd-02b5eb8e14dd/jenkins/workspace/p5, line 871)
      in call from rabbit_reader:recvloop/4 (/usr1/mesos/data/slaves/14630586-f200-43ea-bba9-d42a707bbd6f-S267/frameworks/961fa35f-2c92-4fbd-af3e-b90e969bc459-2023/executors/mesos-jenkins-73f4a31394214adbbde1b3d345fa9618-OceanStorDJ_Pack/runs/235ff257-c6dc-4d88-84fd-02b5eb8e14dd/jenkins/workspace/p5, line 327)
      in call from rabbit_reader:run/1 (/usr1/mesos/data/slaves/14630586-f200-43ea-bba9-d42a707bbd6f-S267/frameworks/961fa35f-2c92-4fbd-af3e-b90e969bc459-2023/executors/mesos-jenkins-73f4a31394214adbbde1b3d345fa9618-OceanStorDJ_Pack/runs/235ff257-c6dc-4d88-84fd-02b5eb8e14dd/jenkins/workspace/p5, line 309)
    ancestors: [<0.3515.2>,rabbit_tcp_client_sup,rabbit_sup,<0.77.0>]
    messages: []
    links: [<0.3515.2>]
    dictionary: [{process_name,
                      {rabbit_reader,
                          <<"8.46.196.41:45804 -> 8.46.196.41:5671">>}}]
    trap_exit: true
    status: running
    heap_size: 10958
    stack_size: 27
    reductions: 3685
  neighbours:

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This has been discussed numerous times on rabbitmq-users.

```
/bin/df: '/usr/local/lib/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@mq84619641': No such file or directory\n
```

means that node's free disk space monitor tried to run `df` against `/usr/local/lib/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@mq84619641` and that returned `No such file or directory`. In modern versions (3.6.15, 3.7.x) that would simply disable disk space monitoring after N retry attempts. It is not a "node crash" and alone cannot affect node's ability to serve client connections (but there can be other issues with the same root cause that can).

**Comment by michaelklishin** [comment]
I have a guess how `df` subprocess failures can potentially be related to *some* clients failing to connect: your node may be running out of file descriptors for short periods of time.

See http://www.rabbitmq.com/networking.html and http://www.rabbitmq.com/production-checklist.html.
