### ISSUE TITLE
Rabbit does not post messages to subscribers after restart of one of the nodes in a cluster

### ISSUE THREAD

**Issue by shevino** [rabbitmq/rabbitmq-server#1562]
Hi Guys, 

I think I have just encountered a bug. I have a cluster of RabbitMQ consisting of two nodes. I have a producer and a consumer. The producer connects to node 1 and dispatches items to a queue. The consumer is connected to node 2 and is subscribed to receive items from the queue using the below code:
`               channel.BasicQos(0, maxFetchCountNoAck, false);
                
                 EventingBasicConsumer consumer = new EventingBasicConsumer(channel);
                consumer.ConsumerTag = QueueName; //The consumerTag is used to cancel consumuer 

                consumer.Received += Item_Received;

                channel.BasicConsume(queue: QueueName,
                                        autoAck: false,
                                        consumer: consumer);`

The problem arises when node 1 is restarted (simulating a server breakdown). The consumer connected to node 2 does not trigger a connection shutdown or something similar since node 2 is still active and connected. However when node 1 is back online and cluster is reformed, any posting of messages to the same queue would not be received by the consumer handler which is still connected to node 2, and the messages would just keep on accumulating in the queue. 

Shutting down the consumer and re-establishing the connection on the other hand would get everything working back to normal. The problem is that in such situations the messages would end up accumulating in the queue without getting notified.

Is this a known problem or am I doing something wrong? I'm running Rabbit 3.7.4 nodes on 2 different Window Servers 2012 as a cluster. My code is using the RabbitMQ .NET client v5.0.1. 

Would appreciate any help on this. 

Many thanks. 
Andre.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/pB7sHB_Vt6Y).
