### ISSUE TITLE
rabbitmqctl cannot run 

### ISSUE THREAD

**Issue by xulingfeng931027** [rabbitmq/rabbitmq-server#1563]
when i run rabbitmqctl in centos7 , it shows "escript: Premature end of file reached".it dosent work!!!why??

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
