### ISSUE TITLE
829 of items at a time

### ISSUE THREAD

**Issue by 727023460** [rabbitmq/rabbitmq-server#1565]
i use send.go that use dead cycle  to send massages
but at most number is 829 ,and then connected failed
i don't know how to configure it

this is send.go
```
package main

import (
	"fmt"
	"github.com/streadway/amqp"
	"log"
	"time"
)

func failOnError(err error, msg string) {
	if err != nil {
		log.Fatal("%s:%s", msg, err)
		panic(fmt.Sprintf("%s:%s", msg, err))
	}
}

func main() {
	for {
		time.Sleep(time.Millisecond * 10)
		conn, err := amqp.Dial("amqp://guest:guest@localhost:5672/")
		failOnError(err, "Failed to connect to RabbitMQ")
		defer conn.Close()

		ch, err := conn.Channel()
		failOnError(err, "Failed to connect to Channel")
		defer ch.Close()

		q, err := ch.QueueDeclare("hello", false, false, false, false, nil)
		failOnError(err, "Failed to declare a queue")
		body := "hello this is my test queue"

		err = ch.Publish("", q.Name, false, false, amqp.Publishing{
			ContentType: "text/plain",
			Body:        []byte(body),
		})
		failOnError(err, "Failed to publish a message")
	}
}
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
