### ISSUE TITLE
an out-of-the-box way to test user credentials (username/password)

### ISSUE THREAD

**Issue by richlv** [rabbitmq/rabbitmq-server#1576]
There seem to be two main ways to test a user name and password, a fairly common need:

* write a script
* install admin plugin and download rabbitmqadmin

These both are quite cumbersome and it would be great to include a way to test username/password out of the box.

This need has been mentioned in external resources as well: https://serverfault.com/questions/706511/how-to-verify-a-rabbitmq-user-password .

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
* There is [rabbitmqctl authenticate_user](http://www.rabbitmq.com/rabbitmqctl.8.html#authenticate_user)
 * `rabbitmqadmin` can be used if the user has the `management` tag (which can be added temporarily)
 * Alternative [authN backends](http://www.rabbitmq.com/access-control.html) have more options: LDAP tooling for the LDAP backend, curl for the HTTP backend and so on.

**Comment by richlv** [comment]
Sorry about the noise. I was checking on an older RabbitMQ version and nothing came up - turns out, `authenticate_user` was added in 3.6.5: https://rabbitmq.docs.pivotal.io/36/relnotes/release-notes-rabbitmq3.6.5.html

Thank you for that hint :)

**Comment by michaelklishin** [comment]
I'd recommend using [RabbitMQ's own change log](http://www.rabbitmq.com/changelog.html) since Pivotal RabbitMQ releases happen less frequently.

**Comment by richlv** [comment]
Thanks, but how come https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_5 does not list the new command?

**Comment by michaelklishin** [comment]
Sometimes things slip through the cracks. It's hardly a major addition. 3.6.5 is 20 months old now and CLI tools have been reworked and migrated to their own sub-project in 3.7.0, so I don't think it's worth mentioning at this point.
