### ISSUE TITLE
change default behaviour of rabbitMQ exchanges

### ISSUE THREAD

**Issue by govi20** [rabbitmq/rabbitmq-server#1581]
If exchange type is missing, RabbitMQ creates exchange of type Direct, is there any way to override the default behavior of RabbitMQ to create default exchanges of type Fanout? i.e if exchange type is not provided, it should be fanout and not direct.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
If an exchange does not exists, it's a channel error with code = Not Found. A node will pre-create several exchanges, including a fanout called `amq.fanout`, in the default vhost on first boot. It is also possible to [make it declare just about any topology you please](http://www.rabbitmq.com/management.html#load-definitions) on boot.
