### ISSUE TITLE
Message rates are not displayed for amq.rabbitmq.trace exchange in Web UI

### ISSUE THREAD

**Issue by Tensho** [rabbitmq/rabbitmq-server#1587]
When I publish a message to any exchange, message rates section of `amq.rabbitmq.trace` exchange page always displays `Currently idle`.

* RabbitMQ: 3.7.2
* Erlang: 20.1.7
* OS: MacOS High Sierra 10.13.4
 * Browser: Google Chrome 65.0.3325.181 (Official Build)
 * Management UI page: http://localhost:15672/#/exchanges/%2F/amq.rabbitmq.trace
 * `curl http://localhost:15672/#/exchanges/%2F/amq.rabbitmq.trace`

![screen shot 2018-04-25 at 13 08 24](https://user-images.githubusercontent.com/892721/39239531-d4e18da0-4889-11e8-92ec-757956ca033e.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
`amq.rabbitmq.trace` is a regular exchange that is only used when tracing for the vhost is enabled (of which we have no information). However, there's one thing that's unusual about it: it is not published to in a regular way. It is also declared as an internal exchange, meaning it is used internally by RabbitMQ.

RabbitMQ nodes already collect publishing totals. I see little value to worry about the fact that the tracing mechanism doesn't bother to collect metrics. Our team has hundreds of more important issues to spend our time on.

**Comment by Tensho** [comment]
@michaelklishin Thank you for the reply 🙇
