### ISSUE TITLE
Issue with RMQ-3.7.3 log files.

### ISSUE THREAD

**Issue by mohitdd** [rabbitmq/rabbitmq-server#1595]
I have upgraded the RabbitMq to 3.7.3 in my application.
On running, it's not generating any log file.

  ##  ##
  ##  ##      RabbitMQ 3.7.3. Copyright (C) 2007-2018 Pivotal Software, Inc.
  ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
  ######  ##
  ##########  Logs: (none)

              Starting broker...
 completed with 4 plugins.

Help Sought @michaelklishin

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
