### ISSUE TITLE
It's not explicit that you need to Cancel consumers before Deleting a queue (with TopologyRecoveryEnabled) 

### ISSUE THREAD

**Issue by TiagoJVO** [rabbitmq/rabbitmq-server#1602]
* RabbitMQ version: http://erlang.org/download/otp_win64_20.3.exe
* Erlang version: https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.4/rabbitmq-server-windows-3.7.4.zip
* A runnable code sample: [ConsoleApp1.zip](https://github.com/rabbitmq/rabbitmq-server/files/2016905/ConsoleApp1.zip)
* Client library version: RabbitMQ.Client 5.0.1

run the application to reproduce.
If the the line ```channel.BasicConsume(queue: queueName, autoAck: true, consumer: consumer);``` gets deleted or the consumer cancelled before deleting the queue, all works fine.

There is no Documentation regarding the need to cancel the consumer, only on the explicit operation documentation (https://www.rabbitmq.com/consumer-cancel.html). Its odd, because I need to access the page of an operation I need to use, without knowing I need to use it.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You don't need to cancel consumers before deleting a queue, it should not be necessary even when automatic recovery is enabled.

We cannot suggest much without seeing server logs. This is mailing list material.

**Comment by michaelklishin** [comment]
It's not clear to me what "works fine" (as well as "doesn't work fine") means in this context.

The example uses exclusive queues. They have [certain characteristics](http://www.rabbitmq.com/queues.html#exclusive-queues) that can be confusing to beginners. That's my best guess anyway.
