### ISSUE TITLE
[QUESTION] Is it possible to send a message to dead letter after 3 redeliveries?

### ISSUE THREAD

**Issue by bnbs** [rabbitmq/rabbitmq-server#1603]
I was developing a node.js service using ActiveMQ and in ActiveMQ to send a message for dead letter queue after 3 redeliveries i just needed to add this to activemq.xml. This configuration also add a redelivery delay so a message is only redelivery after 10000ms.

```
<plugins>
   <redeliveryPlugin fallbackToDeadLetter="true"
                              sendToDlqIfMaxRetriesExceeded="true">
       <redeliveryPolicyMap>
           <redeliveryPolicyMap>
                         
               <defaultEntry>
                   <!-- the fallback policy for all other destinations -->
                   <redeliveryPolicy
                                     maximumRedeliveries="3"
                                     redeliveryDelay="10000"/>
               </defaultEntry>

           </redeliveryPolicyMap>
      </redeliveryPolicyMap>
   </redeliveryPlugin>
</plugins>
```
Is there a way I can achieve the same behavior using RabbitMQ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
