### ISSUE TITLE
Number of mirrored queues become unavailable after restarting a node in the cluster

### ISSUE THREAD

**Issue by liudasbk** [rabbitmq/rabbitmq-server#1607]
When single node in a RabbitMQ cluster is restarted some mirrored queues become unavailable (without slave nodes). The failed queues can be listed using API (management interface, `rabbitmqadmin`), however are not shown in `rabbitmqctl list_queues` output.

## Environment

* RabbitMQ 3.7.5 installed from official RPM, default configuration
* Erlang 20.3.4 installed from RPM provided by RabbitMQ team (rabbitmq/erlang-rpm)
* Red Hat Enterprise Linux 7.5, minimal install, no customizations
* 3 node cluster with ha policy: `{"ha-mode": "exactly", "ha-params": 2, "ha-sync-mode": "automatic"}`
* Cluster partition handling: `cluster_partition_handling = pause_minority`

## Symptoms

* Following message can be seen in logs for failed queues:
  ```
  2018-05-22 15:59:02.294 [warning] <0.1772.0> Mirrored queue 'testq-4' in vhost '/': Stopping all nodes on master shutdown since no synchronised slave is available
  ```
* "State", "Features" is empty, "Read", "Unacked" and "Total" shows `NaN` in management "queues" page
* Failed queue
  ```json
  {
      "arguments": {},
      "auto_delete": false,
      "consumer_details": [],
      "deliveries": [],
      "durable": true,
      "exclusive": false,
      "garbage_collection": {
          "fullsweep_after": -1,
          "max_heap_size": -1,
          "min_bin_vheap_size": -1,
          "min_heap_size": -1,
          "minor_gcs": -1
      },
      "incoming": [],
      "name": "testq-4",
      "node": "rabbit@node-3",
      "vhost": "/"
  }
  ```
* Queue is not listed in `rabbitmqctl list_queues` output
  ```
  # rabbitmqctl list_queues name | grep -E "testq-4$"; echo $?
  1
  ```

## Steps to reproduce

1. Create number of queues (2 vCPU, 4 GB RAM, 3 node cluster takes around
   3000 queues to replicate the issue)
2. Restart any node in cluster using `systemctl restart rabbitmq-server`
3. Check for queues without slave nodes

The script below creates set number of queues, restarts a node and checks for failed queues. The script uses nodes with names `rabbit@node-1`, `rabbit@node-2` and `rabbit@node-3` with passwordless SSH authentication.

```bash
i=1
while [ $i -le 3000 ]
do
  rabbitmqadmin declare queue \
    name="testq-$i" \
    node="rabbit@node-$( expr $i % 3 + 1 )" \
    durable=true > /dev/null
  i=$( expr $i + 1 )
done

failed_queues=0
i=1
while [ $failed_queues -eq 0 ]
do
  # rotate between all three nodes
  node="node-$( expr $i % 3 + 1 )"

  ssh $node "systemctl restart rabbitmq-server"
  sleep 60

  # list queues without slave_nodes
  failed_queues=$( rabbitmqadmin -f tsv list queues name slave_nodes \
    | awk -F "\t" '$2 == "" { print $1 }' | wc -l )

  i=$( expr $i + 1)
done
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The log message is pretty clear: you have no [synchronised mirrors](http://www.rabbitmq.com/ha.html#unsynchronised-mirrors), so none of them can be promoted using the effective (likely default) settings. There is a separate doc section about [specifically that scenario](http://www.rabbitmq.com/ha.html#cluster-shutdown).

**Comment by liudasbk** [comment]
All queues are synchronized before restart (in test scenario they are empty) and in some cases they are correctly promoted. Even if they cannot be promoted, why they are not coming back when note returns to cluster? Actually they become stuck after node comes back to cluster.

**Comment by michaelklishin** [comment]
Because your effective settings tell it to do so. You can choose to promote [unsynchronised mirrors](http://www.rabbitmq.com/ha.html#promoting-unsynchronised-mirrors) if availability is more important than consistency.

There seem to be two separate things going on, the other being unavailable stats (but not necessarily the queue master) for the queues. That's something we will be investigating soon and will file a new specific issue with all the details when we have them.

**Comment by michaelklishin** [comment]
So the script restarts nodes in a tight loop. This means that a node can be forced to shut down before it had a chance to finish promotion for the queue mirrors it hosts. Restarts in a tight loop are not a realistic scenario. 

3.8.0 will feature queue mirroring using a different consensus protocol that will handle cascading restarts as long as the majority of nodes are online (which in this specific test won't be the case).

**Comment by liudasbk** [comment]
There is one minute delay between restarts, but this sometimes fails even on the first restart (especially if VMs are tight on CPU resources). But if queues are empty and synchronized before restart, should each restart end up without any stuck queue? I get that `"ha-promote-on-shutdown": "always"` should resolve the issue, but why there are unsynced queues in the first place if there are no messages and enough time to sync.

The real life scenario is OS patching of RabbitMQ cluster, where each node is restarted and cluster ends up with stuck queues.
