### ISSUE TITLE
Cannot install rabbitmq-server on ubuntu server 16.04.4

### ISSUE THREAD

**Issue by mymtw** [rabbitmq/rabbitmq-server#1614]
Hi, I'm trying to install rabbitmq-server on ubuntu Server 16.04 as:

apt-get install rabbitmq-server -y

during installation I'm getting error:
```
May 30 06:27:26 v systemd[1]: Starting RabbitMQ Messaging Server...
May 30 06:27:27 v rabbitmq[31277]: Waiting for rabbit@v ...
May 30 06:27:27 v rabbitmq[31277]: pid is 31285 ...
May 30 06:27:28 v systemd[1]: rabbitmq-server.service: Main process exited, code=exited, status=140/n/a
May 30 06:27:29 v rabbitmq[31277]: Error: process_not_running
May 30 06:27:29 v systemd[1]: rabbitmq-server.service: Control process exited, code=exited status=2
May 30 06:27:29 v systemd[1]: Failed to start RabbitMQ Messaging Server.
May 30 06:27:29 v systemd[1]: rabbitmq-server.service: Unit entered failed state.
May 30 06:27:29 v systemd[1]: rabbitmq-server.service: Failed with result 'exit-code'.
dpkg: error processing package rabbitmq-server (--configure):
 subprocess installed post-installation script returned error exit status 1
```

```
sudo rabbitmqctl status saying:

Status of node rabbit@v ...
Error: unable to connect to node rabbit@v: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@v]

rabbit@v:
  * connected to epmd (port 4369) on v
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on v
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-32749@v'
- home dir: /var/lib/rabbitmq
- cookie hash: KHRxM68AKD22OGcXr68lyQ==
```

It's a real server for testing our application. If I'm installing rabbitmq in virtualbox also on ubuntu server 16.04 everything ok.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/7Eghbcwqm9U).
