### ISSUE TITLE
SSL connecting from Java client does not work and breaks rabbitmqctl stop

### ISSUE THREAD

**Issue by Alex-Schiegl** [rabbitmq/rabbitmq-server#1618]
* RabbitMQ version
3.7.5
Installed via: 
https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.5/rabbitmq-server-3.7.5-1.el7.noarch.rpm
yum install rabbitmq-server-3.7.5-1.el7.noarch.rpm

* Erlang version
20.3.6-1.el7.centos (the minimal version from rabbitmq repo)

* RabbitMQ server and client application log files
...stopped SSL Listener on [::]:5671 
(this is the last line when the rabbitmqctl stop is broken) 

* Client library version (for all libraries used)
https://mvnrepository.com/artifact/com.rabbitmq/amqp-client/5.2.0
https://mvnrepository.com/artifact/com.rabbitmq/amqp-client/5.1.1 
Error consists on both versions.

* Operating system, version, and patch level
Centos 7 
newest version at 2018/06/02

My goal was to implement a SSL connection (TLSv1.2) between RMQ-Server and one of the java clients mentioned above. 
After going through https://www.rabbitmq.com/ssl.html the server started without complaining. 
But connecting with the java client failed with a SocketTimeoutException : Read Timed Out

So, to verify that I did not have configured something wrong, I went through this guide:
https://www.rabbitmq.com/troubleshooting-ssl.html
All things have worked fine without a problem (only stunnel which I haven't yet tested).
openssl s_client -> OK connected to rmq 
The certificates are OK, tested with openssl (I use no client cert) with s_client and s_server

In the log I see no entry regarding to SSL or port 5671. If i connect to 5672 all works and logs are written, if I connect over SSL to 5671 nothing is ever mentioned in the logs. 
In the management UI:
![unbenannt2](https://user-images.githubusercontent.com/20769238/40877593-dd770ffe-6683-11e8-908b-b19550077c2c.PNG)

However Wireshark capture shows something:
![unbenannt](https://user-images.githubusercontent.com/20769238/40877482-d5e7929c-6681-11e8-882f-7244e24cde64.PNG)

So now comes the interesting part (haha):
To test new params in config file I tried to stop the server using rabbitmqctl stop, but this command never finishes. If I close this window or type again Crtl+C it terminates the execution (of the command, not the server). However, rabbitmq-server does not start any more stating out rabbit is already running at this machine (ps -ef says many rabbitmq processes are running). Using rabbitmqctl stop again does not make things better.
The funny thing is trying to stop the server before I try to connect via SSL on port 5671 succeeds every time I try to stop, however after trying to connect on SSL breaks the shutdown process. Only after a restart of the whole machine, rabbitmq can be started anymore.

So my questions: 
How can I connect via SSL to my rabbitmq, what have I done wrong. Or is this a bug in a release of Erlang/RabbitMQ?
Why is the rabbitmqctl stop broken after SSL connection attempt?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Start with inspecting server logs and posting to the list you [effective configuration(http://www.rabbitmq.com/configure.html#verify-configuration-effective-configuration). Then use the tools mentioned in the [Troubleshooting TLS guide](http://www.rabbitmq.com/troubleshooting-ssl.html).

If [inter-node communication is configured to use TLS](http://www.rabbitmq.com/clustering-ssl.html), CLI tools must be provided certificates and private keys as well or they won't be able to connect. We cannot know if that's the case since the report does not change when TLS is enabled.

**Comment by lukebakken** [comment]
@Alex-Schiegl this is either an issue with your certificates and RabbitMQ configuration or with how you are configuring your Java application to use TLS. If you can provide more details or share your certificates and Java code on the mailing list, that will facilitate us helping out. Thanks.
