### ISSUE TITLE
RabbitMQ client stuck, because server doesn't respond to assertQueue

### ISSUE THREAD

**Issue by blissi** [rabbitmq/rabbitmq-server#1623]
Hallo,
I've got a strange problem:
I am talking to RabbitMQ in a node.js application, using the amqplib-package. Usually the following, stripped down code just works:
```
const rabbit = require('amqplib');

const connection = rabbit.connect('amqp://localhost:5672');
const queue = 'mycommands';

connection
	.then((con) => con.createChannel())
	.then(async (ch) => {
		try {
			console.log("Asserting queue now...");
			await ch.assertQueue(queue);
			console.log("Queue successfully asserted!");
			return ch;
		}
		catch (err) {
			console.error("Failed: " + err);
		}
	});
```

But sometimes the promise of assertQueue is never completed - neither successfully nor rejected - and therefore the code just hangs. I can restart my application over and over again and this bug always remains. When I change the queue name to one that is not present yet in my RabbitMQ-server, the problem still remains, but when I enter the RabbitMQ management console I can see that the new queue has been created. I debugged into amqplib and saw that it still retrieves frames from RabbitMQ, but only Heartbeat-frames. No response to the assertQueue.

When I restart the RabbitMQ service, the problem is gone - therefore I strongly suppose this not to be a problem of amqplib, but of RabbitMQ itself. I am using RabbitMQ 3.6.12 under Windows and amqplib 0.5.2. Has anybody experienced such a problem, too? Do you have an idea what's going on or how this could be fixed?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Sorry but that's no evidence of "a problem in RabbitMQ itself". [A traffic capture](http://www.rabbitmq.com/amqp-wireshark.html) will tell exactly what's send by both peers. Server logs will reveal any channel-level exceptions, e.g. due to [properties of an existing queue not being equivalent to those your app tries to use](http://www.rabbitmq.com/queues.html#property-equivalence) — after which there will be no channel activity and thus no responses even in theory — which is the most likely scenario. I'm not a JavaScript expect but your code lacks error handling as far as I can tell.

This is 200% mailing list material.
