### ISSUE TITLE
Clustered by consul

### ISSUE THREAD

**Issue by panjunDev** [rabbitmq/rabbitmq-server#1630]
hi,i want to join a cluster by consul,but when i start it,i got a error message '2018-06-26 16:05:34.911 [error] <0.233.0> CRASH REPORT Process <0.233.0> with 0 neighbours exited with reason: no function clause matching rabbit_peer_discovery_consul:service_address("undefined", true, "en0", false) line 384 in application_master:init/4 line 134'.
Here is my config file:
**cluster_formation.peer_discovery_backend=rabbit_peer_discovery_consul
cluster_formation.consul.host=10.200.41.166
cluster_formation.consul.port=8500
cluster_formation.consul.scheme=http
cluster_formation.consul.svc=rabbitmq
cluster_formation.consul.svc_addr_auto=true
cluster_formation.consul.svc_addr_nic=en0
cluster_formation.consul.svc_addr_use_nodename=false
cluster_formation.consul.use_longname=false**

Here is my version info:
rabbitmq:3.7.6
Erlang:20.3.8

Here is my enabled plugins:
rabbitmq_auth_backend_http,rabbitmq_management,rabbitmq_mqtt,rabbitmq_peer_discovery_consul

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The plugin [assumes](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/src/rabbit_peer_discovery_consul.erl#L380) that when `svc_addr_nic` is set (the least common option FWIW), `svc_addr_auto` must be `false`. That might be a legitimate mistake carried over from rabbitmq-autocluster but this repo has nothing to do with Consul.

**Comment by michaelklishin** [comment]
According to `rabbitmq-autocluster` code comments, `auto` assumes "use hostname"; a configured static address should be used as given; and otherwise use NIC — but that does not include `auto = true` for an unknown reason. Moved to https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/issues/12.
