### ISSUE TITLE
sudo rabbitmqctl status, "fetch_ldap_pw: neither ldap secret retrieved! pdb_init_ldapsam_common: Failed to retrieve LDAP password from secrets.tdb pdb backend ldapsam:ldap://192.168.1.5 did not correctly init (error was NT_STATUS_NO_MEMORY)"

### ISSUE THREAD

**Issue by rameshAnsr** [rabbitmq/rabbitmq-server#1631]
Hi,
I am getting status of rabbitmqclt as displayed in attached image. I am not able to resolve it. Please suggest me the way to resolve it. 
Folder '/etc/rabbitmq' contains only 'enabled_plugins' file that have '[rabbitmq_management].' text inside.  
I am not able to find rabbitmq 'config' file, please tell me the location of it. 
I am using rabbitmq with django celery. 
<img width="587" alt="rabbitmq status" src="https://user-images.githubusercontent.com/38215331/41908749-b50a3176-7962-11e8-91bc-f3a77521dc1e.png">

Thanks!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
First two hits in Google for "rabbitmq config file" for me:

 * [RabbitMQ configuration guide](https://www.rabbitmq.com/configure.html#configuration-files)
 * [RabbitMQ file and directory location guide](http://www.rabbitmq.com/relocate.html)

While not related:

 * RabbitMQ 3.2.x has been out of support for 3-4 years now
 * Erlang R16B03 has been out of support for about as long and has [major issues that affect RabbitMQ](http://www.rabbitmq.com/which-erlang.html)

Both have improvements and bug fixes related to LDAP. Please [upgrade](https://www.rabbitmq.com/upgrade.html) at the earliest opportunity.
