### ISSUE TITLE
can`t set heartbeat larget than 120s

### ISSUE THREAD

**Issue by whitebluecloud** [rabbitmq/rabbitmq-server#1635]
rabbitmq v3.6

I want to config heartbeat larger than 120s.
I had set heartbeat 3600 but result logs shows like this

log
closing AMQP connection <0.757.0> (ip:46080 -> ip:5672):
missed heartbeats from client, timeout: 120s

then inifinite loop for connect to rabbitmq like this

log
=INFO REPORT==== 5-Jul-2018::01:50:12 ===
connection <0.3141.0> (ip:52418 -> 172.18.0.3:5672): user 'crawl' authenticated and granted access to vhost '/'
=WARNING REPORT==== 5-Jul-2018::01:50:12 ===
closing AMQP connection <0.3141.0> (ip:52418 -> 172.18.0.3:5672, vhost: '/', user: 'crawl'):
client unexpectedly closed TCP connection
=INFO REPORT==== 5-Jul-2018::01:50:12 ===
accepting AMQP connection <0.3154.0> (ip:52420 -> 172.18.0.3:5672)
=INFO REPORT==== 5-Jul-2018::01:50:12 ===
connection <0.3154.0> (ip:52420 -> 172.18.0.3:5672): user 'crawl' authenticated and granted access to vhost '/'
=WARNING REPORT==== 5-Jul-2018::01:50:12 ===
closing AMQP connection <0.3154.0> (ip:52420 -> ip:5672, vhost: '/', user: 'crawl'):
client unexpectedly closed TCP connection

how can I resolve this?

rabbitmq config file
[
        { rabbit, [
                { loopback_users, [ ] },
                { heartbeat, 3600 },
                { tcp_listeners, [ 5672 ] },
                { ssl_listeners, [ ] },
                { default_pass, <<"pass">> },
                { default_user, <<"user">> },
                { hipe_compile, false }
        ] },
        { rabbitmq_management, [ { listener, [
                { port, 15672 },
                { ssl, false }
        ] } ] }
].

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Heartbeats are negotiated between RabbitMQ and clients. It's the clients that decide on the final value, so what client is used is critically important here. RabbitMQ doesn't have any limit on the heartbeat value you configure it to suggest. This is mailing list material.
