### ISSUE TITLE
join the cluster with ram node role fail

### ISSUE THREAD

**Issue by currycan** [rabbitmq/rabbitmq-server#1638]
version 3.7.7
command: rabbitmqctl join_cluster --ram "$RMQHA_MASTER_NODE@$RMQHA_MASTER_HOST"

Error: unable to perform an operation on node 'rabbit@rmqha_node1'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rmqha_node1

but in 3.6.5 I can join the cluster success

**Comment by lukebakken** [comment]
Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

Please post your question or issue to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

* Operating system used, and version
* RabbitMQ version and details on how it was installed
* Erlang version and details on how it was installed
* Plugins enabled and their versions
* Client library and versions used.
* Server logs.
* A code example or terminal transcript that can be used to reproduce.
* **Full** exception stack traces (not a single line message).
* If applicable, `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output). Redirect output to files and attach the files to your message.
* Other relevant information about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html).

Feel free to edit out hostnames and other potentially sensitive information.

If enough details and evidence are provided that demonstrate an issue we'd be happy to file one on GitHub.

Thanks again!
Luke

**Comment by lukebakken** [comment]
@currycan - more than likely your Erlang cookies are not synchronized. Please see this document: https://www.rabbitmq.com/clustering.html#erlang-cookie
