### ISSUE TITLE
ldap-plugin stops working when using erlang-21.0.3

### ISSUE THREAD

**Issue by rafaelma** [rabbitmq/rabbitmq-server#1651]
Hello

After upgrading to rabbitmq-3.7.7 and erlang-21.0.3 the ldap-plugin stops working in our rabbitmq server.

We get these errors and the authentications fails: 
```
".....
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure
LDAP network traffic: Connect: "ldap.server" failed {error,{tls_alert,"handshake failure"}}
......"
```

A downgrade to erlang-20.3.8.3 fixes the problem.

We use these ssl options in /etc/rabbitmq/rabbitmq.conf:

```
ssl_options.certfile 
ssl_options.keyfile
ssl_options.cacertfile 
ssl_options.versions.1 = tlsv1.2
ssl_options.versions.2 = tlsv1.1
ssl_options.honor_cipher_order = true
ssl_options.honor_ecc_order    = true
```

Thanks in advance
Rafael Martinez Guerrero

**Comment by michaelklishin** [comment]
Our team does not maintain Erlang/OTP or its LDAP client or TLS client implementation. Please collect more data using the same approach as [described in the TLS troubleshooting guide](http://www.rabbitmq.com/troubleshooting-ssl.html) and post them to tge erlang-questions, the Erlang user mailing list.

**Comment by michaelklishin** [comment]
According to OTP 21 [release notes](http://erlang.org/download/otp_src_21.0.readme), there are at least 5 potentially breaking changes in the `ssl` app:

 * `OTP-14824`: Drop SSLv2-enabled clients
 * `OTP-14768`: For security reasons no longer support 3-DES cipher suites by default
 * `OTP-14769`: For security reasons RSA-key exchange cipher suites are no longer supported by default
 * `OTP-14789`: The interoperability option to fallback to insecure renegotiation now has to be explicitly turned on.
 * `OTP-14882`: Remove CHACHA20_POLY1305 ciphers form default cipher suite list

So those are the first items I'd recommend investigating (perhaps not the first one since RabbitMQ explicitly disables SSLv2 and SSLv3 for server sockets and I'd be very surprised if client sockets used any of those in practice).

If such questions become recurring our team will have no choice but to investigate but currently there's not enough information to work with (attempt to reproduce) anyway.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
