### ISSUE TITLE
Unable to stop RabbitMQ from listening on port 25672 on all interfaces

### ISSUE THREAD

**Issue by Paradoxis** [rabbitmq/rabbitmq-server#1661]
I'm currently working on an application using celery in combination with rabbitmq, due to security concerns no services that don't require any connection with the internet should only listen on localhost.

After looking around I found [this](https://serverfault.com/questions/235669/how-do-i-make-rabbitmq-listen-only-to-localhost) question which shows how I can make _most_ ports listen only on localhost, however for some reason port `25672` remains open, which I determined to be part of rabbitmq:

    $ nmap -sV -p25672 -T5 <my server>
    
    Starting Nmap 7.50 ( https://nmap.org ) at 2018-08-04 23:54 CEST
    Nmap scan report for <my server> (<my server>)
    Host is up (0.011s latency).
    
    PORT      STATE  SERVICE VERSION
    25672/tcp open   unknown
    
    Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
    Nmap done: 1 IP address (1 host up) scanned in 124.87 seconds

On the server:

    $ lsof -i :25672
    COMMAND   PID     USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
    beam.smp 4513 rabbitmq   12u  IPv4 473675236      0t0  TCP *:25672 (LISTEN)

The `man` entry for rabbitmq does not state how to change this, nor can I find out how to do so online. Could anyone point me in the right direction on how to make it listen on `127.0.0.1` rather than `0.0.0.0`? 

* RabbitMQ version: 3.5.7
* Erlang version: 18.3

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ documentation is fairly extensive and cannot be put into a single man page. There's a dedicated [Networking guide](http://www.rabbitmq.com/networking.html).

Port 25672 is used specifically for [inter-node and CLI tool communication](http://www.rabbitmq.com/clustering.html) and it makes no sense to limit it to localhost (same goes for the epmd port). If you do, you will be able to connect and use CLI tools against that node *only* from localhost which is not what RabbitMQ was designed for.

On an unrelated note, RabbitMQ 3.5.x has been out of any kind of support for a while now. Consider [upgrading](http://www.rabbitmq.com/upgrade.html) since you are [tens of release behind](http://www.rabbitmq.com/changelog.html).

**Comment by michaelklishin** [comment]
Binding epmd to localhost is possible (it makes about as much sense as limiting a DNS server to localhost, however) but our docs do not really cover it since it's a part of the runtime.

There are [pretty decent summaries](https://stackoverflow.com/questions/20316035/rabbitmq-listens-on-all-interfaces) available and [epmd has doc guide](http://erlang.org/doc/man/epmd.html) of its own which has an access restriction section at the bottom.

Please direct all further questions to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users) and [erlang-questions](http://erlang.org/mailman/listinfo/erlang-questions).

**Comment by azerum** [comment]
I don't understand. The [documentation](https://www.rabbitmq.com/networking.html#ports) recommends that

> 25672: used for inter-node and CLI tools communication (Erlang distribution server port) and is allocated from a dynamic range (limited to a single port by default, computed as AMQP port + 20000). **Unless external connections on these ports are really necessary (e.g. the cluster uses [federation](https://www.rabbitmq.com/federation.html) or CLI tools are used on machines outside the subnet), these ports should not be publicly exposed**. See [networking guide](https://www.rabbitmq.com/networking.html) for details.

While by default RabbitMQ listens this port on all interfaces, and it's hard to find options to stop it from doing so
