### ISSUE TITLE
Can it possible to install rabbitmq-server/erlang with powershell script silently on windows

### ISSUE THREAD

**Issue by zpf1989** [rabbitmq/rabbitmq-server#1662]
First,thank you for you great work!I really love rabbitmq,and use it in our business work.
Now I'm trying to develop a tool to deploy rabbitmq on our windows server using powershell.
For some reasons,we don't use docker.
**So how can I find out the parameters the exe(both the erlang and the rabbitmq) can support?**
Such as the install folder,the port,and so on.

**Thank you!**

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I highly respect the folks who maintain the RabbitMQ Docker image but their approach to configuration is terrible. Environment variables are used for everything, party like it's 1984. Do not follow their example. Nearly everything in RabbitMQ is configured [using a config file](http://www.rabbitmq.com/configure.html). For Windows installer-specific things, see [rabbitmq-users archives](https://groups.google.com/forum/#!searchin/rabbitmq-users/Windows$20installer%7Csort:date).

Erlang installer is maintained by the Erlang/OTP team.

**Comment by lukebakken** [comment]
> So how can I find out the parameters the exe(both the erlang and the rabbitmq) can support?

Both the Erlang and RabbitMQ installer are built with NSIS, which only supports a few command-line arguments: http://nsis.sourceforge.net/Docs/Chapter3.html#installerusage
