### ISSUE TITLE
Problem running RabbitMQ commands from Symbolic Link to a different drive

### ISSUE THREAD

**Issue by TiagoJVO** [rabbitmq/rabbitmq-server#1679]
Installation information:
* RabbitMQ version: 3.7.7
* Erlang version: 20.3
* Operating system, version, and patch level: Windows Server 2016 Datacenter

Both Erlang and RabbitMQ are installed with non default installation folders, 'C:\Program Files\MyProgram\Server\thirdparty\Erlang' and 'C:\Program Files\MyProgram\Server\thirdparty\RabbitMQ Server'.
The folder 'C:\Program Files\MyProgram\Server' is a symbolic link to 'D:\MyProgram\Server'. 
Installation ran with no problems, but I can't say the same to configuration.
To configure the Rabbit node, I tried to use 'rabbitmqctl.bat status' to check if the node was up, so I opened a Windows PowerShell terminal and executed the following commands:
* `cd c:\Program Files\MyProgram\Server`
* `& '.\thirdparty\RabbitMQ Server\rabbitmq_server-3.7.7\sbin\rabbitmqctl.cat' status`

and the following error occur:
`escript: exception error: undefined function rabbitmqctl_escript:main/1
   in function escript:run/2 (escript.erl, line 759)
   in call from escript:start/1 (escript.erl, line 277)
   in call from init:start_em/1 (init.erl, line 1085)
   in call from init:do_boot/3 (init.erl, line 793)`

When executing the same command but from any other path besides the junction (inside or outside the junction, or even from the other drive), the command executes successfully. Example:
* `cd c:\Program Files\MyProgram`
* `& '.\Server\thirdparty\RabbitMQ Server\rabbitmq_server-3.7.7\sbin\rabbitmqctl.cat' status`

Note: we had the exact same installation on a Windows Server 2012, and everything worked correctly.

We are available to provide any other information from the environment that you need to reproduce the problem.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
