### ISSUE TITLE
rabbitmq-server {handshake_timeout,handshake} error

### ISSUE THREAD

**Issue by Set4now** [rabbitmq/rabbitmq-server#1683]
Actually this issue is related to sensu client sending msgs to its transport(rabbitmq)
everything was working fine with erlang-18.2-1.el6.x86_64 & rabbitmq-server-3.6.0-1.noarch.

I recently upgraded Erlang and rabbitmq-server with rabbitmq official sites recommendations.

erlang-19.3.6.4-1
rabbitmq-server-3.6.16-1
OS: Centos7
https://www.rabbitmq.com/which-erlang.html

Also i had to upgrade openssl 1.0.1 to 1.0.2 since erlang required lib crypto.so.10(1_0_2).
erlang and rabbitmq-server got installed successfully. The certificates are there in their respective locations in both sensu node and rabbitmq server. Initially I thought may be from the client site its not able to connect. But after following TLS troubleshooting steps , I suspect its something related to rabbitmq node itself.

http://www.rabbitmq.com/troubleshooting-ssl.html

```
cat /etc/rabbitmq/rabbitmq.config
[
 {rabbit, [
  {loopback_users, []},
  {collect_statistics_interval, 540000},
    {cluster_partition_handling, autoheal},
     {ssl_handshake_timeout, 50000},
     {handshake_timeout, 20000},
     {ssl_listeners, [5671]},
     {ssl_options, [{cacertfile,"/etc/rabbitmq/ssl/cacert.pem"},
                    {certfile,"/etc/rabbitmq/ssl/cert.pem"},
                    {keyfile,"/etc/rabbitmq/ssl/key.pem"},
                    {versions, ['tlsv1.2']},
                    {verify,verify_peer},
                    {fail_if_no_peer_cert,true}]}
     ]},
     {rabbitmq_management,  [ {http_log_dir,  "/Monitoring/rabbit-mgmt"},
        {rates_mode, none}] }
].
```

```
Erlang/OTP 19 [erts-8.3.5.3] [source] [64-bit] [smp:56:56] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3.5.3  (abort with ^G)
1> ssl:versions().
[{ssl_app,"8.1.3.1"},
 {supported,['tlsv1.2','tlsv1.1',tlsv1]},
 {available,['tlsv1.2','tlsv1.1',tlsv1,sslv3]}]
2>
```

on the rabbitmq node

with reference to Attempt TLS Connection to Broker section from 
http://www.rabbitmq.com/troubleshooting-ssl.html

However 
In one terminal window execute the following command:

```
openssl s_server -accept 8443 -cert server/cert.pem -key server/key.pem \
  -CAfile testca/cacert.pem
```

In another terminal window execute

```
openssl s_client -connect localhost:8443 -cert client/cert.pem -key client/key.pem \
  -CAfile testca/cacert.pem
```

The above two works fine.. can see terminal attached..verified status ok.. messages on both sides.

```
openssl s_client -connect localhost:5671 -cert client/cert.pem -key client/key.pem   -CAfile sensu_ca/cacert.pem

cceptable client certificate CA names
/CN=SensuCA
Client Certificate Types: ECDSA sign, RSA sign, DSA sign
Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
---
SSL handshake has read 1680 bytes and written 2343 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: 6513825F78CB02BC0E92E0956C4E0F1FC28DCCC75A1348DC6FE2EFEBC3F00413
    Session-ID-ctx:
    Master-Key: 3E2E3657B800523AF7547866D184C2F538DB25D6456C1DE83488AA0FAA9DC1B30EEC60B7B3482705D8E91E6D69C316F8
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1535279348
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed
```

Now on the rabbitmq server logs

```
=INFO REPORT==== 26-Aug-2018::03:02:17 ===
accepting AMQP connection <0.574.0> ([::1]:51836 -> [::1]:5671)

=ERROR REPORT==== 26-Aug-2018::03:02:17 ===
closing AMQP connection <0.574.0> ([::1]:51836 -> [::1]:5671):
**{handshake_timeout,handshake}**

=INFO REPORT==== 26-Aug-2018::03:29:28 ===
accepting AMQP connection <0.602.0> ([::1]:51894 -> [::1]:5671)

=ERROR REPORT==== 26-Aug-2018::03:29:28 ===
closing AMQP connection <0.602.0> ([::1]:51894 -> [::1]:5671):
**{handshake_timeout,handshake}**
```

**Comment by lukebakken** [comment]
Please post this to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users), as there is no evidence of a RabbitMQ bug nor do you provide a way to reproduce what you're seeing.

When providing the output of commands, if the output is more than a line or two, please attach the output in a text file, not pasted like you have done here (which is very difficult to read).

You should also provide the output (in a file!) of the `rabbitmqctl environment` and `rabbitmqctl report` commands.

Finally, `handshake_timeout,handshake` is evidence that your sensu client is not doing the TLS negotiation correctly. Since you have upgraded Erlang and OpenSSL, there are probably differences in how TLS negotiation is done that need to be taken into account with sensu. You should try the following:

* Configure sensu to connect to the non-TLS RabbitMQ port (`5672`) and verify that works. Be sure to disable TLS in sensu.
* If that works, re-enable TLS in sensu and increase debug output as much as possible, hopefully you will see something useful logged.
* Remove or comment-out the following three TLS options from RabbitMQ to see if it makes a difference. Restart RMQ and re-try connecting from sensu:

```
    {versions, ['tlsv1.2']},
    {verify,verify_peer},
    {fail_if_no_peer_cert,true}
```

Again, please follow up on the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users), thanks.
