### ISSUE TITLE
Proposal: support header exchange authorization

### ISSUE THREAD

**Issue by TKul6** [rabbitmq/rabbitmq-server#1684]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version:  3.7.5

* Erlang version: 20.3

Hi,
I apply the RabbitMQ server in my solution.
I started configure the server when I realize I have an issue:

Currently (just to test the server meets my needs) I have server with one queue.
The server publishes messages and put in the message's header a source Id.

The consumer consumes messages from the queue using the **Header Exchange**  to get only the messages from the sources I care about (has sufficient privileges).

an It works great, perfect.

The only problem is when the subscriber connects to the queue with a specific exchange, I need to know the header he uses in order to know if he authorize to get messages of that source.

According to the documentation the authorization mechanism only authorize user by the exchange name, (doesn't care about the header).
I wanted to know if there are any future plans to support this feature?

Thanks,

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Unlikely. [Topic authorization](http://www.rabbitmq.com/access-control.html) and [Exchange-to-exchange bindings](http://www.rabbitmq.com/e2e.html) should provide enough to simulate a headers exchange using a topic naming convention and with one more authorisation layer.
