### ISSUE TITLE
Consider queue attributes for multi-consumer sequential consumption

### ISSUE THREAD

**Issue by theagechen** [rabbitmq/rabbitmq-server#1687]
It is hoped that the queue can have an attribute that can ensure that multiple consumers consume in order for the same queue. Consumers can take messages in turn instead of simultaneously, ensuring that another consumer can get the next message after the previous message ack. In this way, in the same business service cluster mode, there are 3 advantages:
1. Guarantee the order of the messages
2. Stress can be shared across multiple consumer nodes (of course this service is not just about consuming a queue, but also doing other things, such as accepting http requests)
3. I can stop a service node to upgrade the application or guarantee the disaster tolerance of the business.

At present, I can only use the exclusive attribute to complete this business scenario, which can guarantee the order of messages and stop a certain consumer. Another consumer will take over and remain exclusive, but the business pressure is always in a consumer node. .

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Items 1 and 2 contradict each other. If load is "shared" (distributed between) N consumers then by definition they are consuming and ordering between deliveries to those consumers is in part their responsibility.

For better or worse all 4 protocols RabbitMQ supports today use nearly identical models for delivery acknowledgements. Specific examples of what you have in mind are welcome on the mailing list.

Currently our team focuses on things other than extending protocols.
