### ISSUE TITLE
how can i sync queue form a RMQ Server with dynamic IP

### ISSUE THREAD

**Issue by alues** [rabbitmq/rabbitmq-server#1692]
Here is the solution I use right now, consumer consume the msg from Server A over `WAN`, counsumer can publish msg fail from time to time due to unstable `WAN` connection
![unname](https://user-images.githubusercontent.com/23065608/44948415-8f063c00-ae4f-11e8-97da-a12d16ac34f9.png)

I would like to use RMQ Server B as a agent to handle msg's delivering. 
It performed well for deliver msg from RMQ Server A to RMQ Server B, 
but i can't setup federate queue from RMQ Server B to RMQ Server A due to Server B have no *`static IP`*. 
![server control](https://user-images.githubusercontent.com/23065608/44948417-9299c300-ae4f-11e8-9ce6-a4350ef30fbf.png)
how can i solve the problem?

**Comment by alues** [comment]
@michaelklishin that will nice feature for federate plugin to support sync msg from downstream to upstream?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There has been a solution for connections to potentially changing IP addresses for a few decades now: hostnames and DNS A/AAAA records.

**Comment by alues** [comment]
Thank you for your time.
DNS A/AAAA records has a large delay. cause to about several minutes unusable time.

**Comment by michaelklishin** [comment]
@alues it depends on the TTL for those records used on your network. It can be under a minute. We are not interested in reinventing parts of DNS in RabbitMQ, sorry.
