### ISSUE TITLE
How to delete messages from an RabbitMQ queue if it's delivered to destination (Cloud) is success?

### ISSUE THREAD

**Issue by isharehappycode** [rabbitmq/rabbitmq-server#1708]
Want help in design decisions.

I have few devices on field, which will be sending messages to cloud (Azure/AWS). I am planning to use RabbitMQ and once message is successfully delivered to the cloud I would like to delete it from the queue. Sometime internet will be down and messages will not reach the cloud. Such messages still stays on Queue and system needs to **retry to send.**

Does RabbitMQ support this requirement by default? or do I have to write custom code to achieve the same?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There are two ways to delete a message: consume and [acknowledge](http://www.rabbitmq.com/confirms.html) it or purge the queue. You can also use a data store or a coordination service (ZooKeeper, etcd) to mark a message as "deleted" and consumers then can use this information to acknowledge them without processing.
