### ISSUE TITLE
Release not signed.

### ISSUE THREAD

**Issue by bjoernHeneka** [rabbitmq/rabbitmq-server#1716]
Hey.. hope it's the right place here.
I have the following problem at the momen.

I'm using Ubuntu 18.04 and try to instal rabbit.
When adding the sources i get the following error:

```
E: The repository 'http://dl.bintray.com/rabbitmq/debian bionic Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
ubuntu@ip-10-2-101-173:~$ sudo vi /etc/apt/sources.list.d/bintray.erlang.list
`
``

apt-key list shows up the following
```
apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2016-05-17 [SC]
      0A9A F211 5F46 87BD 2980  3A20 6B73 A36E 6026 DFCA
uid           [ unknown] RabbitMQ Release Signing Key <info@rabbitmq.com>
sub   rsa4096 2016-05-17 [E]

pub   dsa1024 2007-07-06 [SC]
      F783 72A0 6FF5 0C80 464F  C1B4 F7B8 CEA6 056E 8E56
uid           [ unknown] RabbitMQ Release Signing Key <info@rabbitmq.com>
sub   elg2048 2007-07-06 [E]
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
@bjoernHeneka you need to remove the 2007 signing key and import [the new one](http://www.rabbitmq.com/download.html#release-signing-key). This is not a commonly reported issue and therefore I highly doubt the problem is with packages.

[Package Cloud](https://packagecloud.io/rabbitmq) signs packages published to it with their own key.

**Comment by bjoernHeneka** [comment]
Hey @michaelklishin I'm building with packer and AWS. So i have a plain ubuntu installation

**Comment by michaelklishin** [comment]
The repo is [signed again](https://dl.bintray.com/rabbitmq/debian/dists/xenial/) now.
