### ISSUE TITLE
Wrong connection

### ISSUE THREAD

**Issue by dersar00** [rabbitmq/rabbitmq-server#1725]
Hello guys!
I have a virtual vagrant machine, I'm deploying my app using script.
After starting machine and starting using my app, when I try to send message from my first worker to another, I don't get them, but the main problem is that I don't get only few first message, sometimes it can be 3-4, sometimes 10+ message, after few message everything works well. Using tracelog I finded difference between those incidents(below).
![image](https://user-images.githubusercontent.com/17855733/46481951-28cd5a00-c7fd-11e8-9129-d49a74a21527.png)

Difference is in connection line, message coming from one place with same message, without any changes between those messages. Any idea how I can fix it?
![image](https://user-images.githubusercontent.com/17855733/46481993-45699200-c7fd-11e8-9805-afa70a11aaba.png)

My app using elixir, fragment of code what I used for send messages below.
```
{:ok, connection} = AMQP.Connection.open port: 5672, username: "username", password: "password"
{:ok, channel} = AMQP.Channel.open(connection)
AMQP.Queue.declare(channel, routing_key, durable: true)
AMQP.Basic.publish(channel, "", routing_key, message)
AMQP.Exchange.declare(channel, "backend", :topic, durable: true)
IO.puts " [x] Sent message to queue #{routing_key}"
```

**Comment by lukebakken** [comment]
Hi Valentin,

Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

Please post your question or issue to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used.
 * Server logs.
 * A code example or terminal transcript that can be used to reproduce.
 * **Full** exception stack traces (not a single line message).
 * If applicable, `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output). Redirect output to files and attach the files to your message.
 * Other relevant information about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html).

Feel free to edit out hostnames and other potentially sensitive information.

If enough details and evidence are provided that demonstrate an issue we'd be happy to file one on GitHub.

Thanks again!
Luke
