### ISSUE TITLE
maximumRedeliveries and redeliveryDelay

### ISSUE THREAD

**Issue by fangcaixiang** [rabbitmq/rabbitmq-server#1746]
can rabbitmq set maximumRedeliveries and redeliveryDelay like ActiveMQ?

**Comment by fangcaixiang** [comment]
1

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is no support for either of those in the core in 3.7.x. 3.8 is going to include a redelivery counter for quorum queues. There's also a delaying exchange type (not a direct equivalent but somewhat close).
