### ISSUE TITLE
RabbitMQ for Disaster Recovery Site

### ISSUE THREAD

**Issue by phucle2411** [rabbitmq/rabbitmq-server#1754]
Hi all.
I have 2 sites (one master, one DR site), on each, I set up a rabbitMQ cluster (3 nodes). 
My question: is there any way to sync  messages of all queues  between 2 rabbitMQ cluster real time?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This has been discussed on the mailing list multiple times. Keywords: hot standby, [topology export and import](http://www.rabbitmq.com/backup.html#rabbitmq-definitions), exchange federation, message TTL.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/4Hvew_F-D2o)
