### ISSUE TITLE
Snap support(Feature Request)

### ISSUE THREAD

**Issue by Mikerr1111** [rabbitmq/rabbitmq-server#1759]
I was thinking the setup and install process for Ubuntu and other Linux distros could be improved by having a [Snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I implemented the snap?

[Creating a Snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Create snaps from your preferred programming language.](https://docs.snapcraft.io/build-snaps/languages)

[Build and Test snap](https://snapcraft.io/build)

[Linux distros with snap support](https://docs.snapcraft.io/core/install)
![snap](https://user-images.githubusercontent.com/18353476/43989596-ec564800-9d01-11e8-89e6-8e0af1434f62.png)

**Comment by michaelklishin** [comment]
We certainly wouldn't mind community contributions. Thank you for considering one 👍 My first question around new package types is always "who is going to maintain this going forward?" since our team is small.

This is something that's best discussed on the mailing list. You might find potential contributors there and this is where new projects are best announced.

If there's enough interest over time it is something that can be added to our release pipeline.
