### ISSUE TITLE
Message are lost on connection failure between client and rabbitmq server.

### ISSUE THREAD

**Issue by Hariom0000** [rabbitmq/rabbitmq-server#1773]
My query is regarding rabbitmq confirm functionality. As i understood when a client send a message on a rabbitmq queue and It confirm the client  with an acknowledgment that message is received at rabbitmq queue.

But i'm facing a issue that whenever a client sends 1000 messages toward rabbit server and in between the connection between client and rabbit server got break. I saw confirm channel show 798 messages are acknowledged and non-confirm channel show 202 messages are not acknowledged. And the queue is showing 800 messages on it.

So it is some discrepancy that acknowledgement receives for messages on confirm channel are 798 but  in queue are 800. I faced this issue many time.

Please help me to find out the possible cause of message discrepancy.

Note: There is no consumer for this queue.
Please revert back for any help from my end
Thanks in advanced.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There's a window of time in which a publisher confirm can be lost even though the message was successfully routed. Publishers must treat all unacknowledged messages as requiring republishing. That means there's a window of time and certain failure scenarios which can produce duplicates. If it's important in a given system consumers should be developed with that in mind.

A "confirm for confirms" mechanism or a full blown consensus algorithm between clients and nodes would help address that but it would also introduce significant overhead and FWIW the messaging protocols we implement today use a basic "publish and confirm" algorithm.
