### ISSUE TITLE
I can't seem to get x-message-ttl to work in golang i've already installed the plugin

### ISSUE THREAD

**Issue by unisqu** [rabbitmq/rabbitmq-server#1786]
I'm not sure if the installed delay schedule for rabbitmq is being used (i've installed the plugin but not sure how to check if it's running)

https://pastebin.com/u9yk6HGH

the code is above but i'm getting
2018/12/02 16:03:18 Failed to declare a queue: table field "x-message-ttl" value %!t(uint16=500) not supported

how do i get it to work in golang? pls help. thx

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The [plugins guide](http://www.rabbitmq.com/plugins.html) explains how to check plugin status.

According to the message (it's not clear where it is coming from but looks like it's the client), the header value cannot be of type uint16. The plugin supports several [numeric types defined in the protocol](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/src/rabbit_delayed_message_utils.erl#L24). I'd try a different numerical Go type first.
