### ISSUE TITLE
Excessive progress report logging on Windows in 3.5.x

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#180]
See [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/-hc9CLN6gwA). Note that SASL logger configuration seems to be identical to that I have on OS X but progress reports are still logger.

**Comment by michaelklishin** [comment]
The issue seems to be with [argument ordering](https://github.com/rabbitmq/rabbitmq-server/blob/stable/scripts/rabbitmq-server.bat#L163-167).

**Comment by scratch-net** [comment]
Any quick workaround for this? Or better wait for 3.5.4?

**Comment by michaelklishin** [comment]
Try 3.5.4 RC1?

**Comment by scratch-net** [comment]
Ok, will try. I just don't see commits referring #180

**Comment by michaelklishin** [comment]
One of the potential fixes is https://github.com/rabbitmq/rabbitmq-server/commit/0802e872c22aabfe8c65aa30beb7f2adec359d52. We'll check one more time before `.3.5.4` final.

**Comment by scratch-net** [comment]
Yep, seems to be working after I fixed #222

**Comment by bassrob** [comment]
Hi guys,

Following on from @scratch-net's comment, rather than having to wait for 3.5.4 or rolling a release candidate into a production environment, is there a config tweak I can make to reduce the amount of logging to the -sasl.log file?

I've made the following modification which completely prevents the -sasl.log file from being created but A) it'd be useful to see errors and B) the .log file starts to log out a badarg error (see below):

FROM:  -rabbit sasl_error_logger {file,\""!SASL_LOGS:\=/!"\"} ^
TO:  -rabbit sasl_error_logger false ^

Error in .log file:

=ERROR REPORT==== 17-Jul-2015::10:37:27 ===
** Generic server rabbit_mgmt_external_stats terminating 
** Last message in was emit_update
** When Server state == {state,8192,
                               [{{io_read,bytes},0},
                                {{io_read,count},0},
                                {{io_read,time},0},
                                {{io_reopen,count},0},
                                {{io_seek,count},0},
                                {{io_seek,time},0},
                                {{io_sync,count},0},
                                {{io_sync,time},0},
                                {{io_write,bytes},0},
                                {{io_write,count},0},
                                {{io_write,time},0},
                                {{mnesia_disk_tx,count},5},
                                {{mnesia_ram_tx,count},45},
                                {{msg_store_read,count},0},
                                {{msg_store_write,count},0},
                                {{queue_index_journal_write,count},0},
                                {{queue_index_read,count},0},
                                {{queue_index_write,count},0}],
                               undefined,
                               {set,0,16,16,8,80,48,
                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]},
                                    {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]}}}}
** Reason for termination == 
** {badarg,[{erlang,list_to_binary,[undefined],[]},
            {rabbit_mgmt_external_stats,log_location,1,[]},
            {rabbit_mgmt_external_stats,'-infos/2-lc$^0/1-0-',2,[]},
            {rabbit_mgmt_external_stats,'-infos/2-lc$^0/1-0-',2,[]},
            {rabbit_mgmt_external_stats,emit_update,1,[]},
            {rabbit_mgmt_external_stats,handle_info,2,[]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
            {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]}]}


Cheers,

Rob

**Comment by michaelklishin** [comment]
@bassrob you need to make the same change as in https://github.com/rabbitmq/rabbitmq-server/commit/0802e872c22aabfe8c65aa30beb7f2adec359d52 and [re-apply config changes](http://www.rabbitmq.com/configure.html) before restarting the service.

**Comment by bassrob** [comment]
Hmmm, that's strange, I made that change a little earlier but must have missed something before, it all looks good now!  Thanks Michael.
