### ISSUE TITLE
Memory cannot be freed

### ISSUE THREAD

**Issue by dongbo0737** [rabbitmq/rabbitmq-server#1804]
rabbitmq 3.7.4
Erlang 20.2.4

Unused memory is located at allocated_unused：
![image](https://user-images.githubusercontent.com/16332526/50210367-df7ab880-03b0-11e9-8aa4-66fe5d909086.png)

Trigger memory alarm
![image](https://user-images.githubusercontent.com/16332526/50210416-0638ef00-03b1-11e9-8a32-d4f3abb6e871.png)

How do I recycle memory?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This questions can be found in the mailing list archives, e.g. [this thread](https://groups.google.com/d/msg/rabbitmq-users/pFZaG492X7M/tI-FvUi6BAAJ). You have two options (that can be combined):

 * Use different runtime allocator flags (RabbitMQ does not allocate memory directly)
 * Try re-enabling background GC (won't make a different for all workloads)
