### ISSUE TITLE
rabbitmqctl cannot run when rabbitmq installed in dir other than /usr/local 

### ISSUE THREAD

**Issue by liangsix** [rabbitmq/rabbitmq-server#1810]
* RabbitMQ version  : 3.7.9
* Erlang version: 21.2
* Operating system: centos7

 I installed the rabbitmq server in /data/server/rabbitmq  dir,  when I run `./sbin/rabbitmqctl`, it raise an error:
`
escript: exception error: undefined function rabbitmqctl_escript:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
`
but when rabbitmq sever installed in `/usr/local/rabbitmq`,  `./sbin/rabbitmqctl` works.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Generic binary builds should be used when running from arbitrary installation locations. Package-provisioned versions can [override](http://www.rabbitmq.com/configure.html) [default paths](http://www.rabbitmq.com/relocate.html), including runtime code path (where the modules are loaded from).

FWIW I use binary builds at non-standard locations many times a day and do not run into this.
