### ISSUE TITLE
suggestion:Is there a plan to support timing delivery ?

### ISSUE THREAD

**Issue by athinboy** [rabbitmq/rabbitmq-server#1811]
As title.

**Comment by wjdavis5** [comment]
Ask your question here:
https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid I don't know what "timing delivery" means to you. Consider starting a mailing list thread if there's something you'd like to see. There's already a [delayed publishing plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/), for example.

**Comment by athinboy** [comment]
@michaelklishin 
not delay delivery  . delivery on specific time ,    定时消息.

sorry ,I can not access google .

https://help.aliyun.com/document_detail/43349.html
http://rocketmq.apache.org/docs/schedule-example/

**Comment by michaelklishin** [comment]
This is not something on the immediate roadmap but can be achieved with a plugin.
There’s interest in making the delayed exchange plugin distributed, this may be just
another feature eventually offered by it. There is no ETA and this is not a delivery promise.
