### ISSUE TITLE
Downtime while shutting down node that is master of many queues

### ISSUE THREAD

**Issue by joaonuno** [rabbitmq/rabbitmq-server#1847]
Queue master node migration time seems to be proportional to the number of queues which causes long downtime when doing a **planned rolling restart** of RMQ nodes in the cluster.

For more context, please see this post in the mailing list: https://groups.google.com/forum/#!topic/rabbitmq-users/0OVgPKKY1jU

To make it easier to understand, I created a [video (with sound)](https://github.com/rabbitmq/rabbitmq-server/files/2795765/rmq-failover-latency.mp4.gz) illustrating this problem.

We're not able to confirm this, but it seems that, looking at the logs, the client connection is being closed before assuring that the other nodes becomes the master of all queues.

Let me know WDYT, is this a bug or is there a better way to restart RMQ nodes without downtime?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
A node that's shutting down will close all of its connections. This is in no way coordinated with queue replica promotion and should not be. Queue replica promotion should in no way depend on client connections. In fact, because of properties such as exclusive and auto-delete, closing connections first makes more sense because some queues may be imminent for deletion (why would anyone use auto-delete mirrored queues is a separate discussion).

**Comment by joaonuno** [comment]
> This is in no way coordinated with queue replica promotion and should not be. Queue replica promotion should in no way depend on client connections.

I'm not implying that it should be or how it should behave. I'm just wondering if taking a node down when all its queues are replicated should cause such a noticeable timeout and proportional to the number of queues. Is it a bug or expected behavior?

> In fact, because of properties such as exclusive and auto-delete, closing connections first makes more sense because some queues may be imminent for deletion

The queues in this test are not exclusive nor auto-delete.

**Comment by michaelklishin** [comment]
I responded in https://groups.google.com/forum/#!topic/rabbitmq-users/0OVgPKKY1jU.
