### ISSUE TITLE
RabbitMQ Memory Dealloaction issue after consuming all the messages

### ISSUE THREAD

**Issue by Niro23** [rabbitmq/rabbitmq-server#1865]
I am working on a POC project to migrate from EMS to RabbitMQ. For that I have done following steps,

Created a 4 - node cluster
 72 mirrored(HA) and durable queues
 Single "direct" exchange that routes a messages to several queues(1 to 8 queues) depending on the routing key.
Published 1 Million persistent messages (~20KB each)
 Nodes' High Memory water mark : 11GB
RabbitMQ Version :"3.6.9"
Erlang_version: 19.0.4

Status Before Publishing 
Memory usage of each node : ~80MB

Status After Publishing
Memory usage of each node : ~5GB (all the messages were not kept in memory, I was able to witness 2/3rd of the messages were in disk)

I wanted to test RabbitMQ memory deallocation performance. 

I consumed all the messages using Java programs. After consuming 0 messages were in the cluster. 

But my problem is the memory usage never reached the original level even after all the messages are consumed.

In each node's memory usage was : ~2GB (Originally it was 80MB), 
The status was same even after 10hours. 

Please see memory status below. I don't really understand why RabbitMQ behaving like this. Is it an issue with GC ?
As soon as restart the node it went to original memory 
How do I fix this issue? 

{memory,
     [{total,2125937048},
      {connection_readers,0},
      {connection_writers,0},
      {connection_channels,0},
      {connection_other,2688},
      {queue_procs,1676712696},
      {queue_slave_procs,0},
      {plugins,9036232},
      {other_proc,25693816},
      {mnesia,648920},
      {metrics,253224},
      {mgmt_db,897520},
      {msg_index,1152952},
      {other_ets,3199392},
      {binary,375125672},
      {code,24543516},
      {atom,1033401},
      {other_system,7887555}]},

Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Please post this and future questions to the mailing list, as GitHub issue template suggests. 3.6.9 is 18 releases behind and has been out of support since May 2018. Very importantly here, starting with 3.6.11 [nodes use a different memory reporting](https://groups.google.com/forum/#!topic/rabbitmq-users/TVZt45O3WzU) algorithm that includes memory allocated but currently unused (possibly due to memory fragmentation) by the runtime. Memory fragmentation is a pretty involved and workloads-specific topic, see e.g. [one strategy to reduce it](https://groups.google.com/d/msg/rabbitmq-users/124TXWN9kk0/0s6fUPozAwAJ).

We have no code or workload details but according to the memory breakdown, 78% of memory is used by queue master processes, which suggests they kept a non-trivial number of messages in RAM previously and in current state there are no triggers for runtime GC. Modern versions force a minor collection every 1000 messages by default.

You can either publish messages as persistent and use durable queues only to make them go to disk or use [lazy queues](https://www.rabbitmq.com/lazy-queues.html) that sent all messages to disk as aggressively as possible. In environments with mostly idle queues [re-enabling background GC](https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example#L470)

Please conduct all future tests with a supported, recently released version such as 3.7.11, which will require [upgrading Erlang from 19.0](https://www.rabbitmq.com/which-erlang.html) as well.
