### ISSUE TITLE
i install windows get Distribution failed

### ISSUE THREAD

**Issue by quan01994** [rabbitmq/rabbitmq-server#1880]
![image](https://user-images.githubusercontent.com/20533465/52697673-e2f38000-2fac-11e9-9b9d-3ae0cdb04520.png)

````
Distribution failed: {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}}, 
{:child, :undefined, :net_sup_dynamic, {:erl_distribution, :start_link, [[:"rabbitmqcli-13672-rabbit@QuanYuqiu", :shortnames, 15000], false]}, 
:permanent, 1000, :supervisor, [:erl_distribution]}}
````
rabbitmq-server-3.7.11
otp_win64_21.2 
windows 10 1809 

Everything is installed by default
How can I solve this problem?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
