### ISSUE TITLE
RabbitMQ - Socket Exception -Broken Pipe and Connection timed out (Write failed)

### ISSUE THREAD

**Issue by Nandha13** [rabbitmq/rabbitmq-server#1897]
Getting the below exceptions when our code in our endpoints trying to communicate with RMQ . We are using cachingConnectionFactory and TopicExchange.

`error=org.springframework.amqp.AmqpIOException: java.net.SocketException: Connection timed out (Write failed) at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:63) at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:110) at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:968) at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:945) at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:470) at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:535) at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:522)

error=org.springframework.amqp.AmqpIOException: java.net.SocketException: Broken pipe (Write failed) at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:63) at org.springframework.amqp.rabbit.connection.SimpleConnection.createChannel(SimpleConnection.java:49) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createBareChannel(CachingConnectionFactory.java:684) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.access$300(CachingConnectionFactory.java:673) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:369) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:345) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:315) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:308) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$900(CachingConnectionFactory.java:74) at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:689) at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createChannel(ConnectionFactoryUtils.java:85) at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:134) at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:67)

`

**Comment by lukebakken** [comment]
When you click "New Issue" in this repository, the following text is shown. Please, rather than ignoring it, read it carefully and follow the instructions given. Thank you.

-----

Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
`java.net.SocketException: Connection timed out (Write failed)` is pretty descriptive. See [Troubleshooting Networking](https://www.rabbitmq.com/troubleshooting-networking.html).
