### ISSUE TITLE
general question about connections / channels : 

### ISSUE THREAD

**Issue by fas3r** [rabbitmq/rabbitmq-server#1908]
Hello, 

Following this [article] (https://www.cloudamqp.com/blog/2018-01-19-part4-rabbitmq-13-common-errors.html) we can read the following thing : 

> Don’t open and close connections or channels repeatedly
Have long lived connections if possible, and use channels for each task. The handshake process for an AMQP connection is quite complex and requires at least 7 TCP packets (more if TLS is used). Channels can be opened and closed more frequently if needed. Even channels should be long-lived if possible, e.g., reuse the same channel per thread for publishing. Don’t open a channel each time you are publishing. If you can't have long lived connections, then make sure to gracefully close the connection Best practice is to reuse connections and multiplex a connection between threads with channels.
>
>AMQP connections: 7 TCP packages
AMQP channel: 2 TCP packages
AMQP publish: 1 TCP package (more for larger messages)
AMQP close channel: 2 TCP packages
AMQP close connection: 2 TCP packages
Total 14-19 packages (+ Acks)

and _(most important)_ 

>Don’t share channels between threads
You should make sure that you don’t share channels between threads as most clients don’t make channels thread-safe (because it would have a serious negative impact on performance).

I'm just not sure to understand, does it mean that if I use for example nodeJs with some HA solution to scale across the CPUs of my instance, I  should create my connections on the master and share it across all the workers and open channels on the workers and never closed it ( at least not open/close each time that's needed ) ?

Thanks by advance.

fas3r.

**Comment by lukebakken** [comment]
I'm re-posting the text that appears when "New Issue" is clicked -

----

Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
With Node.js the common way of achieving concurrency is `fork(2)`, which *requires* that a new connection is opened from each child process because of how file descriptors are [not] inherited.
In any case, there is nothing wrong with using more than one connection per process, e.g. one to publish and one to consume is a common strategy to avoid consumer connections being [blocked](http://www.rabbitmq.com/alarms.html).

The rule of thumb is "when in doubt, open a new channel, not a new connection". Channels are also not free and apps should not open a lot of them but what "a lot" means is system-specific. Modern RabbitMQ versions have a hard limit of `2047` (plus one special channel used for protocol negotiation and error reporting) channels per connection by default, and even that is very high in our opinion. 1-10 channel should be enough for most applications.

Relevant doc guides: [Connections](https://www.rabbitmq.com/connections.html), [Channels](https://www.rabbitmq.com/channels.html).
