### ISSUE TITLE
Large memory usage lead to node termination

### ISSUE THREAD

**Issue by shendongsd** [rabbitmq/rabbitmq-server#2003]
Hello,
 The RabbitMQ's log:      
       
=WARNING REPORT==== 6-May-2019::03:41:49 ===                             
memory resource limit alarm cleared across the cluster                
=WARNING REPORT==== 6-May-2019::03:56:36 ===
memory resource limit alarm set on node rabbit@ctl001.
**********************************************************
*** Publishers will be blocked until this alarm clears ***
**********************************************************
=WARNING REPORT==== 6-May-2019::03:56:42 ===
memory resource limit alarm cleared on node rabbit@ctl001
=WARNING REPORT==== 6-May-2019::03:56:42 ===
memory resource limit alarm cleared across the cluster
=INFO REPORT==== 6-May-2019::03:56:47 ===
rabbit on node rabbit@ctl001 down
=INFO REPORT==== 6-May-2019::03:56:47 ===
node rabbit@ctl001 down: connection_closed

Why large memory usage lead to node termination?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Most operating systems have an [out of memory killer](https://en.wikipedia.org/wiki/Out_of_memory) (watchdog subsystem) that kills processes that use most memory when the system is under memory pressure.

[Reasoning About Memory Usage](https://www.rabbitmq.com/memory-use.html) and [RabbitMQ monitoring](https://www.rabbitmq.com/monitoring.html) guides explain how to collect relevant information. At least on Linux on OOM killer events are logged ([one example](https://unix.stackexchange.com/questions/354319/how-to-make-oom-killer-log-into-var-log-messages-when-it-kills-any-process), [two](https://serverfault.com/questions/652362/understanding-oom-killer-logs)) to one of the kernel logs.
