### ISSUE TITLE
I have special needs. Is there a way to reinitialize the "x-max-priority" default?

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/rabbitmq-server#2008]
I have special needs. Is there a way to reinitialize the "x-max-priority" default?
@michaelklishin Help me, thank you

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
@501956430 we have repeatedly asked you to direct questions to the mailing list. Please cooperate.

Queue properties, including optional arguments, are [immutable unless controlled by a policy](https://www.rabbitmq.com/queues.html#properties). Max priority of a priority [cannot be changed](https://www.rabbitmq.com/priority.html#using-policies). You have to delete the queue and redeclare it.
