### ISSUE TITLE
Root vhost encoding

### ISSUE THREAD

**Issue by tarastriska** [rabbitmq/rabbitmq-server#2010]
I use rabbitmq 3.7.14 web interface.
There are 2 vhosts:

1. Root (/)
2. Custom

There are exchanges/queues/etc. for both vhosts.
They are shown well in list views. However once I wanna click on any object to get details it fails for any resource from root vhost and works fine for custom.
It encodes URL with /%2F/ for root and always return 404 for get.
Does it mean that I have to use specific vhost instead of root?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
