### ISSUE TITLE
Is it possible to only synchronize metadata in the mirrored?

### ISSUE THREAD

**Issue by andChow** [rabbitmq/rabbitmq-server#2020]
If the cluster is not configured with mirrored, the metadata cannot be synchronized to other nodes in the cluster. If the cluster is configured with mirrored, the mirrored not only synchronizes the metadata, but also synchronizes the content of queue, which seriously affects the performance of the cluster.

Does mirrored supports configuration for synchronizing metadata Only?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Schema/definitions, such as what queues exist in a cluster, are always replicated to all nodes. Please clarify what you mean by "metadata". If that means "queue properties" then your claim is factually incorrect.

**Comment by michaelklishin** [comment]
[Relevant documentation section](https://www.rabbitmq.com/clustering.html#cluster-membership).
