### ISSUE TITLE
record authz_socket_info undefined

### ISSUE THREAD

**Issue by zyfmix** [rabbitmq/rabbitmq-server#2027]
I was install rabbitmq server by source compile,when it comes to make, it's crash error:

    src/rabbit_access_control.erl:43: record authz_socket_info undefined
    make[1]: *** [erlang.mk:5177: ebin/rabbit.app] Error 1
    make: *** [erlang.mk:4967: app] Error 2
    The command '/bin/sh -c make' returned a non-zero code: 2

I was installed with docker follow bellow:

    ENV OTP_VNO 22.0
    ENV ELIXIR_VNO 1.8
    ENV RABBITMQ_VNO 3.7.15

    # 安装软件依赖包 ...
    WORKDIR /data/opt
    RUN apt install -y libncurses5-dev

    # 下载 OTP Erlang 运行环境...
    WORKDIR /data/opt
    RUN wget http://erlang.org/download/otp_src_${OTP_VNO}.tar.gz
    RUN tar -zxvf otp_src_${OTP_VNO}.tar.gz
    RUN mv otp_src_${OTP_VNO} otp_src
    WORKDIR /data/opt/otp_src
    RUN ./configure
    RUN make -j4
    RUN make install

    # 回到安装主目录
    WORKDIR /data/opt

    # 安装 elixir 执行环境...
    RUN git clone https://github.com/elixir-lang/elixir.git
    WORKDIR /data/opt/elixir
    RUN git checkout v${ELIXIR_VNO}
    RUN make
    RUN make install

    # 回到安装主目录
    WORKDIR /data/opt

    # 源码编译
    # 新版本编译报错: [src/rabbit_access_control.erl:43: record authz_socket_info undefined]
    RUN git clone https://github.com/rabbitmq/rabbitmq-server.git
    WORKDIR /data/opt/rabbitmq-server
    RUN git checkout tags/v${RABBITMQ_VNO} -b new_coam_branch
    RUN make
    RUN make install

Error same with otp-21.3 and rabbit-mq-3.7.14,does i missing somethings?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The record was introduced in https://github.com/rabbitmq/rabbitmq-server/pull/110. The header file is in [`rabbit_common`](https://github.com/rabbitmq/rabbitmq-common/blob/master/include/rabbit.hrl).

I cannot reproduce using our [server build instructions](https://www.rabbitmq.com/build-server.html). You are welcome to share your environment details on the mailing list.

Also note that there is no reason to build RabbitMQ from source. Use the [binary packages](https://www.rabbitmq.com/install-generic-unix.html) instead.

**Comment by michaelklishin** [comment]
So this is due to a `rabbit`/`rabbit_common` branch mismatch. I can reproduce something similar if I first build `master`, then check out `v3.7.x` and build without cleaning. The record is gone in `master` but not in `v3.7.x`. So is a couple of others, e.g. the public `amqqueue` record.

You can download and build [the source tarball](https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.15/rabbitmq-server-3.7.15.tar.xz) which includes all repositories at  `v3.7.15`:

```
wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.15/rabbitmq-server-3.7.15.tar.xz
tar xf rabbitmq-server-3.7.15.tar.xz
cd rabbitmq-server-3.7.15
make
```
