### ISSUE TITLE
Plugin .app file expansion doesn't work for RABBITMQ_BASE paths containing certain characters

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-server#2035]
Currently RabbitMQ can't be installed in RABBITMQ_BASE path containing symbols `*?[]{}` (or, at least, with certain restrictions)

E.g.

https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_plugins.erl

```
prepare_plugin(#plugin{type = dir, location = Location, name = Name},
               _ExpandDir) ->
    case filelib:wildcard(Location ++ "/ebin/*.app") of
```
must be rewritten as
```
prepare_plugin(#plugin{type = dir, location = Location, name = Name},
               _ExpandDir) ->
    case filelib:wildcard("ebin/*.app", Location) of
```
to enable `Location` with symbols from `*?[]{}` 

Found in **3.6.10** on **Windows**, but it is relevant to all versions and platforms (except `*?`, which are disallowed in Windows paths either)

**Comment by michaelklishin** [comment]
You are welcome to submit a pull request but I doubt that `*?[]{}` are particularly common in installation directories. This is the first time I could find this being reported in over 5 years.

**Comment by inikulshin** [comment]
You're right, wildcard special symbols are not particularly common in installation directory paths.
But they're **not supported** and I didn't found any mention about in RabbitMQ installation guides and docs.

We have thousands of installations, and we don't want to limit our clients. Every time we should explain that those symbols (in Windows also `!^`, because of RabbitMQ batch files) are not supported, our product looks more fragile and less reliable.

Reproduction scenario (on **WIndows**)

1. Set `RABBITMQ_BASE` environment variable to `C:\Temp\[{Rabbit MQ`
2. Install RabbitMQ server
3. Try to start RabbitMQ

=WARNING REPORT==== 17-Jun-2019::09:47:30 ===
worker_shutdown_timeout={ok,600000}

=INFO REPORT==== 17-Jun-2019::09:47:31 ===
Error description:
   {badpattern,missing_delimiter}

Log files (may contain more information):
   C:/Temp/[{Rabbit MQ/log/rabbit@localhost.log
   C:/Temp/[{Rabbit MQ/log/rabbit@localhost-sasl.log

Stack trace:
   [{filelib,wildcard,1,[{file,"filelib.erl"},{line,53}]},
    {rabbit_plugins,prepare_plugins,1,
                    [{file,"src/rabbit_plugins.erl"},{line,205}]},
    {rabbit,broker_start,0,[{file,"src/rabbit.erl"},{line,293}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,417}]},
    {init,start_em,1,[{file,"init.erl"},{line,1076}]},
    {init,do_boot,3,[{file,"init.erl"},{line,784}]}]

**Comment by michaelklishin** [comment]
Sorry I'm still not convinced that we should change a code path that is impractical to test extensively besides property-based testing of a function or two and had no issues reported against it in at least 5 years. There always will be an edge case with paths that is incompatible with globs or regular expressions. Perhaps your product/installer could introduce path validations instead of expecting every dependency you have to support every directory name out there.

I [documented the above characters as unsupported](https://github.com/rabbitmq/rabbitmq-website/commit/50b9f77123ed268a8b3a772e8df75037511d6e4f).

Perhaps it is worth mentioning that RabbitMQ 3.6.x [has been out of support for over 1 year](https://www.rabbitmq.com/changelog.html), and specifically `3.6.10` is 6 patch releases behind the latest `3.6.x`.
