### ISSUE TITLE
RabbitMQ Cluster single machine

### ISSUE THREAD

**Issue by armanpetrosyan23** [rabbitmq/rabbitmq-server#2042]
Hi everyone, I created RabbitMQ cluster single machine, and i recieve this message for second node stattistics (Node statistics not available ). Please help me
I work in Windows OS,

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [Running management plugin on a subset of nodes](https://www.rabbitmq.com/management.html#clustering-subset-of-nodes).
