### ISSUE TITLE
make fails with FIPS enabled OpenSSL - complains about EVP_rc4 symbol missing in libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by vikmalik** [rabbitmq/rabbitmq-server#2061]
I am trying to use rabbimq-server (v3.7.15-1 with erlang v22.0.7-1) with fips enabled mode, it didn't work well as it kept throwing following error:

```
{error,{load_failed,"Failed to load NIF library: '/usr/lib/erlang/lib/crypto-4.2.2.2/priv/lib/crypto.so: symbol RC4 version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference'"}}
```

i thought its problem with erlang not able to support fips mode, so I decided to build erlang with --fips-enabled flag and try to compile rabbimq server in same environment. I had fips mode on for openssl as well. I ran ```make``` command to build executable, but it failed as well with same error

```
":load_failed, Failed to load NIF library: '/home/ubuntu/kerl/22.0-fips/lib/crypto-4.5/priv/lib/crypto.so: symbol EVP_rc4, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference'"
```
so I am stuck now, I am not able to use rabbimq with fips enabled openssl, could you please guide me what is causing this issue and if there is any workaround for this ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ does not implement TLS or use any crypto functions directly. It also doesn't load any NIF libraries, the message clearly comes from the `crypto` module in the runtime. To our knowledge the FIPS-compliant part of the crypto module has not been updated ever since its original development in 2015 or so. So I'd not expect it to work with Erlang 22, which almost certainly requires a recent OpenSSL version.

This is `erlang-questions` material.
