### ISSUE TITLE
dlx message  don't expire in expected seconds

### ISSUE THREAD

**Issue by geosmart** [rabbitmq/rabbitmq-server#2074]
I'm not set the x-max-priority property,  and have the same problem!
 If I put 2 messages: with expired time 1 minute and 10 minutes. 
In this case both messages delivered after 10 minutes.
 Is it a correct behavior?
I need   consumer recieve  message(ttl=1) first!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
From [TTL documentation](https://www.rabbitmq.com/ttl.html#per-message-ttl-caveats):

```
Only when expired messages reach the head of a queue will they actually be discarded (or dead-lettered). Consumers will not have expired messages delivered to them.
```

**Comment by geosmart** [comment]
the queue ttl is simple enough and working fine.
but set per message ttl  is not working expectly: 
each message publish to online consumer just after ttl.
 
why rabbitmq provide this feature?  for which biz scenario?

**Comment by geosmart** [comment]
> From [TTL documentation](https://www.rabbitmq.com/ttl.html#per-message-ttl-caveats):
> 
> ```
> Only when expired messages reach the head of a queue will they actually be discarded
> (or dead-lettered). Consumers will not have expired messages delivered to them.
> ```

if i want to consume each message just  as the per message ttl ,any solution?

**Comment by michaelklishin** [comment]
I don't have much to add to what the [Caveats section](https://www.rabbitmq.com/ttl.html#per-message-ttl-caveats) already covers. Expired messages are not delivered to consumers but if they are delivered right before expiration, of course, they will reach the consumer. Delivery still takes time, however small it may be.

**Comment by michaelklishin** [comment]
Please post all further questions to rabbitmq-users, our public mailing list. Thank yoou.
