### ISSUE TITLE
What is the maximum number of queues created in RabbitMQ?

### ISSUE THREAD

**Issue by uzdz** [rabbitmq/rabbitmq-server#2093]
I hope your answer.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is no limit by default but operators [can configure one](https://www.rabbitmq.com/vhosts.html#limits) on a per-vhost basis. Every queue consumes a certain amount of memory and [runtime scheduler time](https://www.rabbitmq.com/queues.html#runtime-characteristics). So the actual peak sustained number depends on the system and [runtime configuration](https://www.rabbitmq.com/runtime.html). There are certainly known environments with over 1M queues.

**Comment by michaelklishin** [comment]
> There is no limit by default but operators [can configure one](https://www.rabbitmq.com/vhosts.html#limits) on a per-vhost basis. Every queue consumes a certain amount of memory and [runtime scheduler time](https://www.rabbitmq.com/queues.html#runtime-characteristics). So the actual peak sustained number depends on the system and [runtime configuration](https://www.rabbitmq.com/runtime.html). There are certainly known environments with over 1M queues.

I have seen cases where someone was led to believe by this statement that "RabbitMQ with all defaults can support 1M queues". Different queue types and workloads will consume a different amount of resource. Keep a few things in mind when you read the above comment

1. Having 1M queues often means a comparable number of connections, which in and of itself [requires tuning](https://www.rabbitmq.com/docs/connections#large-number-of-connections), to the point that that workload has a dedicated documentation section in the Networking guide; without a certain amount of kernel tuning, the 1M concurrent connection goal on Linux is not realistic (this is covered in more detail in the linked doc guides and below)
2. Reaching 1M queues plus 1M connections in a cluster will require adequate hardware resources. A couple of cores per nodes will not be enough even with [reduced metric collection CPU footprint](https://www.rabbitmq.com/docs/runtime#erlang-process-limit)
3. Sustaining that many queues can and in practice will require tuning in other areas, including the high (1M by default) [Erlang process limit](https://www.rabbitmq.com/docs/runtime#erlang-process-limit): 1M connections + 1M channels + 1M queues = 3M Erlang processes even if we completely ignore everything else that runs on a RabbitMQ node
4. Getting to 1M connections and queues will require Linux kernel default tuning even with RabbitMQ distributions from VMware (both open source and Tanzu) because even in 2025, Linux kernel defaults are absolutely inadequate even for 100K connections per node. The default file handle limit on Linux is 1024, and while VMware deployments have much higher defaults, they usually do not surpass 60K-80K for various reasons, namely the [inevitable memory footprint of the runtime](https://www.rabbitmq.com/blog/2022/08/30/high-initial-memory-consumption-of-rabbitmq-nodes-on-centos-stream-9) with the limit set to 100s of thousands or millions

So yeah, 1M of connections plus 1M queues will require tuning at several levels, including kernel setting tuning, and an adequate amount of hardware resources.

Fortunately, adding more cluster nodes and a maintaining a reasonable queue leader and client connection distribution helps with scaling on both of those metrics.
