### ISSUE TITLE
Erlang/OTP 22 cannot install rabbitmq-server-3.7.17-1.el7.noarch.rpm

### ISSUE THREAD

**Issue by wecloud2008** [rabbitmq/rabbitmq-server#2094]
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Eshell V10.4  (abort with ^G)
1> 

[root@li1861-201 opt]# rpm -ivh rabbitmq-server-3.7.17-1.el7.noarch.rpm 
warning: rabbitmq-server-3.7.17-1.el7.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 6026dfca: NOKEY
error: Failed dependencies:
	erlang >= 20.3 is needed by rabbitmq-server-3.7.17-1.el7.noarch

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`NOKEY` strongly suggests the [signing key](https://www.rabbitmq.com/signatures.html) was not imported. We also have no information on how the Erlang package was installed. My guess is that it is a duplicate of https://github.com/rabbitmq/erlang-rpm/issues/64.
