### ISSUE TITLE
Make sure that CONF_ENV_FILE location can be overridden

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#210]
I'm not sure if that's intentional but we should investigate making it so.

**Comment by occho** [comment]
What does this issue mean?
Is it still an open issue?

**Comment by michaelklishin** [comment]
It is: it's still not possible to override 'rabbitmq-env.conf' location IIRC.

**Comment by occho** [comment]
OK, maybe I understand.
My first thought was the issue is CONF_ENV_FILE location cannot be overridden in any way due to some logic that depends on the default value (/etc/rabbitmq/rabbitmq-env.conf).

I'm guessing you mean that we cannot override CONF_ENV_FILE variable by setting a corresponding environment variable like RMQ_CONF_ENV_FILE, right?


We currently changes the CONF_ENV_FILE value directly in [rabbitmq-defaults](https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-defaults#L45).

**Comment by michaelklishin** [comment]
> On 20 feb 2016, at 5:14, Tomoyuki Saito <notifications@github.com> wrote:
> 
> I'm guessing you mean that we cannot override CONF_ENV_FILE variable by setting a corresponding environment variable like RMQ_CONF_ENV_FILE, right?

You understanding seems correct.

**Comment by michaelklishin** [comment]
There were recent changes in this area, so chances are, this is already possible or we are close to it. We need to investigate first.

**Comment by hairyhum** [comment]
`CONF_ENV_FILE` is just being sourced by `rabbitmq-env` script before redefining `RABBITMQ_` variables, so it's safe to override it with something like `RABBITMQ_CONF_ENV_FILE`.
In windows scripts it can already be overridden, in shell scripts it doesn't seem intentional according to commit history.

**Comment by michaelklishin** [comment]
Thank you, @hairyhum.
