### ISSUE TITLE
mochiweb_socket_server,295,{acceptor_error,{error,accept_failed}

### ISSUE THREAD

**Issue by cesadan01** [rabbitmq/rabbitmq-server#2104]
Hi people,

I'm trying to enable SSL on the RabbitMQ plugin page.
I configured the rabbitmq.config file
![2019-09-11 08_52_15-root@clurmq01_~](https://user-images.githubusercontent.com/50356087/64674712-b8e63b80-d471-11e9-8de1-f7ef1068661d.png)

 I restart the service, but when I try it returns the following errors and blank page

![2019-09-11 08_50_00-Inbox - daniele cesario@4ward it - Outlook](https://user-images.githubusercontent.com/50356087/64674760-cef3fc00-d471-11e9-9af6-f71f43bc824e.png)
![2019-09-11 08_52_41-52 233 248 41](https://user-images.githubusercontent.com/50356087/64674766-d2878300-d471-11e9-9ba1-16daa91f9e02.png)

I have a two-node cluster and the changes on the second node still have to be applied, but I don't think that's the problem.

I used a RabbitMQ version {rabbit,"RabbitMQ","3.3.5"}

The file owner is the rabbitmq user
![image](https://user-images.githubusercontent.com/50356087/64675075-8be65880-d472-11e9-856d-aab6291eb946.png)

Do you have any ideas?

Thansk a lot.

Daniele

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Please search the Web for `eacces`. It means that a file system operation failed due to insufficient effective user permissions. From the [RabbitMQ TLS guide](https://www.rabbitmq.com/ssl.html#enabling-tls-paths):

«RabbitMQ must be able to read its configured CA certificate bundle, server certificate and private key. The files must exist and have the appropriate permissions. When that's not the case the node will fail to start or fail to accept TLS-enabled connections.»

**Comment by michaelklishin** [comment]
It's worth mentioning that RabbitMQ has switched from Mochiweb to Cowboy in the 3.6.0 development cycle. 3.6.0 was [released in December 2015](https://www.rabbitmq.com/changelog.html).

Consider using the [new configuration format](https://www.rabbitmq.com/configure.html#configuration-files) that provides additional validations for file paths.
It is available in all the [currently supported versions](https://www.rabbitmq.com/versions.html).
