### ISSUE TITLE
A message is undelivered and becomes an undelivered state

### ISSUE THREAD

**Issue by acuitong** [rabbitmq/rabbitmq-server#2105]
What causes A message is undelivered and becomes an undelivered state?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
"Undelivered" is not a state RabbitMQ management UI or docs use. Assuming you mean "a message in Ready state that was previously delivered", see the two sections related to requeueing in the [Acknowledgements guide](https://www.rabbitmq.com/confirms.html).

**Comment by acuitong** [comment]
Consumers didn't get the message，But the state of the message becomes "Unacked"，Blocking subsequent consumption，I'm setting it to auto ack
