### ISSUE TITLE
RabbitMQ should not use predefined environment variables - it should use it's own configuration files or own unique environment variables

### ISSUE THREAD

**Issue by xantari** [rabbitmq/rabbitmq-server#2107]
RabbitMQ uses some system environment variables to write things like .erlang.cookie (specifically the HOMEDRIVE environment variable is often a culprit)

This poses problems in corporate environments on developer PC's who have their home drive remapped to a network share.

Suggestions of changing to use your own environment variables and/or configuration files for making that determination and not piggy back off of existing environment variables that users have little control over.

Good discussion on the topic here:
https://stackoverflow.com/questions/17496037/change-default-home-path-in-erlang-to-resolve-rabbitmq-start-up-error

**Comment by lukebakken** [comment]
Hi and thank you for using RabbitMQ.

The use of a user's home directory for the `.erlang.cookie` location is determined by the Erlang VM and there is little that can be done about it. If a user wishes to use a different location, they will have to set `HOME` *prior* to running the Erlang VM for the first time since the VM creates the cookie file on first run. Or, you can set `HOME` and create the `.erlang.cookie` file yourself, at which point the Erlang VM will use it.

Please post this question to the mailing list if you'd like to continue to discuss options.

https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by michaelklishin** [comment]
Using most common environment variables such as `HOMEDRIVE` is reasonable. That's why they exist: for software to rely on them.

Changing what fundamental environment variables we rely on would be quite a change to consider, given that they have been stable in over 12 years now.
