### ISSUE TITLE
ha policy incompatible with queue expires policy

### ISSUE THREAD

**Issue by chopper-poet** [rabbitmq/rabbitmq-server#2125]
hi,friend
If i set up a expire policy for queue,the ha policy will not effective,here are my policies.

![image](https://user-images.githubusercontent.com/16041012/65869910-cc6c2e80-e3ad-11e9-80c2-49e1bc389485.png)

![image](https://user-images.githubusercontent.com/16041012/65870079-0a695280-e3ae-11e9-898b-cae01c00bc89.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Only one policy is applied to a queue or exchange at a time.

From [Combining Policy Definitions](https://www.rabbitmq.com/parameters.html#combining-policy-definitions):

> In some cases we might want to apply more than one policy definition to a resource.
> For example, we might need a queue to be federated and mirrored.
> At most one policy will apply to a resource at any given time, but we can apply multiple definitions in that policy.

In other words, both mirroring and TTL keys have to be combined into a single policy.
