### ISSUE TITLE
ReferenceError: disable_stats is not defined ReferenceError on Windows 10

### ISSUE THREAD

**Issue by saurav-kumar-inferstat** [rabbitmq/rabbitmq-server#2128]
I am getting below error on a Window 10 64 bit machine- 

`ReferenceError: disable_stats is not defined ReferenceError: disable_stats is not defined at Object.process (eval at compile (http://localhost:15672/js/ejs-1.0.min.js:1:6654), :6:29) at EJS.render (http://localhost:15672/js/ejs-1.0.min.js:1:1885) at format (http://localhost:15672/js/main.js:1086:21) at check_login (http://localhost:15672/js/main.js:89:34) at start_app_login (http://localhost:15672/js/main.js:75:9) at HTMLDocument. (http://localhost:15672/js/main.js:3:5) at e (http://localhost:15672/js/jquery-3.4.1.min.js:2:29453) at t (http://localhost:15672/js/jquery-3.4.1.min.js:2:29755)
`

Steps to reproduce -
1. Install `RabbitMQ 3.8.0` from official GiHub link
2. Enable rabbitq_management 
3. Go to url `http://localhost:15672/` (default port).

![image](https://user-images.githubusercontent.com/50596409/66023177-03f1ec80-e50e-11e9-9e01-ca3eed000fcd.png)

**Comment by michaelklishin** [comment]
We are aware of two cases where this happens:

* A 3.7 UI uses an upgraded node without refreshing
* the same case happening due to browser caching of JS resources 

Making 3.8 UI backwards compatible with the 3.7 API is not something our team has the resources to do. Please clear browser cache and reload the page, it should be sufficient.
