### ISSUE TITLE
Can regular expressions be supported in routingKey ?

### ISSUE THREAD

**Issue by QiusHosens** [rabbitmq/rabbitmq-server#2207]
i want to use regular expressions in routingKey, such as a|b.
e.g, publish two types of messages(such as t1/t2) to an exchange.
i want to create three types of queue to bind this exchange.
1、receive message that type is t1;
2、receive message that type is t2;
3、receive message that type is t1 and t2.
how to solve this problem？
thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
A new exchange plugin could do it. A convention-based use of [topic exchanges](https://www.rabbitmq.com/tutorials/tutorial-five-python.html) and multiple bindings (possibly to the same set of queues) could be a decent approximation.
