### ISSUE TITLE
Support for SAC definitions in policy

### ISSUE THREAD

**Issue by pbillen** [rabbitmq/rabbitmq-server#2213]
Hi,

Are there plans to support the `single-active-consumer` flag of a queue in a policy? This does not seem to be possible in 3.8.2 (via admin UI or API). I cannot see a reason not to allow it to be defined in a policy, but maybe I am overlooking something? FWIW, I couldn't find anything related to this in https://github.com/rabbitmq/rabbitmq-server/pull/1802 and related issues.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
