### ISSUE TITLE
Investigate graceful shutdown in response to UNIX signals

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2222]
As of Erlang/OTP 20.x, which we can require, OTP has a way for applications to [handle OS signals in a more sensible way](https://medium.com/@ellispritchard/graceful-shutdown-on-kubernetes-with-signals-erlang-otp-20-a22325e8ae98) (using `gen_event` listeners).

It would make life easier for operators if RabbitMQ nodes behaved more typically of a conventional UNIX process, namely responded to `SIGTERM`, `SIGHUP` and perhaps a few others.

A `SIGTERM` signal should ideally be equivalent of a `rabbitmqctl shutdown` call.

Per discussion with @ChunyiLyu @gerhard.

**Comment by lukebakken** [comment]
@michaelklishin @Vanlightly since we require Erlang 21.3 for the latest `3.7.x` versions I'm assuming this should be backported (?)

**Comment by dumbbell** [comment]
Is it possible to revert this in `master`?

`rabbit` is a regular Erlang application now in this branch, therefore RabbitMQ is stopped gracefully like any other Erlang applications when the VM receives a SIGTERM signal. I would like to not reinvent things again there.

**Comment by michaelklishin** [comment]
@dumbbell we don't reinvent much and we added logging but you are welcome to revert it if we are certain that the shutdown is safe. We have evidence that in 3.8 it wasn't without an explicit clean shutdown.

**Comment by michaelklishin** [comment]
In my opinion RabbitMQ and other tools should have their own signal handlers. Relying on the underlying runtime to do exactly what you want is too optimistic and the behavior can vary between versions. Plus if you want to do something in reaction to `USR1` and `USR2`, you'd have to roll out your own handler anyway. It's a pretty tiny module, too.

**Comment by lukebakken** [comment]
@dumbbell thanks for bringing that point up. It didn't even cross my mind.

How about we log the signal that is seen (if the default handler doesn't) and only ignore those we wish to ignore, defaulting to the default behavior since it will stop RabbitMQ correctly?

**Comment by dumbbell** [comment]
The problem with the signal handler in `master` is that we have again several (inconsistent) behaviors depending on how one stops RabbitMQ. With this patch, we call `rabbit:stop_and_halt()` (which I would love to remove) in the case of a signal, but `init:stop()` will go through the regular application master directly (and do half of what we expect before the VM is terminated).

The stopping code in `rabbit.erl` just reinvents what Erlang's application master does for years and adds its own undocumented things on top of it (to handle plugins and dependencies + logging). I believe it makes more sense to leverage the existing, maintained and documented Erlang behavior instead of having our own implementation. I clearly don't see the added value of the latter.
* Managing plugins? `rabbit:stop/1` (the regular Erlang application callback) should already take care of that if plugins can't work with `rabbit` stopped. Exactly like `rabbit:start/2` will start them.
* Managing dependencies? If dependencies' stop must be managed by an application which depends on them, there is a design flow somewhere. The only current reason to manage Mnesia and Ra specifically during startup, is that we need to configure them before they are started (or restart them after configuration), especially Ra (otherwise it creates files in unexpected places). We have a few lines of code for this in `master` and, if one day we can finally make an Erlang release for RabbitMQ, they will go away.
* Logging? We can log whatever we want from `rabbit:stop/1`. Exactly like what we did with the startup code which logs waaay more informations than what we have in 3.7 & 3.8. Also, Erlang can already log applications start/stop.

**Comment by dumbbell** [comment]
Also, the only reason we still have `start_apps/2` in `master` (likewise for `stop_apps/1`) is the need to run boot steps: they should also be part of the regular startup of plugins, not a RabbitMQ-specific thing.
