### ISSUE TITLE
Authentication Failure If Host In /etc/hosts Has Alias

### ISSUE THREAD

**Issue by jasonrogena** [rabbitmq/rabbitmq-server#2223]
RabbitMQ Version: 3.6.15-1
Erlang Version: 20.3
Operating System: Ubuntu 18.04

I have, in my `/etc/hosts` file this line (the host's hostname has been set as an alias of the localhost record):

```
127.0.0.1 localhost server1
```

When I run rabbitmqctl I get the following error:

```
Error:********@localhost'
- home dir: /var/lib/rabbitmq
- cookie hash: <REDUCTED>", "rc": 69, "stderr": "Error: unable to connect to node rabbit@localhost: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@localhost]

rabbit@localhost:
  * connected to epmd (port 4369) on localhost
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed

  * Hostname mismatch: node "rabbit@server1" believes its host is different. Please ensure that hostnames resolve the same way locally and on "rabbit@server1"


current node details:
- node name: 'rabbitmq-cli-60@localhost'
- home dir: /var/lib/rabbitmq
- cookie hash: <REDUCTED>
```

However, I don't get this error when I modify the /etc/hosts file to:

```
127.0.0.1 localhost
127.0.0.1 server1
```

I don't get this error. Maybe I got something wrong but my assumption here is that RabbitMQ doesn't support records that have aliases in the hosts file.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
> Hostname mismatch: node "rabbit@server1" believes its host is different

is the line you are looking for.  [Hostname Resolution Requirements](https://www.rabbitmq.com/clustering.html#cluster-formation-requirements) covers this. Erlang VM hostname resolution can be configured without messing with `/etc/hosts` but can also use it (via the OS resolver) like almost every other piece of software.
