### ISSUE TITLE
Change collect_statistics is not respected by RMQ

### ISSUE THREAD

**Issue by avarf** [rabbitmq/rabbitmq-server#2242]
Hi, I am using the Helm chart of rabbitmq-ha to launch RMQ on k8s. I noticed that the default value of `collect_statistics` has been set to `fine` but in the (documentation)[https://www.rabbitmq.com/configure.html#config-items] it is mentioned that:
```
Default:

collect_statistics = none
```

After this I tried to change it by expelicitly set `collect_statistics = none` and later `collect_statistics = coarse` and `collect_statistics_interval = 15000`. I can see that the new config has correctly passed to the container:
```bash
bash-5.0$ cat /etc/rabbitmq/rabbitmq.conf | grep collect_statistics
collect_statistics = coarse
collect_statistics_interval = 15000
```

But when I check the environment from withing container I see that `collect_statistics` hasn't been changed:
```bash
bash-5.0$ rabbitmqctl environment | grep collect_statistics
      {collect_statistics,fine},
      {collect_statistics_interval,15000},
```

I tried to just pass some value to such as `collect_statistics = abcd` and the container crashed and I got below in the logs:
```log
BOOT FAILED
===========

Config file generation failed:
10:35:57.130 [error] Error generating configuration in phase transform_datatypes
10:35:57.130 [error] Error transforming datatype for: collect_statistics
10:35:57.130 [error] "abcd" is not a valid enum value, acceptable values are: none, coarse, fine
In case the setting comes from a plugin, make sure that the plugin is enabled.
Alternatively remove the setting from the config.

{"init terminating in do_boot",generate_config_file}
init terminating in do_boot (generate_config_file)
```

So the configuration has been passed to RMQ but for some reason, RMQ is not respecting `collect_statistics`.

I test this on both RMQ 3.8.1 and 3.7.12 and it was the same on both.

How I can change the `collect_statistics` to something other than `fine`?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This value is overridden by the [management agent](https://github.com/rabbitmq/rabbitmq-management-agent/blob/c604ddf956976745fb130e1f6ba64e5df25f75a6/src/rabbit_mgmt_db_handler.erl#L71) as needed in order to provide the rates mode configured.

Direct modification of `rabbit.collect_statistics` has been replaced with [rate mode](https://www.rabbitmq.com/management.html#fine-stats) years ago. [Management plugin guide](https://www.rabbitmq.com/management.html#fine-stats) only lists rate mode and not `rabbit.collect_statistics`.
