### ISSUE TITLE
Consider disabling busy-waiting by default

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2243]
As [this `rabbitmq-users` discussion](https://groups.google.com/d/topic/rabbitmq-users/dTP6sCSlNpM/discussion) and [this article](https://stressgrid.com/blog/beam_cpu_usage/) points out, busy-waiting consumes CPU for what appears to be little benefit. The higher CPU usage is unwanted in cloud environments where you pay for it.

@gerhard @michaelklishin - I suspect we already have run benchmarks for `+sbwt none` but probably not `+sbwtdcpu` nor `+sbwtdio`

**Comment by michaelklishin** [comment]
We have evidence that (expectedly) `+sbwt none` helps in environments where the number of processes greatly outpaces the number of cores/schedulers.

**Comment by pjk25** [comment]
I ran a small set of benchmarks against a 3 node cluster of single core vms, with quorum queues. While generally throughput was higher without busy waiting, it was also more variable, so I don't think we can say that a change in the default would be safe for all workloads. I ran the tests with all three erl flags, `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=+sbwt none +sbwtdcpu none +sbwtdio none`.

**Comment by michaelklishin** [comment]
Single-core VMs is just one scenario. Busy waiting is more relevant in multi-core environments and workloads that are volatile in nature (say throughput meaningfully goes up and down). We should primarily target those as single-core VMs is not really our target environment.

In case we see the same behavior we should close this issue and instead introduce a dedicated doc section in the Runtime guide about reducing CPU footprint in CPU constrainted and/or lower loaded systems.

**Comment by pjk25** [comment]
I ran a similar benchmark with n1-standard-4 (quad vCPU) nodes:

With busy waiting:
https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&var-rabbitmq_cluster=rtt-12345-with-busy-waiting&from=1582711737486&to=1582717019374
https://grafana.gcp.rabbitmq.com/d/C6pszWlWz/rabbitmq-benchmark-container?orgId=1&from=1582711737486&to=1582717019374&fullscreen&panelId=2&var-run_tag=rtt-12345&var-config_tag=with-busy-waiting

Without busy waiting:
https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582711737486&to=1582717019374&var-rabbitmq_cluster=rtt-12345-without-busy-waiting
https://grafana.gcp.rabbitmq.com/d/C6pszWlWz/rabbitmq-benchmark-container?orgId=1&from=1582711737486&to=1582717019374&fullscreen&panelId=2&var-run_tag=rtt-12345&var-config_tag=without-busy-waiting

The benchmark varies the number of consumers and publishers according to https://github.com/Vanlightly/RabbitTestTool/blob/master/orchestration/run/playlists/qq-point-to-point-safe.json
However, it should be noted that the run ended after only 9 of the 24 steps in the playlist (I suspect a preemptible VM was taken down, so I will have to re-run).

What I've noted from this run is the following:
- Higher throughput is achieved with busy waiting disabled, as before
- In the steps
    ```
        { "topologyVariables": { "publisherCount": "6", "queueCount": "6", "consumerCount": "6" } },
        { "topologyVariables": { "publisherCount": "8", "queueCount": "8", "consumerCount": "8" } },
        { "topologyVariables": { "publisherCount": "10", "queueCount": "10", "consumerCount": "10" } },
    ```
    Backlogs of messages began to build. [This was worst without busy waiting, for 6 queues, at 2.6 million messages](https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582713491114&to=1582715108233&var-rabbitmq_cluster=rtt-12345-without-busy-waiting). [There was a similar story with busy waiting, although the backlog did not grow as much, and was more stable](https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582713491114&to=1582715108233&var-rabbitmq_cluster=rtt-12345-with-busy-waiting). [CPU usage remained high in all 3 steps, although higher with busy waiting](https://grafana.gcp.rabbitmq.com/d/C6pszWlWz/rabbitmq-benchmark-container?orgId=1&from=1582713491114&to=1582715108233&fullscreen&panelId=2&var-run_tag=rtt-12345&var-config_tag=with-busy-waiting&var-config_tag=without-busy-waiting).
- In the step
    ```
    { "topologyVariables": { "publisherCount": "1", "queueCount": "1", "consumerCount": "1" } }
    ```
    Where things are arguably less loaded (the benchmark tool attempts to max out throughput, but there is only one queue), [CPU usage is generally lower without busy waiting](https://grafana.gcp.rabbitmq.com/d/C6pszWlWz/rabbitmq-benchmark-container?orgId=1&from=1582711913240&to=1582712412753&fullscreen&panelId=2&var-run_tag=rtt-12345&var-config_tag=with-busy-waiting&var-config_tag=without-busy-waiting).
- Overall we seem to get higher throughput with lower apparent CPU usage, at the cost of some stability with busy waiting turned off.

However, I do believe that the remaining steps of the playlist should be completed to see what happens when we benchmark latency, to round out the picture here.

**Comment by pjk25** [comment]
I completed the full 24 step benchmark:

With busy waiting:
https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582809679033&to=1582823237845&var-rabbitmq_cluster=rtt-12345-with-busy-waiting
https://grafana.gcp.rabbitmq.com/d/C6pszWlWz/rabbitmq-benchmark-container?orgId=1&from=1582809679033&to=1582823237845&fullscreen&panelId=2&var-run_tag=rtt-12345&var-config_tag=with-busy-waiting

Without busy waiting:
https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582809679033&to=1582823237845&var-rabbitmq_cluster=rtt-12345-without-busy-waiting
https://grafana.gcp.rabbitmq.com/d/C6pszWlWz/rabbitmq-benchmark-container?orgId=1&from=1582809679033&to=1582823237845&fullscreen&panelId=2&var-run_tag=rtt-12345&var-config_tag=without-busy-waiting

Observations:
- Steps 1-9 look consistent with the previous run
- More memory seems to be used with busy waiting
- In the latter 12 steps, which send messages at a fixed rate and are under the capacity of the cluster, disabling busy waiting doesn't have any effect on messaging rates, but does have the expected effect of reducing reported CPU usage

Takeaways:
Unfortunately I don't consider the results conclusive yet. For this configuration, I would probably turn of busy waiting, even though these are dedicated VMs. There seems to be a small throughput advantage, and there is an additional benefit that CPU saturation is easier to judge with classic tools. Looking across the larger set of 24 benchmark steps, there were cases where a message backlog built up [with](https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582811612170&to=1582812176002&var-rabbitmq_cluster=rtt-12345-with-busy-waiting) and [without](https://grafana.gcp.rabbitmq.com/d/Js7vR3QZk/rabbitmq-benchmark-clusters?orgId=1&from=1582811619856&to=1582812158974&var-rabbitmq_cluster=rtt-12345-without-busy-waiting). In this case things were a little worse without busy waiting, but over many runs, things might average out, so I don't see a downside to disabling busy waiting.
The things to consider before changing the default might be:
1. The benchmark generates load at steady rates for 5 minutes, and so it is almost surely not as bursty as some real world workloads.
2. I'm generally hesitant to recommend running Erlang with custom flags without profiling my use case specifically.

@michaelklishin any particular thoughts on the above? I think my final recommendation would be to add the dedicated doc section. It's the conservative recommendation, but we could revisit it say, 6 months after the docs update. If we've not seen any reports of users running into trouble with it, we could rerun some benchmarks and reconsider the change to the defaults.

**Comment by michaelklishin** [comment]
We had a doc section but it wasn't very specific as to what the effects are. The new one is hopefully more useful.

**Comment by lukebakken** [comment]
Thanks for doing the work @pjk25
