### ISSUE TITLE
Can erlang.cookie, (In SSL) certificate and private key be encrypted and not shown in plaintext?

### ISSUE THREAD

**Issue by Redfisky** [rabbitmq/rabbitmq-server#2265]
RabbitMQ server:
`3.7.16`

Erlang:
`22.0`

Operating system version (and distribution, if applicable):
`Huawei EulerOS 2.0`

All client libraries used:
`rabbitmq-java-client 5.7.2`

RabbitMQ plugins (if applicable):
None

Problem:
-  RabbitMQ Cluster authentication needs `erlang.cookie`,  passwords are stored in plaintext in `erlang.cookie`, is there any method to enhance security or add encryption mechanism?
- When SSL is enabled, RabbitMQ encrypted certificate file and private key are stored  in plaintext, this may cause security issues, any method to improve this?

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Erlang cookie file cannot be encrypted but it is required that its permissions are `0400` (accessible only by the owner). This is the same approach that ssh uses.

It makes no sense to encrypt certificates as they are public keys (meant to be shared, can only be used for *encryption*). Private keys are never encrypted. They can be password-protected, and the password value can be [encrypted]() using a separate private key. Ultimately you need a private key to decrypt things, so the problem is simply shifted to a different file.
