### ISSUE TITLE
Problem in rabbit with normal and less traffic

### ISSUE THREAD

**Issue by kaaaq** [rabbitmq/rabbitmq-server#2266]
Hi,
Im using rabbitmq cluster (v3.7.15) in production but i have problem with it, it can not resist with even normal traffic and it crashes with only 1200 req/second !!!, and i have this error messages on my servers:
`Uncaught PhpAmqpLib\\Exception\\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data.`

And network error but nodes can ping each other.
what should i do for solving this problem?
Best regards.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
