### ISSUE TITLE
Problem !! expiration message queue

### ISSUE THREAD

**Issue by Thanakorn-ki** [rabbitmq/rabbitmq-server#2271]
## I found an issue about the expiration message queue.
For example, I had `notification.message` queue name with `dead-letter-exchange` to the exchange `exchange.sent.noti` binding `queue.sent.noti` . And then per message queue difference, the expiration assume published `message 1` with `expiration` is 60000 as a 1 min and I publish again `message 2` with `expiration` 10000 as a 10 ms go to `notification.message` queue.

## For the example above,
Expect `message 2` will be expiration and pop yourself go to `exchange.sent.noti` and that the exchange push to `queue.sent.noti` queue. But not as expected. It waits for `message 1` expired also pop `message 2`.

Do you recommend for use expiration?. Or we should create a queue by queue per expiration.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
