### ISSUE TITLE
[Windows] - RabbitMQ service is running, but no response on telnet

### ISSUE THREAD

**Issue by tuananhzippy** [rabbitmq/rabbitmq-server#2275]
I have successfully installed RabbitMQ on Windows 10. When I go to Services, select RabbitMQ, right-click and select Start, service is running.

But when I visit http://127.0.0.1:15672 and Telnet to port 5672 didn't get response. Although I have enabled rabbitmq_management plugins.

Environment:
```
Erlang: 10.5
RabbitMQ Server: 3.8.2

```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
