### ISSUE TITLE
rabbitmq-unack

### ISSUE THREAD

**Issue by zhiliao666** [rabbitmq/rabbitmq-server#2284]
Hello, there is a problem on my side: the phenomenon is like this, we have a queue, this queue has 5 consumers, we turned on the manual confirmation mode for the message, the following is our configuration:

`
```properties
spring.rabbitmq.host=host
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=v-host
spring.rabbitmq.username={name}
spring.rabbitmq.password={password}
spring.rabbitmq.requested-heartbeat=5s
spring.rabbitmq.listener.type=simple
spring.rabbitmq.listener.simple.acknowledge-mode=manual
#spring.rabbitmq.listener.simple.missing-queues-fatal=true
spring.rabbitmq.listener.simple.prefetch=250
spring.rabbitmq.listener.simple.retry.enabled=false
spring.rabbitmq.listener.simple.retry.max-attempts=1
spring.rabbitmq.listener.simple.retry.max-interval=1000ms
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.stateless=true
spring.rabbitmq.listener.simple.retry.multiplier=1.5
spring.rabbitmq.cache.channel.size=40
spring.rabbitmq.cache.channel.checkout-timeout=2s
spring.rabbitmq.cache.connection.mode=channel
spring.rabbitmq.publisher-confirms=true
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.connection-timeout=3s
spring.rabbitmq.dynamic=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.template.reply-timeout=2s
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.multiplier=1.0
spring.rabbitmq.template.retry.initial-interval=1s
spring.rabbitmq.template.retry.max-interval=5s
spring.rabbitmq.template.retry.max-attempts=2
````

` <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>`

But at some point we find that the unack is full and then we stop consuming, we delete the queue and start again, but it doesn't work for a while

![image](https://user-images.githubusercontent.com/8140511/77304922-2253da80-6d30-11ea-899e-20d9c9f4e78b.png)

What might be the reason？？？

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid I do not understand what "unack is full" means. Your applications are responsible for acknowledging deliveries and [doing so once per delivery](https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking) only.

**Comment by michaelklishin** [comment]
A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) can immediately tell what applications do and so not do. [Application-level metrics](https://www.rabbitmq.com/api-guide.html#metrics) is another important data source.
