### ISSUE TITLE
Hello from Nowhere

### ISSUE THREAD

**Issue by treyconley** [rabbitmq/rabbitmq-server#2286]
I'm running RabbitMQ 3.8.2 with mqtt plugin. I have been able to reproduce this every time using any mqtt client. If I subscribe to a topic named "Results", I immediately receive a "Hello" message. This will happen even if the client is the only connection.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin does not publish any messages, although MQTT brokers sometimes have various "system topics".

Having no other connections does not mean that there is no previously enqueued data. Use `rabbitmqctl list_queues` and/or [management UI](https://www.rabbitmq.com/management.html) to inspect ready message counts.
