### ISSUE TITLE
Message expired when consumer offline

### ISSUE THREAD

**Issue by koszar93** [rabbitmq/rabbitmq-server#2287]
I want to create a queue that, after an error on task execution, moves the task to the second queue, which will repeat its execution at the right moment.

Declaration queue:
Work.queue:
`{"x-dead-letter-exchange", RetryExchange},
		{"x-dead-letter-routing-key", RetryQueue}`
Retry.queue:
`{"x-dead-letter-exchange", WorkerExchange},
		{"x-dead-letter-routing-key", WorkerQueue},
		{"x-message-ttl", 60000},
	}`

So, after rejected task on work.queue, message travel to retry.queue, where after 60 sec go back to work.queue. In this case, if an error occurred while performing the task, everything is fine.

Problem is if the consumer task is disabled when publishing. The task goes to retry.queue, but unfortunately it is not queued to work.queue again. The quest disappears when it is marked as expired.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is no evidence of a bug. Consider posting an executable example to the mailing list. Queue lifecycle can be [tied to that of a connection or consumer](http://rabbitmq.com/queues.html), for example, and not necessarily intentionally.
