### ISSUE TITLE
Prevent quorum queues from being server-named

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2296]
Server-named quorum queues make no sense, as their [rationale](https://www.rabbitmq.com/quorum-queues.html) hopefully explains. They create interesting problems when used. We should prohibit this combination, as we already do for certain "transient state" features in the context of quorum queues.

Per discussion with @kjnilsson.

**Comment by dcorbacho** [comment]
We will wait to fix this issue until stream queues are merged, as we can use the new queue types to query queue capabilities and make it generic.

**Comment by avatarofhope2** [comment]
I don't understand the rationale or the problems, but would like to comment here to potentially find an alternative for my use case. I'm trying to create a high availability cluster, and I use the RPC model documented [here](https://www.rabbitmq.com/tutorials/tutorial-six-python). If I cannot use mirrored classic queues because of deprecation, how can I properly implement RPC in a highly available way?

**Comment by mkuratczyk** [comment]
Have a look at this discussion: https://github.com/rabbitmq/rabbitmq-server/discussions/6376 and if you have any questions - ask there.

The [local random exchange](https://github.com/rabbitmq/rabbitmq-server/pull/10091) could be an option once it's available.
