### ISSUE TITLE
x-max-length in overflow=reject-publish mode must limit total messages, not ready

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-server#2313]
As far as I understand, the main goal of `overflow=reject-publish` mode is to prevent message loss. Instead of silently dropping messages from queue head, RabbitMQ will notify publisher and it will able to react accordingly.

Also, `overflow=reject-publish` mode has no meaning without `x-max-length` or `x-max-length-bytes` argument. But for those limits

> In all cases the number of **ready** messages is used; unacknowledged messages do not count towards the limit.

It make sense in default  `overflow=drop-head` mode (in case of overflow rejected messages are dropped). But in `overflow=reject-publish` mode we don't want to lose **any messages**, including unacknowledged. **That means, queue must be able to receive back all the rejected messages without dropping.**

Imho, it can be achieved by changing `x-max-length` or `x-max-length-bytes` behavior in `overflow=reject-publish` mode (do count unacknowledged messages toward the limit), but it is a API breaking...

Please, please, consider this as a bug: whole `overflow=reject-publish` mode is pretty useless if rejected messages may be just dropped.

**Comment by michaelklishin** [comment]
`reject-publish` and length limits are by definition for cases where you can afford to lose data. That's how length limits work.

I'm afraid we won't count unacknowledged messages towards the limit for several reasons:

 * A delivered message is no longer "owned" by RabbitMQ, at least not by RabbitMQ alone, and nodes are not aware of what applications are doing
 * There is already a limit for [how many unacknowledged messages there can be on a channel](https://www.rabbitmq.com/confirms.html)
 * If we change what counts towards the limit, then max queue length limit would have to be changed. This would break a behavior that has been in place for a decade. 
 * This would couple publishers with consumers and there is a very clear decoupling of those in AMQP 0-9-1 and arguably messaging protocols in general

**Comment by michaelklishin** [comment]
With `reject-publish`, the idea is that

 * Consumers limit how much they can consume using channel QoS and the rate of acknowledgement that they prefer
 * Publishers keep track of what they publish and can change the rate based on the rate of acknowledgements
 * RabbitMQ notifies publishers about certain conditions and keeps track of the state of a queue, which can be affected by things such as limits, TTL, queue lifecycle settings and so on

These interactions are non-trivial and any changes in any place can result in surprising behaviors.
For example, the proposed change would be breaking to any system where a consumer can consume more than what the queue length limit is. How the limit should be defined depends on
who you ask but we don't see this topic brought up frequently which means the current implementation fulfills its mandate of

 * Protecting from overload in cases where publishers consistently outpace consumers, letting messages pile up
 * Not limiting consumers from how many deliveries they choose to process at any given moment
 * Only limiting publishers at the time when their activity clearly surpasses a certain threshold regardless of the rate of consumer activity

Changing this as suggested by @inikulshin would

 * Couple publisher activity to that of consumers. Adding more consumers would not allow publishers to publish as much as they could have.
 * Cause surprising, and potentially problematic behavior for every queue length limit user out there
 * Cause more deeply philosophical debates such as "what constitutes the length of a queue in presence of consumer acknowledgments". Since neither option would satisfy everyone, we would be spending more time fighting a battle that cannot be won.

So unless substantial evidence that most users would prefer this behavior emerges, we'd stick to the behavior we know.

**Comment by michaelklishin** [comment]
It could be my reading of the issue but we likely don't want to change the way queue length limits work depending on the overflow parameter. All queues types and classic queues specifically already have quite a number of configurable behaviors which often do not make any sense
when used together, which benefits neither users nor us maintainers.

We should be producing more focused queue types with fewer settings each, not more, and tweaking existing settings to mean different things in different contexts.

**Comment by inikulshin** [comment]
Thanks, @michaelklishin 

You must not break, that was just a (bad) option. E. g. the feature can be implemented with new arguments `x-max-length-total` and `x-max-length-bytes-total`.

This not a forum, but is it possible to prevent dropping rejected messages in `overflow=reject-publish` mode?
Active consumer can (try) explicitly republish consumed message, but what about connection loss? All unacknowledged messages over the limit will be just dropped?

It seems like memory/disk alarms are the only ways to 1) stop publishes on some limit 2) never loose any message...

**Comment by amills-vibeirl** [comment]
help ~
https://stackoverflow.com/questions/77804007/when-using-x-max-length-and-x-overflow-how-to-send-to-dead-letter-exchange
