### ISSUE TITLE
rabbitmq no more index entries in atom_tab(max=1048576)

### ISSUE THREAD

**Issue by huangyonghome** [rabbitmq/rabbitmq-server#2333]
HI
we often encounter below problem on several Rabbitmq cluster nodes since we have installed a python monitor script which get data through Rabbitmq web management periodically.

```
Oct  7 04:11:25 mq-es-node3 rabbitmq-server[2274]: Crash dump is being written to: erl_crash.dump...done  
Oct  7 04:11:25 mq-es-node3 rabbitmq-server[2274]: no more index entries in atom_tab (max=1048576)  
Oct  7 04:11:25 mq-es-node3 systemd[1]: rabbitmq-server.service: Main process exited, code=exited, status=1/FAILURE  
Oct  7 04:11:26 mq-es-node3 rabbitmqctl[2511]: Stopping and halting node 'rabbit@mq-es-node3' ...  
Oct  7 04:11:26 mq-es-node3 rabbitmqctl[2511]: Error: unable to connect to node 'rabbit@mq-es-node3': nodedown  
```
![image](https://user-images.githubusercontent.com/40015415/80697476-93df2f80-8b0b-11ea-9050-f49520ffb5d2.png)

I googled this problem and searched the similar error here.I heard that this issue was resolved since rabbitmq v3.6.5 . 

So I upgrade the rabbitmq version from v3.6.2 to v3.6.5 on our production environment. But I still experienced the same problem.

There is another strange question troubled us . Once the error causes the restart of Rabbitmq progress .The rabbitmq_delayed_message_exchange  plugin couldn't  work anymore, all message data which storage in delay queue would be lost. At the end, we have to replace a server.

`rabbitmq version: 3.6.5
erl version: 18.3`

Could you please help me to check on this ? Thank you in advance

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ 3.6.x has been [out of support for two years](https://www.rabbitmq.com/versions.html).  It is two feature and dozens of [patch releases behind](https://www.rabbitmq.com/changelog.html). Please [upgrade](https://www.rabbitmq.com/upgrade.html).

You may be referring to https://github.com/rabbitmq/rabbitmq-server/issues/992 (https://github.com/rabbitmq/rabbitmq-management/issues/245). Starting with `3.6.7` RabbitMQ management plugin was effectively redesigned from scratch. That release shipped over 3 years ago.

We are not aware of scenarios where runtime atom table can be exhausted in 3.8.
