### ISSUE TITLE
 Connection attempt from node rabbit@fbd0bef31d61 rejected. Invalid challenge reply.

### ISSUE THREAD

**Issue by Fossil01** [rabbitmq/rabbitmq-server#2382]
Trying to setup a cluster with Docker Swarm and etcd as the autodiscovery backend. I get this error on startup, can't find anything using Google that applies.

Is there any information about this?

rabbitmq.conf:

```
loopback_users.guest = false
listeners.tcp.default = 5672
default_pass = test123
default_user = test
management.tcp.port = 15672

cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd
cluster_formation.etcd.cluster_name = production

cluster_formation.etcd.endpoints.1 = 10.100.20.19:2379
cluster_formation.etcd.endpoints.2 = 10.100.20.20:2379
cluster_formation.etcd.endpoints.3 = 10.100.20.21:2379

# Forcefully remove unknown nodes from the cluster
cluster_formation.node_cleanup.only_log_warning = false

log.file.level = debug
log.console.level = debug
```

```
 etcdctl get --prefix=true "/"
/rabbitmq/discovery/rabbitmq/clusters/production/nodes/rabbit@65bfc680e0da
{"lease_id":2029560603933801994,"node":"rabbit@65bfc680e0da","ttl":61}
/rabbitmq/discovery/rabbitmq/clusters/production/nodes/rabbit@8d6984ed9f37
{"lease_id":2383093174648781414,"node":"rabbit@8d6984ed9f37","ttl":61}
/rabbitmq/discovery/rabbitmq/clusters/production/nodes/rabbit@fbd0bef31d61
{"lease_id":2383093174648781420,"node":"rabbit@fbd0bef31d61","ttl":61}
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
