### ISSUE TITLE
Can the latest 3.8 version of rabbitmq management view the detailed message information of the delay queue?

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/rabbitmq-server#2386]
Can the latest 3.8 version of rabbitmq management view the detailed message information of the delay queue, such as: message details, expiration time, etc. do you know whether this requirement has been solved?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
