### ISSUE TITLE
RabbitMQ 3.8.5 Windows service starts with random dist port

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2387]
To reproduce:

* Install Erlang on Windows (I used version 10 Pro)
* Install RabbitMQ 3.8.5
* Notice that the distribution port is not `25672`:

```
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmq-diagnostics.bat listeners
Asking node rabbit@DSCH-WIN to report its protocol listeners ...
Interface: [::], port: 51446, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: 0.0.0.0, port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
Interface: 0.0.0.0, port: 15672, protocol: http, purpose: HTTP API

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmqctl.bat eval "application:get_all_env(kernel)."
[{inet_dist_listen_max,25672},
 {shell_docs_ansi,auto},
 {inet_dist_listen_min,25672},
 {logger_sasl_compatible,false},
 {logger,
     [{handler,default,logger_std_h,
          #{config => #{type => standard_io},
            formatter =>
                {logger_formatter,
                    #{legacy_header => true,single_line => false}}}}]},
 {shutdown_func,{rabbit_prelaunch,shutdown_func}},
 {inet_default_connect_options,[{nodelay,true}]},
 {logger_level,notice}]
```

I believe this is due to the fact that, when running as a Windows service, RabbitMQ starts in distributed mode right away and chooses a random port.

You can work around this by creating the following file, then stopping, removing, and re-installing the Windows service:

```
C:\>type %AppData%\RabbitMQ\rabbitmq-env-conf.bat
set SERVER_ADDITIONAL_ERL_ARGS=-kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmq-service.bat stop
The RabbitMQ service is stopping.......
The RabbitMQ service was stopped successfully.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmq-service.bat remove
C:\Program Files\erl-23.0.2\erts-11.0.2\bin\erlsrv: Service RabbitMQ removed from system.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmq-service.bat install
C:\Program Files\erl-23.0.2\erts-11.0.2\bin\erlsrv: Service RabbitMQ added to system.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmq-service.bat start
The RabbitMQ service is starting.
The RabbitMQ service was started successfully.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.5>.\sbin\rabbitmq-diagnostics.bat listeners
Asking node rabbit@DSCH-WIN to report its protocol listeners ...
Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: 0.0.0.0, port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
Interface: 0.0.0.0, port: 15672, protocol: http, purpose: HTTP API
```

**Comment by dumbbell** [comment]
Thank you for the report! I believe your analysis is correct.

As you said, the service must start with Erlang distribution enabled. Unfortunately, there is no work around this currently, that's why the Windows service doesn't behave like rabbitmq-server(8). I guess this is because Erlang distribution is used by `erlsrv.exe` to communicate the service state to Windows.

Before my change to the startup scripts, `rabbitmq-service.bat` would use the old `rabbit_prelaunch` module to verify distribution (is the TCP port busy or is the nodename already taken?). This didn't make a lot of sense because the check happened at the time the service was installed. The TCP port could be busy or the nodename taken when the service actually starts.

The new `rabbitmq-service.bat` does not run the Erlang distribution checks anymore. I think this loss is ok.

However, I should restore the configuration of the Erlang distribution port, this is clearly a regression. I will prepare a patch.

**Comment by VVD** [comment]
When is 3.8.6 release planned?

**Comment by michaelklishin** [comment]
Possibly next week but we make no ETA promises. We can produce a preview build later this week if that would help.

**Comment by VVD** [comment]
Still no 3.8.6 release… :-(
