### ISSUE TITLE
seeing 'second channel open seen' error while checking if queue exists or not using second channel 

### ISSUE THREAD

**Issue by aaa091214** [rabbitmq/rabbitmq-server#2391]
i have two channels under one connection.
channel 1 is used to do the all the necessary queue declare/message etc.
channel2 is only used to check if queue exists or not (believe me, we have this need in my user case). 
i have read somewhere i need to use separate channel here. thus, in the check routine
checkIfQueueExists()
{
  channel2.open()
  //check reply
  amqp_declare (.., passive)
 //check reply
 channel2.close()
}

on first checkIfQueueExists(), it was all ok. but on 2nd checkIfQueueExists(), it error out (seems to me that the whole TCP connection is gone). 
rabbitmq log has this:
channel 2:
 operation channel.open caused a connection exception channel_error: “second ‘channel.open’ seen”

how do we check properly if queue exists?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This is mailing list material. Our team does not use GitHub issues for questions.

Your approach is correct but you seemingly run into an unintentional channel ID reuse. A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) will reveal exactly what your client does. A code example that can be used to reproduce and take a capture would save everyone a lot of time, so consider providing it. You haven't even mentioned what client is used and how.
