### ISSUE TITLE
Log rotation not working correctly on Windows

### ISSUE THREAD

**Issue by nick-randal** [rabbitmq/rabbitmq-server#2479]
settings from rabbitmq.conf

``` ini
log.file = rmq.log
log.file.rotation.size = 104857600
log.file.rotation.size = 4
```

All the files are continually updated and seem to be swapping log text back and forth between them on a constant basis.

![image](https://user-images.githubusercontent.com/6055507/96787542-ed8c2c80-13bf-11eb-96d5-70624f1096e1.png)

The only solution right now is to disable rotation. I also tried rotation by D0 but that did the exact same thing.

![image](https://user-images.githubusercontent.com/6055507/96787794-5d021c00-13c0-11eb-8f80-4852e3fadd93.png)

supported by Erland 22.2 on windows server 2019

**Comment by michaelklishin** [comment]
@nick-randal your config file has a duplicate key. `rabbitmq-diagnostics environment` will print effective configuration. The list of applications only tells us the versions. You are seven patch releases behind, so it would be great if testing was done using `3.8.9`.

@lukebakken we last had to deal with log rotation on Windows in https://github.com/rabbitmq/rabbitmq-server/pull/2078, and Lager version hasn't changed since then. I could not find any new relevant issues in Lager.
