### ISSUE TITLE
Consider moving x-death count into it's own property 

### ISSUE THREAD

**Issue by jwcnewton** [rabbitmq/rabbitmq-server#2498]
Consider moving `x-death[0].count` into it's own header `x-death-count`

```json
{"headers":{"x-death":[{"count":1,"reason":"expired","queue":"test","time":{"!":"timestamp","value":1605004226},"exchange":"","routing-keys":["test"]}],"x-first-death-exchange":"","x-first-death-queue":"test","x-first-death-reason":"expired"}
```

This would allow for the header exchange to route messages based on number retries. 

Ideally it would look something like this:

```json
{"headers":{ "x-death-count": 1, "x-death":[{"count":1,"reason":"expired","queue":"test","time":{"!":"timestamp","value":1605004226},"exchange":"","routing-keys":["test"]}],"x-first-death-exchange":"","x-first-death-queue":"test","x-first-death-reason":"expired"}
```

> Bellow are the headers of a message in a Dead Letter Queue. I'm using RabbitMQ.
> 
> __TypeId__: com.example.queue.TesteDTO
> correlationId:  dfbc9457-8de6-9b77-b7ad-b259d1e2ede4
> sequenceNumber: 1
> sequenceSize:   2
> x-death:    
>   count:    1
>     reason: rejected
>     queue:  queue.raffael.teste
>     time:   1478870283
>     exchange:   
>     routing-keys:   queue.raffael.teste
> 
> I want to declare and bind a Header Exchange using a complex expression, say:
> 
> x-match = any
> x-death[0].count = 1
> x-death[0].count = 2
> x-death[0].count = 3
> 
> But it doesn't work. It seems to work only for simple expressions:
> 
> x-match = any
> simpleExpression = 1
> simpleExpression = 2
> simpleExpression = 3
> 

See [stackoverflow issue](https://stackoverflow.com/questions/40549363/rabbitmq-how-to-use-complex-expressions-in-header-exchanges)

I believe creating a `x-death-count` header would allow for routing using the following rule:

x-match = any
x-death-count = 1
x-death-count = 2
x-death-count = 3

**Comment by michaelklishin** [comment]
I can see why certain original x-death values could be useful for routing but not why the count would be. This is a`wontfix` unless a lot more demand materializes.

**Comment by jwcnewton** [comment]
@michaelklishin This will allow us to move messages that cannot be process out of the dead letter queue for manual intervention. It would be very useful to have this logic contained within the exchange itself

**Comment by michaelklishin** [comment]
@jwcnewton `x-first-death-*` were added as top-level headers years ago to allow for just that. What makes the number of dead-lettering events special?

**Comment by jwcnewton** [comment]
@michaelklishin 

The number indicates how many times a particular task has failed. If a message is being repeatedly dead lettered I move it into a queue where it could be manually resolved, currently I append the `x-death[0].count` as a new property into the message so the property exchange can properly route it.

**Comment by PazReshef-Stork** [comment]
That's actually exactly what I need.
I have a dead-letter-exchange that needs to route the message differently if the retries are different.
The exchange should route the message to a retry-queue when the retires are less than 3, and to a manual-check-queue when the retries are more than 3.

I don't want my code to handle this logic, and since this exchange is dead-letter, I can't add or change headers of my own, I surely don't want to ack the message and re-publish it with new headers. 

Is there any other way to do something like that? am I missing something?

**Comment by michaelklishin** [comment]
There are projects such as Spring AMQP or MassTransit that successfully limit the number of retries without any changes to RabbitMQ.

The whole x-deaths thing is already complex and every time it is changed, there is someone who is affected and not happy about the change.

This is not a priority for our team before 4.0 or maybe even 4.1-4.2 ship.

Workaround discussions belong to a, well, discussion, which have been enabled for this repository since day 1 of the feature.
