### ISSUE TITLE
Inconsistent node disk space and memory with metric aggregation

### ISSUE THREAD

**Issue by logicbomb421** [rabbitmq/rabbitmq-server#2513]
I am seeing some oddness when I look at disk space (`rabbitmq_disk_space_available_bytes`) and memory (`rabbitmq_process_resident_memory_bytes`) metrics in a multi-node cluster. It seems the value returned hops between all nodes, which makes charting the value rather odd. After reading [the documentation on metric aggregation](https://www.rabbitmq.com/prometheus.html#metric-aggregation) and enabling `prometheus.return_per_object_metrics`, I expected to see these metrics expand into one per node, however that does not appear to be the case.

I would be very grateful if someone could explain how to view these two metrics per node.

##### Node Configuration
<img width="1497" alt="RabbitMQ_Management" src="https://user-images.githubusercontent.com/18082086/85448493-98dcc000-b54b-11ea-85b6-b4125d5dfddc.png">

##### Example of `rabbitmq_disk_space_available_bytes`
<img width="965" alt="CODE-975_–_Monitoring_–_Development_–_Google_Cloud_Platform" src="https://user-images.githubusercontent.com/18082086/85448256-5e732300-b54b-11ea-92ef-d56372884cd9.png">

##### Example of `rabbitmq_process_resident_memory_bytes`
<img width="959" alt="CODE-975_–_Monitoring_–_Development_–_Google_Cloud_Platform" src="https://user-images.githubusercontent.com/18082086/85448525-a3975500-b54b-11ea-98b7-64766cf93d23.png">

Thanks!

**Comment by michaelklishin** [comment]
We don't think these are aggregated. They may be missing labels. @logicbomb421 has the above suggestion from @gerhard helped? Are the charts from GCP (Google Cloud Platform)? If that's the case, it sounds like GCP is unaware of the fact that these metrics are node-specific.

**Comment by gerhard** [comment]
I am not sure how you are querying those metrics, but if you are using a loadbalancer or service to query rather than the nodes directly, then the values will change based on which node services the request.

`prometheus. return_per_object_metrics` applies to multiple metrics within a single node, like channels, queues etc. There will be a single `rabbitmq_process_resident_memory_bytes` metric per node, regardless of what `prometheus. return_per_object_metrics` is set to.

I'm assuming that this issue is solved for you @logicbomb421 👍🏻
