### ISSUE TITLE
Retained messages not sent to wildcard subscribers

### ISSUE THREAD

**Issue by csyllac** [rabbitmq/rabbitmq-server#2556]
Using the RabbitMQ Alpine docker image, which contains:
RabbitMQ 3.6.14 on Erlang 19.3

Custom Docker image created to add the:
`RUN rabbitmq-plugins enable --offline rabbitmq_mqtt`
`EXPOSE 1883`
Commands to enable MQTT.

Docker started with:
`docker run -d --hostname rabbit --name rabbit -p 8080:15672 -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_mqtt.retained_message_store [mqtt.retained_message_store [rabbit_mqtt_retained_msg_store_dets] mqtt.retained_message_store_dets_sync_interval [2000]]" rabbit-mqtt`
to enable message retention to disk.

There is what appears to be a bug in that retained messages are not sent to a receiver which starts after the retained message is set and which uses a wildcard to subscribe.

Simple send code:
```
import paho.mqtt.client as mqtt
import time

broker_address="172.17.0.2" 
client = mqtt.Client("sender", False, mqtt.MQTTv311)
client.connect(broker_address)

client.publish("/examples/test1", "test 1 Retained", retain=True)
client.loop()
```

Simple receive code:
```
import paho.mqtt.client as mqtt
import time

def on_message(client, userdata, message):
	print("received topic %s QoS %d RF %d received message %s" % (message.topic, message.qos, message.retain, str(message.payload.decode("utf-8"))))

broker_address="172.17.0.2" 
client = mqtt.Client("listener", False)
client.on_message=on_message
client.connect(broker_address)
client.subscribe("/examples/test1", 1)	<-- This works
client.subscribe("/examples/#", 1)      <-- This does not
client.loop_forever()
```

To reproduce the issue:
Comment out one of the two subscribes.
Start receiver `python receive.py`
Run sender `python send.py`

Messages will be sent and received as expected.
Exit receiver and restart it.

If the subscription is to the specific topic, the retained message is received.
If the subscription is to the wildcard topic, the retained message is not received.

Using VerneMQ, the retained message is always received using either subscription form.

**Comment by sobelman** [comment]
Such a common use case.... can't figure how its not supported yet.

**Comment by lukebakken** [comment]
> can't figure how its not supported yet

Comments like the above do not help the discussion. This is the reason why this feature is not yet supported:

> there are much higher priority items for the core team, even in this plugin alone

Everyone who has commented here, please take note of the "Sponsors" section of this feature added to RabbitMQ:

https://github.com/rabbitmq/rabbitmq-server/pull/2654

**Comment by Webbeh** [comment]
Hi everyone. 

We recently switched to RabbitMQ from MQTT for professional reasons, and were disappointed to see this very troubling issue. We use MQTT for our legacy applications and most of them use wildcard-based subscriptions for various reasons, and it is not really possible for us to do the switch to fully qualified topic names in most of those applications.

Returning to Mosquitto for MQTT could be an option if Mosquitto didn't fail us due to the high volume of messages.

We would like to know what it would take for this issue to be resolved as quickly as possible without disrupting your schedule.

Thank you very much!

**Comment by lukebakken** [comment]
> We would like to know what it would take for this issue to be resolved as quickly as possible without disrupting your schedule.

Pay VMware or another vendor to implement the feature. Erlang Solutions has provided excellent work for paying customers.

https://www.rabbitmq.com/#support

**Comment by Webbeh** [comment]
Thank you for your answer. We will contact them today.

**Comment by MichaelUray** [comment]
Is this issue actually still present in the current version of RabbitMQ?
If yes, is it somewhere on the roadmap for the near future to get fixed?

**Comment by michaelklishin** [comment]
It is. It's not the short term roadmap. Making the MQTT plugin significantly more efficient is, that's what the majority of users care about.

**Comment by mdellen** [comment]
Sad to see this is still an issue. Took me all night to figure out it was a limitation and I did not do anything wrong. I understand the decisions the dev. team have to make. For me this means looking for another solution as for my personal projects this is a must have.

**Comment by robbe-haesendonck** [comment]
I've noticed it seems this does not only relate to retained messages. Also QoS 0 and 1 in a clustered rabbitmq setup seem to not be able to subscribe to wildcards.

When I subscribe to specific topics, it does work.

**Comment by michaelklishin** [comment]
@robbe-haesendonck Please use GitHub Discussions for questions. This issue is about a specific change in the MQTT plugin.

RabbitMQ MQTT plugin does support wildcards and always has, even though due to an internally used topic structure separator that's different from that in MQTT, there is a couple of edge cases. 

We'd need an executable way to reproduce what you see (using Mosquitto CLI tools or a piece of code)>

**Comment by ansd** [comment]
Closing in favour of https://github.com/rabbitmq/rabbitmq-server/issues/8824
