### ISSUE TITLE
Support for more general OAuth2 providers

### ISSUE THREAD

**Issue by MirahImage** [rabbitmq/rabbitmq-server#2605]
When using the `rabbitmq-management` plugin with the `rabbitmq-auth-backen-oauth2`, users are redirected to the OAuth server to authenticate following an implicit_grant flow. The plugin makes several assumptions about the structure of the endpoints provided by the OAuth server, not all of which are valid.

1. The authentication endpoint is assumed to be at the location `uaa_location/oauth/authorize`. While the use of `/authorize` is general as specified in [RFC 6749](https://tools.ietf.org/html/rfc6749#section-3.1), the prefix of `/oauth` is specific to UAA.
1. The `/info` endpoint is not general. [RFC 8414](https://tools.ietf.org/html/rfc8414#section-3) specifies  that a generic OAuth2 server should provide the `/.well-known/oauth-authorization-server` endpoint for such purposes, but also that specific implementations may specify a different endpoint. For example, servers implementing OIDC may instead provide the `/.well-known/openid-configuration` endpoint.

In regards to the first point above, one solution would be to generalize the `uaa_location` advanced config to an `oauth_location` config property. In the specific case of UAA, the `oauth_location` would correspond to `uaa_location/oauth`.

Similarly, for the second point, we could provide an optional configuration for the metadata endpoint, with the default value being `/.well-known/oauth-authorization-server`.

**Comment by edbyford** [comment]
Pre-sales are asking for integration with CSP. JPMC also requested

**Comment by ngbrown** [comment]
@MirahImage Can you test against a few well known providers? Such as Azure AD, Google G Suite, 0Auth, etc. I got so far as getting Azure OAuth tokens working against `rabbitmq_auth_backend_oauth2`.

The way permissions are accepted only in an array is not ideal. Normally, in OAuth 2/OpenID, the requested, and authorized, scopes are echoed back in an `scp` field.

I got the current plugin to work using the Azure specific `roles` field, even this was not ideal as each permission had to be formatted with URL code escaping. Having lots of RabbitMQ specific roles for each read and write pattern you want to add really doesn't map to how roles should be managed.

I wanted a lookup table in the RabbitMQ config file that mapped specific scopes in the `scp` field, or an entry in some other array or space delimited field, to an expanded list of actual RabbitMQ permissions.

**Comment by MarcialRosales** [comment]
@ngbrown We are in the process of testing against more providers. Auth0 is already tested. You can check it out [here](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial#use-case-8-use-external-oauth-server-httpsauth0com). However, we have only tested it against the messaging protocols such as AMQP, not against the management ui. 

With regards the format of permissions, it can be a json array or a space-separated list of scopes within a single string. And RabbitMQ can be configured to read those permissions/scopes from a configurable field name such as `scp` rather than the standard name `scopes`. 

The OAuth2 specification does not say whether the scopes should be treated as roles. You are right that Azure uses `roles` but Oauth0 uses `permissions` though. I do understand what you propose which is that RabbitMQ resolves role names specified in the JWT token into RabbitMQ permissions. However, **roles** tends to be very dynamic not something we statically define in a configuration file. What you are asking seems to be possible to do in Azure using groups and role assignments to group and maybe when you assign a user to a group, that user automatically gets all the "roles" -which in our case would be permissions- assigned to him. This is the kind of role mapping done by Identity providers like Azure.

**Comment by ngbrown** [comment]
In Azure, it was possible to use the `roles` field and then assign users by group. You have to have a separate role per permission pattern in RabbitMQ. You also have to prefix the pattern with the application ID URI (ending with a `.`) for RabbitMQ.

I did try to use the `scopes` request and the `scp` response, but the issue there, was that Azure insisted on prefixing the application ID URI and separated with a `/` while RabbitMQ wanted a period (`.`).

Attempt to use `scope`/`scp` but didn't work, looked like this: `api://e280b497-4249-4fc0-ab84-e8b5c572872e/read%3Agroup1%2F%2A`.

So then adding to the `roles` array, you add them like this: `api://e280b497-4249-4fc0-ab84-e8b5c572872e.read:group1/*`. Which I guess is workable, but if you have a few permission patterns, and a few user groups, you have a combinatorial (Patterns x Groups).

I look forward to the management UI being able to participate in SSO via other providers such as Azure AD.

**Comment by lukebakken** [comment]
> I got so far as getting Azure OAuth tokens working against rabbitmq_auth_backend_oauth2.

@ngbrown it would be very helpful to share a project demonstrating this.

Testing OAuth against several providers is _extremely_ time consuming to set up and maintain. Anything users can do to assist will speed up that process is appreciated.

**Comment by MarcialRosales** [comment]
Hi @ngbrown , we are working on supporting **scope mapping** so that your tokens may carry scopes in any format your Idp requires and yet we can configure RabbitMQ to map those custom scopes into RabbitMq's scopes.

This work is being track here https://github.com/rabbitmq/rabbitmq-server/issues/4588 should you had any comments.

**Comment by baptistedaroit** [comment]
Hello @ngbrown, @MarcialRosales, @MirahImage,

I am currently trying to use Azure AD to authenticate user to the UI management but I am blocked because of the issue mentioned here: I am redirected to `uaa_location/oauth/authorize` while Azure AD authorization endpoint is exposed at `uaa_location/oauth2/authorize` or `uaa_location/oauth2/v2.0/authorize`.

Is there currently a way to be update the expected endpoints so that I would be redirected to the right one?

@ngbrown:  from your previous posts, I understand that you managed to overcome it. Is it the case?

Thanks for your help!

**Comment by baptistedaroit** [comment]
Hi @MarcialRosales,

Thanks a lot for all your inputs.

So far, I have been able to configure RabbitMQ to use Azure AD as OAuth Backend for the Management UI.

I am quite new on Azure AD and OAuth2 in general so I wrote kind of a documentation to describe all the steps needed to set it up. Would you like me to enrich the tutorials to provide guidance for people who could be interested?

**Comment by MarcialRosales** [comment]
Awesome ! @baptistedaroit . In that case, feel free to create a PR to add another integration use case, in your case Azure. You know that we have under `use-cases` a folder dedicated to each Idp. Add one for Azure and then link it to the main Readme. If you can provide screenshots even better. I think I should do that with Oauth0 as it is not easy to explain it in plain words the amount of steps involved. But hey, that is just a suggestion :)

**Comment by baptistedaroit** [comment]
@MarcialRosales 

Thanks for the guidance!

I opened a PR [here](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/pull/8).

Feel free to comment so I can adjust it if needed :)
