### ISSUE TITLE
Adjust RabbitMQ disk limit alert to the size of node RAM

### ISSUE THREAD

**Issue by yaronp68** [rabbitmq/rabbitmq-server#2652]
RMQ has a disk alarm that defaults to 50MB. We can assume that even dev environments will have few GB of free disk space. This limit seems outdated. Suggest we will change this limit to the size of RAM which will satisfy user's need in most environments and will save the user from a need to override the default. This will also allows the K8s operator to create clusters without dealing with the alarms

**Comment by michaelklishin** [comment]
Unfortunately this assumption has not been true just a few years ago when this was last raised. Plenty of development environments had a small partition dedicated to `/var/lib`, which is where the node's data directory resides by default on Linux.

If the limit is too high, the node will immediately go into an alarmed state and no tutorials will work because all published messages beyond the first one will be blocked. This results in really terrible initial user experience.

In general it's hard to pick a good default for resource limits but setting it to the amount of available RAM means at least a few gigabytes, possibly even 16 or 32 GiB with modern laptops. This can exceed the size of the `/var/lib` partition easily.

RabbitMQ Docker image, which has at least some control over the deployment settings, can and likely does use a higher default. I am not aware of cases where disk alarms would be problematic for the Kubernetes Operator but resource limits is something entirely specific to a Kubernetes deployment, RabbitMQ cannot make a lot of assumptions about that.

In the end, the default is not only not dated, it is a safe and conservative option for development environments. Our [Production Checklist](https://www.rabbitmq.com/production-checklist.html) has covered resource limits for a while. Not everyone reads the docs but RabbitMQ cannot target only deployments with a few GiBs (or even tens of GiBs) of disk space.
