### ISSUE TITLE
Inconsistent type for channel_details when requesting queue admin data

### ISSUE THREAD

**Issue by tiljanssen** [rabbitmq/rabbitmq-server#2684]
The response to /api/queues/%2f/{queuename} has a consumer_details array of objects, where one of the fields is channel_details.
This field is an object if filled, but an empty array when no data is available.

In most cases the consumer_details array is empty, or there is a consumer and the channel_details are filled, but occasionally the a consumer_detail is returned with empty channel_details. I am using C# and the Json deserializer cannot handle the array where it expects an object. 

The problem occurs in a test setup where consumers are short-lived. The behavior causes a highly unreliable test result.

RabbitMq version is 3.8.9,  before this version we used 3.7.19 where we did not experience this problem.

**Comment by michaelklishin** [comment]
This is https://github.com/rabbitmq/rabbitmq-management/issues/701, https://github.com/rabbitmq/rabbitmq-management/issues/75 and https://github.com/rabbitmq/rabbitmq-management/issues/424 in a different place. With Erlang proplists there is no way to distinguish between an empty array and an empty object since they are lists of pairs.

I highly doubt this is something new in 3.8.

**Comment by Syuparn** [comment]
This still occurs in RabbitMQ 3.11.6 while a channel is being deleted.

```bash
# empty list appeared
$ curl -s http://user:pass@localhost:15672/api/queues/%2f/queue1 | jq .consumer_details[].channel_details
{
  "connection_name": "10.244.0.47:57414 -> 10.244.0.45:5672",
  "name": "10.244.0.47:57414 -> 10.244.0.45:5672 (1)",
  "node": "rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local",
  "number": 1,
  "peer_host": "10.244.0.47",
  "peer_port": 57414,
  "user": "user"
}
[]
```

This can be fixed by adding a format function to https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl#L543 as @michaelklishin suggested.

@deadtrickster 
Is there any plan for this issue? If not, I will make a PR.

**Comment by michaelklishin** [comment]
@Syuparn no need to ask for permission, you are welcome to submit a PR. Thanks.
