### ISSUE TITLE
Issue #758 still active on version 3.8.2 rabbitmq-management

### ISSUE THREAD

**Issue by VagosGrigoropoulos** [rabbitmq/rabbitmq-server#2710]
Rabbitmq : 3.8.2
Erlang-OTP: Erlang 23.2.1

Issue 758 on rabbitmq-management still active even if 759 backported on 3.8.x versions.My rabbitmq-managemt site missing consumer tab under queues.I trying to fix the code manually but still doesnt work.Is there any ways i can fix this problem?

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-management/issues/758 has its milestone set to `3.8.3`. We cannot suggest much because you haven't provided any details on what was backported and how. Please upgrade instead, I'm afraid our team won't spend any more time on `3.8.2`, `3.8.3` or any backporting of things to them. Once a release is out, it is out. It is followed up with other releases for as long as [the release series is maintained](https://www.rabbitmq.com/versions.html).
