### ISSUE TITLE
rabbitmq_auth_mechanism_ssl plugin login request default to guest user

### ISSUE THREAD

**Issue by shifty21** [rabbitmq/rabbitmq-server#2723]
Hi,

RabbitMQ version - 3.8.9
Running in docker

I am fairly new to rabbitmq and was trying to switch my rabbitmq authentication from custom-http-backend to ssl-authentication.
I have followed the https://www.rabbitmq.com/ssl.html and generated the certificates with hashicorp's vault.

I have tried with rabbit_auth_backend_internal auth_backend. The user is able to log in but the request log in rabbitmq shows the user as guest. Even though I have set ssl config to get name from common_name from client certificate.

rabbitmq log

> 2021-01-17 19:01:21.984 [info] <0.877.0> accepting AMQP connection <0.877.0> (172.19.0.1:60394 -> 172.19.0.3:5671)
2021-01-17 19:01:22.002 [info] <0.877.0> connection <0.877.0> (172.19.0.1:60394 -> 172.19.0.3:5671): user 'guest' authenticated and granted access to vhost '/'
2021-01-17 19:02:37.617 [warning] <0.877.0> closing AMQP connection <0.877.0> (172.19.0.1:60394 -> 172.19.0.3:5671, vhost: '/', user: 'guest'):

Available connections list output and openssl client certificate subject

> root@4edda5f28f42:/home/certificates/client# rabbitmqctl list_connections peer_cert_subject
Listing connections ...
peer_cert_subject
CN=ssltest
>abhishekchoudhary@Abhisheks-MacBook-Air client % openssl x509 -noout -in client.crt -subject
subject= /CN=ssltest

Configuration

> auth_mechanisms.1 = EXTERNAL
auth_backends.1 = rabbit_auth_backend_internal
auth_mechanisms.2 = PLAIN
listeners.ssl.default = 5671
ssl_options.cacertfile = /home/certificates/Combined_CA.crt
ssl_options.certfile   = /home/certificates/server/server.crt
ssl_options.keyfile    = /home/certificates/server/server.pem
ssl_options.verify     = verify_peer
ssl_cert_login_from = common_name
ssl_options.fail_if_no_peer_cert = true
loopback_users = none

Enabled plugins
 * rabbitmq_prometheus
 * rabbitmq_auth_mechanism_ssl
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent

If I remove loopback_users config then as expected it gives an error that guest is only allowed to login via localhost. Although the request should be of ssltest user.

I expected the user to be ssltest but no matter what I try its still comes as guest in logs.
I have created ssltest, CN=ssltest user with permission to ssltest host.

Any help appreciated. Thanks!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You still have

```
auth_mechanisms.2 = PLAIN
```

enabled. If earlier mechanisms or backends refuse authentication, the latter will be tried. Modern versions log a reasonable amount of information at [`debug` level](https://www.rabbitmq.com/logging.html). Enable it and see what's really going on.
