### ISSUE TITLE
`rabbitmq-queues rebalance all` (sometimes) doesn't comply with the mirroring policy

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#2737]
Problem:
---
`rabbitmq-queues rebalance all` (sometimes) doesn't comply with the HA policy
Given the following policy:
![Screenshot 2021-01-21 at 16 48 21](https://user-images.githubusercontent.com/386987/105375212-d223fe00-5c08-11eb-8c30-45b8998c2c60.png)

The `rebalance` add two mirrors instead of one, see:
![Screenshot 2021-01-21 at 16 52 54](https://user-images.githubusercontent.com/386987/105375822-58404480-5c09-11eb-9890-b9993df99ea6.png)

How to reproduce:
----

- Start a cluster with two nodes
- Apply the policy
- Create ~ 200 queues with 5.000 messages
- scaling up to five nodes
- apply `rabbitmq-queues rebalance all`

**Comment by dcorbacho** [comment]
This issue can happen occasionally due to the way classic queues manage mirrors. It won't cause data loss and can be resolved by running the rebalance operation again.

Given the usually high effort taken to resolve race conditions on mirrored queues, expected low occurence and impact of this issue, and mirrored queues being slowly replaced by new queue types, this issue won't be fixed (at least for the time being).
