### ISSUE TITLE
Reduce default QI (queue index) journal size

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#279]
See #227 for background.

Profiling suggests that the bottleneck in #227 is sequential folding over QI journal. While we will look into parallelising it, the need for reducing I/O by having a larger journal seems a lot less relevant in 2015 than it was ~ 5 years ago.

Benchmarks and monitoring results from multiple people suggests values such as `16K` or `8K` result in much more even throughput.

We've agreed to reduce default journal size from `65536` to `8192`.

**Comment by michaelklishin** [comment]
After discussing with, this means tweaking `SEGMENT_ENTRY_COUNT`, and we may want to look into making it configurable.

**Comment by videlalvaro** [comment]
After running some tests over the weekend I think it'd be wise to play with the values for IO_BATCH_SIZE from here https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_variable_queue.erl#L326 `2048` is way too low in my tests.

The next thing to change then is CREDIT_DISC_BOUND https://github.com/rabbitmq/rabbitmq-server/blob/master/include/rabbit.hrl#L127 You can have a big IO_BATCH_SIZE all you want but then every 2000 msgs or so you get control_flow'ed. 

I think having my changes from #227 make `queue_index_max_journal_entries` less relevant than before, and make these two constants more relevant.

`IO_BATCH_SIZE` is quite relevant since it affects when `push_betas_to_deltas` is called and with how many items.  `push_betas_to_deltas` then calls `rabbit_queue_index:publish` which does quite some work per message and might flush the journal (I have a 5GB fprof dump where I checked some things).

**Comment by michaelklishin** [comment]
This is less relevant if we avoid the expensive fold but it is still relevant to getting data to disk more frequently. I see no good reason to have a 65K entry journal.

With changes from #227, the only significant throughput drops I observe with the publishers outpacing consumers test is from flow control, which is expected.

**Comment by videlalvaro** [comment]
I think we are talking about slightly different points:

- Reducing the journal size, might make sense, and since we don't fold anymore, flushing an 8k items journal should be pretty fast. So that's fine.

- About `IO_BATCH_SIZE` this controls how many messages get persisted on a single run, I think an `IO_BATCH_SIZE` with a default of 2048, is VERY conservative. Just compare that with the amounts of elements in the journal.

>  the only significant throughput drops I observe with the publishers outpacing consumers test is from flow control, which is expected

Yes, this is expected, but again, having a default `CREDIT_DISC_BOUND` of 2000 messages is very conservative as well.

So I think we should consider all these constants together, since the original issue reported on the ML was that if there are no consumers, performance drops terribly. I know we are not going to fix the unbounded queues problem, but at least we can let the users tune RabbitMQ for their workload. I've managed to get decent results by tweaking these values and setting a max publisher rate per second.

**Comment by michaelklishin** [comment]
@videlalvaro this issue is only about QI journal size and values that depend on it. Your suggestions may be perfectly relevant with or without this change but should be discussed in a separate issue.

**Comment by michaelklishin** [comment]
Fixed in #281.
