### ISSUE TITLE
Queue definition import declares queues on the importing node only

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#2836]
Given the following 2 queues, each running on one of the 2 nodes started with `make start-cluster`:

```
sbin/rabbitmqctl -n rabbit-1 list_queues name,pid
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name	pid
q1-rabbit1	<rabbit-1@focker.1613133932.1355.0>
q2-rabbit2	<rabbit-2@focker.1613134057.1979.0>

definitions="$(sbin/rabbitmqctl -n rabbit-1 export_definitions -)"

sbin/rabbitmqctl -n rabbit-1 stop_app
sbin/rabbitmqctl -n rabbit-2 stop_app

sbin/rabbitmqctl -n rabbit-1 reset
sbin/rabbitmqctl -n rabbit-1 start_app

sbin/rabbitmqctl -n rabbit-2 reset
sbin/rabbitmqctl -n rabbit-2 start_app

echo "$definitions" | sbin/rabbitmqctl -n rabbit-1 import_definitions
sbin/rabbitmqctl -n rabbit-1@focker list_queues name,pid
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name	pid
q1-rabbit1	<rabbit-1@focker.1613133932.2828.0>
q2-rabbit2	<rabbit-1@focker.1613133932.2831.0>
```

I was expecting queues to retain node location. This is especially important when re-creating environments for troubleshooting purposes.

I don't want to add more context than necessary, but backing up and restoring data volumes would also benefit from this behaviour which feels natural. If we can select the node where to place a queue when declaring it via Management, it implies that support for this already exists, but it's not consistent:
![image](https://user-images.githubusercontent.com/3342/108751231-df027d00-7539-11eb-8aea-764f76216e4b.png)

Somewhat related, but not in scope for this particular issue, is respecting `queue_master_locator`. My preference would be for definition import/export to behave as described above, but I can see how that may not be desired in certain scenarios. In that case, if we respected `queue_master_locator` at least we would end up with an even spread of queues, rather than all of them ending on the node that ran the import. While we have the option of rebalancing Quorum Queues, we cannot do this for non-replicated queues or, less important, classic mirrored queues.

To work around this limitation, we had to split a 163MB definitions export into 3 separate files, and then import it three times, once per node. This took about 2h in total. I wouldn't like anyone to have to use that work-around again, and I'm not looking forward to doing that again either.

**Comment by michaelklishin** [comment]
We cannot do both. Node names are not guaranteed to be identical between clusters (in fact, more often than not they are different). Using queue master locator during definition import is doable.

**Comment by gerhard** [comment]
OK, that is a good compromise.

**Comment by mkuratczyk** [comment]
I've run some tests and the results are:
1. Master locator is used during import. The problem you see is because the default strategy is `client-local` and therefore all queues end up on the node where the import is run. When I `start-cluster` with `RABBITMQ_CONFIG_FILE` pointing at a file with `queue_master_locator = random` then the imported queues are spread between nodes (same with `min-masters`). I guess there is a case to be made that `random` could be the default strategy.
2. The Management UI node selection (as well as `rabbitmqadmin declare queue node=X`) is only effective when `client-local` is used. With `random` and `min-masters`, queues are declared on the node selected by the strategy, not the one specified. I guess this could be considered a bug.

**Comment by michaelklishin** [comment]
We have discussed this with @mkuratczyk and @deadtrickster and some observations were:

 * QQs do not use queue leader locators because in Raft, there is no concept of a pre-assigned leader (every leader is elected using the election process)
 * At the end of the deployment, queue leaders can be rebalanced. Deployment tools have more context on when it is optimal to do so.
 *  Definition import does not have much context (it may run at the time when there are no other cluster nodes at all)

So while definition import can use queue leader locators or be configured with a leader locator setting, it alone cannot guarantee reasonably even queue distribution for some deployment scenarios.

**Comment by mkuratczyk** [comment]
I'm closing this issue since a lot has changed in the last few years. Leader locator strategies are now `local` and `balanced` and can be used for CQs, QQs and streams. Imports honour these settings as well. I believe there's nothing to be done here and if there is - let's open a new issue with fresh assumptions.

**Comment by michaelklishin** [comment]
The leader locator is now respected at definition import time (at least in some cases).
