### ISSUE TITLE
3.8.13 package for RHEL-8 is broken

### ISSUE THREAD

**Issue by assen-totin** [rabbitmq/rabbitmq-server#2855]
The BinTray repository says it is owned by you:
https://bintray.com/rabbitmq/rpm/rabbitmq-server/3.8.13-1

The RHEL-8 package for 3.8.13 is broken - server refuses to start with 

```
{"Kernel pid terminated",application_controller,"{application_start_failure,credentials_obfuscation,{{shutdown,{failed_to_start_child,credentials_obfuscaton_svc,{undef,[{crypto,macN...
```

The likely reason is here:
https://github.com/rabbitmq/credentials-obfuscation/blob/master/ChangeLog.md#changes-between-230-and-240-february-18-2021

```
The library now supports Erlang 24 and drops support for Erlang versions < 22.1.
```

RHEL-8 only ships Erlang 22.0:

```
[root@localhost assen.totin]# rpm -q erlang
erlang-22.0.7-1.el8.x86_64
```

This needs some attention as the Erlang package in RHEL-8 is not (yet) modular, hence no update of the major or minor version is expected during the lifecycle of the product - and next major RHEL version is still 3 years away.

**Comment by michaelklishin** [comment]
Latest RabbitMQ releases require [Erlang/OTP 22.3 or later](https://www.rabbitmq.com/which-erlang.html). This has been the documented case since `3.8.9`, which shipped in September 2020. So the package is not broken, your system does not provide a supported Erlang version.

Our team produces [zero dependency Erlang RPMs](https://github.com/rabbitmq/erlang-rpm) that go up to `23.2.5` at the moment.

Please also be aware of the fact that Bintray the service [goes away on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). So perhaps you should consider installing packages from GitHub (an easy option with RPMs) or PackageCloud.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
