### ISSUE TITLE
~/.rabbitmqadmin.conf ignores ssl_insecure and ssl_disable_hostname_verification

### ISSUE THREAD

**Issue by robertdahlem** [rabbitmq/rabbitmq-server#2889]
RabbitMQ 3.8.12

Adding `ssl_insecure = True` to `~/.rabbitmqadmin.conf` under `[default]` should be the equivalent of adding `-k` to the command line, but it does not work.

To reproduce:
- set up RMQ host with SSL certificate for `my.fqdn` listening on port 15671
- `cat ~/.rabbitmqadmin.conf`
```
[default]
ssl = True
port = 15671
ssl_insecure = True
```
- `# rabbitmqadmin  -u MYUSER -p PASSWORD declare exchange name=dummyexchange`
`ssl.CertificateError: hostname 'localhost' doesn't match 'my.fqdn'`
- `# rabbitmqadmin  -k -u MYUSER -p PASSWORD declare exchange name=dummyexchange`
`exchange declared`
The same problem applies to `ssl_disable_hostname_verification`.

**Comment by michaelklishin** [comment]
I don't see where we mention this as supported in the docs. These options can be necessary in some environments but I don't know if we want to encourage their use in this "permanent" manner.

**Comment by michaelklishin** [comment]
Since `rabbitmqadmin` is a zero dependency Python script, those who really want it to work differently can modify it and deploy their version quite easily. It does not change often so the risks of doing so, in particular for local development, are low.

**Comment by gerhard** [comment]
I can see how this could be useful for self-signed certs.

Knowing that we not only support, but also [default to disabling hostname verification in PerfTest](https://github.com/rabbitmq/rabbitmq-perf-test/blob/e5e324b4acc6a59b6ca4020f3fd13e82dfeb3380/src/docs/asciidoc/usage-advanced.adoc#tls-support), this issue not unreasonable.

I would personally welcome a PR that adds this feature, inclusive of the docs part. Regardless of what we decide to do, we should be consistent across both PerfTest & rabbitmqadmin.

WDYT @michaelklishin?

**Comment by michaelklishin** [comment]
I'm not saying that disabling peer verification is unreasonable but doing so on a permanent basis is not something we see often. If you use self-signed certificates you can add them to the trusted list and solve this problem for every tool at once.

I'd investigate if other TLS-related options were not merged from the config but these ones? You have several options already:

 * Trust the certificate
 * Pass the options on the command line, possibly via a shell alias
 * Run your local version of `rabbitmqadmin` since it's a small zero dependency tool

This change would require additional testing which would not be easy to automate (you'd need nodes with different certificates configured, for example) and it feels difficult to justify that effort, unlike, say, if essential TLS options were not loaded or merged.

FTR, here is where the [TLS context is initialized](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_management/bin/rabbitmqadmin#L581-L599) and here is where [the config options are merged](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_management/bin/rabbitmqadmin#L455-L479).

**Comment by michaelklishin** [comment]
I'm not saying that disabling peer verification is unreasonable but doing so on a permanent basis is not something we see often. If you use self-signed certificates you can add them to the trusted list and solve this problem for every tool at once.

I'd investigate if other TLS-related options were not merged from the config but these ones? You have several options already:

 * Trust the certificate
 * Pass the options on the command line, possibly via a shell alias
 * Run your local version of `rabbitmqadmin` since it's a small zero dependency tool

This change would require additional testing which would not be easy to automate (you'd need nodes with different certificates configured, for example) and it feels difficult to justify that effort, unlike, say, if essential TLS options were not loaded or merged.

FTR, here is where the [TLS context is initialized](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_management/bin/rabbitmqadmin#L581-L599) and here is where [the config options are merged](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_management/bin/rabbitmqadmin#L455-L479).

**Comment by robertdahlem** [comment]
I probably have been naive, not knowing much python. I have just been wondering why `ssl_insecure` is mentioned in `make_parser()` and is not getting through.

**Comment by gerhard** [comment]
That was my understanding as well @robertdahlem: disabling hostname verification via `ssl_insecure = True` should work, but according to your findings doesn't, which is an issue.

I may not have time to dig into this today, but I intend to come back to it.

Are you saying that it works for you @michaelklishin as expected?
