### ISSUE TITLE
improve queue purge performance

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#295]
There's a couple of TODOs related to queue purge performance improvements: that we should address on this issue: 

https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_variable_queue.erl#L554

**Comment by greggwon** [comment]
Both purge and delete need to be asynchronous actions.   Delete needs to hide the queue as it is deleted in the background.  It should be possible to have a huge non-durable queue happen because a service is not running, and be able to delete that queue and start the service immediately.  Huge outages get created when non-durable queues have transient traffic in them due to some error which you'd like to fix "right now", but are stuck waiting for 10s of minutes for millions of records to be deleted from a queue that you just deleted.

**Comment by michaelklishin** [comment]
@greggwon it's important to remember that both operations have to follow protocol semantics. For example, there is a response for each method (`queue.delete-ok` and so on) and every client I can think of awaits it by default. Then queues must guarantee that all operations are applied in order. Combined with message reference counting (a message routed to N queues will not be stored N times), it gets a little more involved than doing deleting "in the background".

There are plans to revisit certain parts of the message store and queue operation logs by 3.8 and 4.0.
First step towards that in 3.7.0 is per-vhost message stores: each virtual host has its own pair of message stores, so wiping a vhost can be done very efficiently.

This discussion belongs to rabbitmq-users.
