### ISSUE TITLE
Debian packages hang on Erlang 24

### ISSUE THREAD

**Issue by pjk25** [rabbitmq/rabbitmq-server#3058]
The API for `socket:bind/2` has changed in Erlang 24, in a manner that breaks systemd integration via https://github.com/hauleth/erlang-systemd

https://github.com/hauleth/erlang-systemd/pull/29 has already been merged, so this should simply be a matter of updating the dependency in `deps/rabbit/Makefile` and `workspace_helpers.bzl`.

**Comment by dumbbell** [comment]
For the record, this is unrelated to Debian. It is related to the fact we failed to notify systemd, which means `systemctl start rabbitmq-server` would never return. It happens to block the installation of the Debian package because a service should be started as part of the postinst step per Debian Policy.

But the problem would have been the same on any Linux distribution using systemd. Even if there is no policy saying the service should be started when the package is installed, as soon as the admin would start the service manually or enable automatic start at boot time, it would hang the same way.
