### ISSUE TITLE
Creating a queue with invalid name by moving messages

### ISSUE THREAD

**Issue by kaanyilgin** [rabbitmq/rabbitmq-server#3074]
It is possible to create a queue with a name longer than the maximum character limit by moving the messages.

I tried to create a queue with the same name via "Add a new queue" panel and it doesn't let me create it. However, it is possible while moving messages. Also, it is not possible to delete the queue by using UI or HTTP API because it returns “414 Request-URI Too Large”.

Reproducing steps:

- Create a queue
- Publish a random message
- Copy the response of https://swapi.dev/api/people/ to use it as the name
- Move the message to a destination queue with the name of the copied json.

**Comment by lhoguin** [comment]
The problem we should fix here is the fact that a queue can be created with a name that is longer than allowed when we try to delete it via the UI. This likely happens because the queue is created with a name in the POST body and deleted with the name in the query string part of the URI. The solution is likely to be increasing the maximum request URI length, or limiting the queue name size when it is created.

I will take a closer look when time allows. Thanks!

**Comment by michaelklishin** [comment]
It sounds like something specific to the HTTP API. `queue.declare` frames issued by a client should go over not one but two validations (in the protocol parser then the channel operation).
