### ISSUE TITLE
consumer_timeout cannot be disabled via text based config

### ISSUE THREAD

**Issue by PiotrZakrzewski** [rabbitmq/rabbitmq-server#3096]
According to the consumer [docs](https://www.rabbitmq.com/consumers.html)
`consumer_timeout` can be set to `false` via a file config like so:
```
# disable the timeout
consumer_timeout = false
```
when I try this on Rabbitmq-server 3.8.17 (via the official Docker image)
I get
```
12:55:52.477 [error] Error preparing configuration in phase transform_datatypes:
12:55:52.479 [error]   - Error transforming datatype for: consumer_timeout
12:55:52.479 [error]   - "false" cannot be converted to a(n) integer

12:55:52.480 [error] 
12:55:52.480 [error] BOOT FAILED
12:55:52.480 [error] ===========
```
`0` is also not accepted in this config.
The same value (false or 0) seems to be accepted via the ENV var mini-DSL thingy but it is not clear if it is actually disabled.

**Comment by michaelklishin** [comment]
It cannot be disabled via `rabbitmq.conf` but it can be disabled via `rabbit.consumer_timeout` in `advanced.config`.
https://github.com/rabbitmq/rabbitmq-server/pull/3090 must have assumed that `rabbitmq.conf` validator would allow for
a `false` value.

I don't know what the "mini-DSL thingy" is.

**Comment by michaelklishin** [comment]
``` erl
%% advanced.config
[
  {rabbit, [
    {consumer_timeout, undefined}
  ]}
].
```

(or any non-integer value) would disable the timeout. I would not recommend disabling it as it exists for a reason.
The default in `3.8.17` is already 30 minutes which should be enough for a very large % of applications, and it can be set to
an hour or more. If delivery processing takes several hours, I don't know how you can distinguish a stuck consumer
from an operating slower one but not having any timeout is not a great solution.

**Comment by PiotrZakrzewski** [comment]
We wanted to disable it becase we schedule ETA tasks far in the future and that (apparently) raises PrecondtionFailed exception.
My SO q on that: https://stackoverflow.com/questions/67907336/celery-task-with-a-long-eta-and-rabbitmq/67911386#67911386

**Comment by bholland** [comment]
This was a really terrible change. There are loads of reasons why you would want to have no timeouts. In my use case it is because we are doing very large SQL queries on a shared server so a query can run anywhere between 10 minutes and 3 hours depending on load. I never worried about something getting stuck in the more than year that I have used rabbitmq but I do worry that this broke by entire setup that was working.

**Comment by antoine-pous** [comment]
This breaking change is a bad joke

**Comment by bholland** [comment]
I 100% agree with the sentiment though not the frustration. It should
accept a 0 value. I found 6h to be sufficiently large enough time for my
use case for rabbit but honestly, I do not understand this development
idea. You can always add existing functionality but should never change the
default. A lot of people rely on defaults being the default. If people
wanted an error after 15m, that is a feature and should require additional
configuration.

Also, for the docker example, I would be a very good idea to provide a
working example for setting this in the configuration directory since the
rabbit configuration gets overwritten on startup.

Thanks,
Ben

**Comment by antoine-pous** [comment]
I have more and more call from clients due to this feature. You must never change the default behavior on any product which is already in use at large scale.

Due to that those clients asking to move away of RMQ, for them RMQ behavior is not trustrable anymore, this is a trully waste of energy and time for me. You can't imagine at which point i'm disapointed...

**Comment by davidemerritt** [comment]
+1 - changing defaults is very unexpected and threw a wrench my way.
