### ISSUE TITLE
Switch hostname detection to use Erlang

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#402]
Filing retroactively for https://github.com/rabbitmq/rabbitmq-server/commit/1fb451090a2557f35a2800f9d04c476ff1ad6a22 since it can be a breaking change (we will see if it actually is in practice).

@dumbbell came up with the idea of using Erlang for hostname detection. In certain environments (Windows, containers), env variables and CLI tools sometimes result in a different hostname being detected from OTP, e.g. the case is different.

This seems to improve things at the expense of ignoring the `HOSTNAME` env variable.

It's difficult to predict how we will this is going to work. `RABBITMQ_NODENAME` is still going to work. We can also revert this in `3.6.x` if it does more harm than good.

**Comment by dumbbell** [comment]
Ok, here is the full explanation after finishing the investigations.

On Windows, we definitely had a problem: on my Windows 8.1 laptop, `rabbit@%COMPUTERNAME%` is `rabbit@ROSETTA` but `erl -sname rabbit` becomes `rabbit@rosetta`. Only the case changes and both names resolve to the correct IP address. But something in Erlang makes both names incompatible: when `rabbit@rosetta` is running, pinging `rabbit@rosetta` succeeds, pinging `rabbit@ROSETTA` fails. So we will **keep the change in `rabbitmq-env.bat`**. This means `%COMPUTERNAME%` is not used anymore which is a breaking change in RabbitMQ 3.6.0.

The other host where we had a problem was Travis CI's docker image. Here, `rabbitmqctl` without `-n <nodename>` or `$RABBITMQ_NODENAME` let to `rabbitmqctl` trying to contact `rabbit@localhost`. After multiple tests on Travis (see rabbitmq/playground@f83bb055 and https://travis-ci.org/rabbitmq/playground/builds/89185004), this has nothing to do with inconsistencies between hostname(1) and the name picked by Erlang (when using `erl -sname rabbit`): the Travis environment comes with a `/etc/rabbitmq/rabbitmq-env.conf` containing `NODENAME=rabbit@localhost`. Therefore, I will **revert the change in `rabbitmq-env`**.

I will file a new issue so that, in the testsuite, we ignore `/etc/rabbitmq/rabbitmq-env.conf`.

**Comment by apollosaar** [comment]
shit~

**Comment by SharkFourSix** [comment]
I changed my computer's name and now I get this:

````
rabbitmqctl status
Status of node rabbit@<...> ...
Error: unable to perform an operation on node 'rabbit@<...>'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@<...>

DIAGNOSTICS
===========

attempted to contact: [rabbit@<...>]

rabbit@<...>:
  * connected to epmd (port 4369) on <...>
  * epmd reports node 'rabbit' uses port 25672 for inter-node and CLI tool traffic
  * TCP connection succeeded but Erlang distribution failed

  * Authentication failed (rejected by the remote node), please check the Erlang cookie


Current node details:
 * node name: rabbitmqcli45@<...>
 * effective user's home directory: D:\Users\Administrator
 * Erlang cookie hash: WFZ9wSoh2JEG9QHdDBBJ0g==
```

Also, I installed RabbitMQ on Windows as an Administrator but I get cookies in both current user and admin's home directories, which, ironically won't let me interact with rabbit from a standard user account. I had to enable Web Management plugin

I personally think binding to the computer/hostname is not a good idea because it breaks stuff and leads to loss of data because I couldn't figure out a way to rename/copy the data over. Some of the data files are not text edit-able.

F***king stupid.

**Comment by michaelklishin** [comment]
@SharkFourSix leaving comments on a 4 year old issue, strong language and name calling are not a very productive way of provide feedback to open source software.

I'm afraid that's how Erlang distribution works: node names have a hostname part, and authentication requires that target node name to be consistent on both CLI and target node end. RabbitMQ cannot changes this.

The only place where RabbitMQ itself uses host name by default is [the node data directory name](https://www.rabbitmq.com/relocate.html). That can be overridden. [`rabbitmqctl rename_cluster_node`](https://www.rabbitmq.com/rabbitmqctl.8.html#rename_cluster_node) was introduced years ago to update all internal database entries when hostname changes.
