### ISSUE TITLE
Log a warning when a file handle cannot be obtained in N seconds

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#413]
Issues [like this one](https://groups.google.com/forum/#!topic/rabbitmq-users/uNJAT_nKANI) with insane ulimit defaults in most OSes are increasingly common. We should log a warning if a file handle cannot be obtained in a reasonable number of seconds, for example.

This can be fairly tricky to do because there are two key users of file handles: TCP acceptor pools (not just in the core but also plugins) and message stores. But we should be able to log things at least in the file handle cache: TCP clients would get a `ECONNREFUSED` or similar if a server socket cannot be opened anyway.

Another suggestion is to stop the node when this happens during boot. This is debatable.

**Comment by videlalvaro** [comment]
During boot we should stop the node if the queues cannot be recovered. If we know the amount of free file handles the node has, then we know in advance if this function will succeed or not:

https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_amqqueue.erl#L253

We can count the number of queues that need recovering, if that value exceeds the amount of available file handles, then I think there's no point in continuing booting the server.

Another approach could be here: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_queue_index.erl#L285 to ask `init_clean` and `init_dirty` to close the journal handle once they are done recovering the queue.

In that way we could at least boot, then the QI will take care of opening the Journal Handle on demand (this is handled automatically already). The problem still remains of what happens when the user has more queues than file handles. We could for example release idle file handles after N seconds.

What's for me is clear is that we can't boot a node without recovering all it's queues.

**Comment by videlalvaro** [comment]
@michaelklishin @dumbbell any decision on this?

**Comment by dumbbell** [comment]
What about implementing your first solution (comparing the number of queues and allowed opened files) to fill the gap, then go for the other solution on the longer term?

**Comment by videlalvaro** [comment]
@dumbbell I think both solutions are rather easy to implement. The Queue Index opens the Journal Handle on demand anyway, so that wouldn't be a problem.

Now, if the user starts using all these queues at the same time (via publishes/acks or whatever) then at some point it will still run out of file descriptors.

Stopping the server from booting and logging a clear error message will at least let the user fix the problem immediately

**Comment by dumbbell** [comment]
You are right, let's abort early.

**Comment by michaelklishin** [comment]
I don't have objections to stopping early. Of course, we should log something very visible, too.

**Comment by videlalvaro** [comment]
@michaelklishin should I assign this to myself then, and bring up a PR?

**Comment by michaelklishin** [comment]
@videlalvaro please do.

**Comment by videlalvaro** [comment]
@michaelklishin @dumbbell what should we do if the FHC reports and `unknown` ulimit like here: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/file_handle_cache.erl#L1523 ?

The `init` function there handles the `unknown` case like this: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/file_handle_cache.erl#L1089, assuming `1024` handles.

Shall I replicated what's done there? Assuming 1024 handles might still be unsafe

**Comment by michaelklishin** [comment]
@videlalvaro 1024 is the default value on Linux. I can't think of anything safer than what we already do.

**Comment by videlalvaro** [comment]
@michaelklishin OK, so at least now we know that RabbitMQ might hang like this during startup, so in the worst case somebody will come with this problem, but now we know what's going on

**Comment by michaelklishin** [comment]
@videlalvaro we can log something like "could not determine effective open file handles limit, assuming 1024 which is a low value"

**Comment by videlalvaro** [comment]
So this is not so simple: it's not just about counting the number of queues and comparing it to the number of available FHs. Queues that don't have recovery terms won't consume file handles, but eventually as the broker is used later on, they will. 

Safe solution: still alert the user when number_of_queues > number_of_file_handles, and stop booting.
Unsafe solution: if number_of_queues_with_recovery terms > number_of_file_handles, warning and stop booting.

Which one you prefer @michaelklishin @dumbbell ?
