### ISSUE TITLE
Direct Reply-To capability is not declared

### ISSUE THREAD

**Issue by tenor** [rabbitmq/rabbitmq-server#520]
The server does not declare the direct reply-to capability in server properties.
The only way a client can detect this is by parsing the version and checking if it's v3.4.0 or greater.
This is an error-prone method. Ideally, the server should declare this capability.

**Comment by michaelklishin** [comment]
Fair enough. Please submit a PR against `stable`?

**Comment by tenor** [comment]
My Erlang is not good enough to submit a PR. :smile:

**Comment by michaelklishin** [comment]
Actually, some may argue that we should not do this because server capabilities only demonstrate non-standard features. But I guess direct reply-to can be considered that.

Adding a capability is a [single line change](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L297).

**Comment by michaelklishin** [comment]
Yeah, we already list `per_consumer_qos` which is comparable to `direct_reply_to`.

**Comment by tenor** [comment]
I'll send a PR shortly.
The `direct_reply_to` capability is needed so the client knows if it needs to fall back to the older technique of creating/disposing callback queues.

**Comment by michaelklishin** [comment]
Will be in `3.6.1`.

**Comment by tenor** [comment]
Thanks!
