### ISSUE TITLE
Bump minimum required Erlang/OTP version for RabbitMQ 3.7.0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#546]
What the title says. `3.7.0` is scheduled for Q3 or Q4, 2016, so 18.2 doesn't seem particularly aggressive.

However, we'd need to bump standalone OS X release first as it is currently on 17.x.

**Comment by dumbbell** [comment]
I vote for Erlang 18.x because the maps implementation is much better apparently. We could get rid of the `time_compat` and `ssl_compat` modules at the same time.

**Comment by michaelklishin** [comment]
I vote for 18.x for a different reason: fewer obscure cipher suite issues for TLS connections, in particular with ECC.

**Comment by essen** [comment]
In addition to the previous comments:

I vote 18 for maps, because the syntax is more complete, and large maps are fast.

Going to 18 opens the way to eventually switching to Cowboy 2 (currently WIP) which would allow me to delete a lot of code in various parts of RabbitMQ and would also allow supporting HTTP/2.

18.2 would mean having some extra fixes for SSL that makes it easier to avoid it taking insane amounts of memory under specific scenarios. But 18.2 was a little broken on Windows and FreeBSD, so we need to require 18.2.1 at a minimum on those platforms (easy enough for Windows, since it's the last release listed on erlang.org; for FreeBSD we need to check if patches are in).

**Comment by michaelklishin** [comment]
@essen thanks, that's good to know. By the time 3.7.0 ships we'd have 18.4 or 18.5 or maybe even 19.0, so it's `18.x` vs `17.5`.

**Comment by dumbbell** [comment]
@essen: On FreeBSD, the package maintainer does a pretty good job. Erlang 18.2.2 is already available and is what you get if you ask for "erlang" (without specifying a version).

**Comment by dumbbell** [comment]
FYI, our test framework was fixed to work with Erlang 18.2; see rabbitmq/rabbitmq-test#29.

**Comment by hairyhum** [comment]
There are several nasty regressions in `18.3` like https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/42
Maybe it makes sense to set requirement to 18.3.x or 18.4

**Comment by michaelklishin** [comment]
We can bump it to `18.3` for now and `18.4` (or even `19.0`) at a later point. We have months to do that before 3.7.0 ships.

**Comment by dumbbell** [comment]
There are at least two regressions with TLS in 18.3.x:
* RabbitMQ doesn't boot at all with 18.3.2
* The ObjectiveC client fails to connect using TLS to RabbitMQ when it runs on 18.3.3.

**Comment by michaelklishin** [comment]
Effort medium as the number of PRs involved in this spans across our entire sub-project portfolio.
