### ISSUE TITLE
Evaluate the feasibility of using "lazy" queue mode by default

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#568]
"Lazy queue mode" makes more sense for most users, judging from some of the most common issues that come up on `rabbitmq-users` and in other support channels.

We should investigate switching queue mode to `lazy` by default and after a release or so consider removing the "variable mode" altogether. The gains from it are only visible to those using transient messages only and aren't particularly significant. Years of feedback suggest that the "variable mode" is a feature that creates technical operations pain.

**Comment by hairyhum** [comment]
"variable mode" - is current default mode?

**Comment by michaelklishin** [comment]
Correct.

**Comment by tenor** [comment]
I don't know what the numbers are but I think users that are mostly interested in transient messaging will be unfairly penalized by a default lazy queue.

I'd like to propose a default "hybrid" mode:
1. All queues are created as the current 'default' mode. 
2. When the backlog in a queue hits a certain size limit , then the queue is converted to a 'lazy' one.  
For non-durable queues this involves paging all current messages (a one time performance hit) and processing all new incoming messages lazily. For durable queues, all current messages will also be paged to disk to ensure non-persistent messages are also saved to disk.
*alternatively*
For both durable and non-durable queues, all current messages are still kept in the cache, but new messages (and the message that caused the cache limit to be hit) are processed lazily. The cache is never paged to disk since it never gets larger than a few MB.  
3. Once a queue has been converted to a lazy queue, it stays lazy until it is empty, then it is reconverted to a 'default' queue.

I think this proposal preserves the performance gains RabbitMQ brings to transient messaging while still meeting the goals set for lazy queueing.

**Comment by michaelklishin** [comment]
@tenor this is exactly the kind of thing we are trying to avoid: current default backing queue module is just way too complicated and tries to be very smart. It falls on its ass in practice. Default queues are much dumber and much more predictable.

It's not any more difficult to switch queue mode to "variable" than it is to "lazy" right now. This change is not going to ship until Q4 2016 anyway, so we may find all kinds of improvements to either mode before that.

**Comment by tenor** [comment]
@michaelklishin I see your point. 
Messages are committed to disk every 100ms or so. There may not be a significant performance drop for transient queues since many messages might go straight to the consumer and escape being committed to disk.

**Comment by mkuratczyk** [comment]
Classic Queues v2 in 3.12+ will always behave like lazy queues and will become the default (TBD whether they will become the default in 3.12 or later).
