### ISSUE TITLE
Update HiPE recommendations in the docs

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#58]
Post `3.5.0`, so filing it here.

HiPE seems to [have matured](https://www.cloudamqp.com/blog/2014-03-31-rabbitmq-hipe.html) and I couldn't find a HiPE-induced crash report on Erlang 17.x. I can, however, recall a couple of high profile users using it in production.

So maybe we should re-consider our position and recommend people to give it a try if throughput is a major concern for them.

**Comment by carlhoerberg** [comment]
We at CloudAMQP currently have 2 customers who run HiPE in production. 
1) uptime 150 days. RabbitMQ 3.3.4, Erlang 17.1. avg 1msg/s, ~3 conns, amqp, 1x t2.micro, single node
2) uptime 60 days. RabbitMQ 3.4.2, Erlang 17.4. avg 100msgs/s, ~400 conns, amqps, 2x c3.large, clustered

So very few of our users have enable HiPE, but the uptime on the once that have looks good and we haven't got a support email regarding HiPE since May last year (before we'd enabled Erlang 17).  

Did some benchmarks from an aws c3.2xlarge to a t2.micro instance. RabbitMQ 3.4.4 and Erlang 17.4.

```
Without HiPE
Startup time: 2 seconds

amqp, 1 producer, 1 consumer, autoack
moving avg 1min 16,551 msgs/s

amqps, 1 producer, 1 consumer, autoack
moving avg 1min 5,270 msgs/s

amqp, 1 producer, 1 consumer, manual ack
moving avg 1min pub 8,232 msgs/s
moving avg 1min sub 8,089 msgs/s
 ```
```
With HiPE
Startup time: 2 minutes

amqp, 1 producer, 1 consumer, autoack
moving avg 1min 27,817 msgs/s (70% faster)

amqps, 1 producer, 1 consumer, autoack
moving avg 1min 6,203 msgs/s (18% faster) 

amqp, 1 producer, 1 consumer, manual ack
moving avg 1min pub 13,219 msgs/s (61% faster)
moving avg 1min sub 12,421 msgs/s (53% faster)
```
```
AMQPS TLS connection properties
Protocol Version 	tlsv1
Key Exchange Algorithm 	rsa
Cipher Algorithm 	aes_256_cbc (no difference with aes_128_cbc)
Hash Algorithm 		sha
```

Summary: Get an up to 70% speed increase with HiPE for a 2min startup time penalty.

**Comment by michaelklishin** [comment]
@carlhoerberg thanks so much!
