### ISSUE TITLE
Add a test for changing the password of a user with non-standard password hashing function

### ISSUE THREAD

**Issue by edmorley** [rabbitmq/rabbitmq-server#632]
The issue described in #623 happened to be fixed by this commit:
https://github.com/rabbitmq/rabbitmq-server/commit/f1f28eac1bc955580bbead82721d75c45e69999d

However a testcase wasn't added. I think it might be good to add one :-)

From https://github.com/rabbitmq/rabbitmq-server/issues/623#issuecomment-183435313
> @edmorley I'm afraid adding a test that uses two different database schemas (from 3.5.x and 3.6.0) is going to be quite hard.
> 
> The best I can think of is manually injecting a user with a non-standard password hashing function. I have no objections to having an issue for that.

**Comment by hairyhum** [comment]
Will it be enough to have a test for changing `password_hashing_module` application env, while having user with different `hash_algorithm` and checking that after password change this user can connect?
We don't need to check upgrade in this case and inject non-standard users.
Because it was not upgrade issue, but password edit issue.

**Comment by michaelklishin** [comment]
@hairyhum I'd personally seed the user table with data that would mimic a 3.5.x user record migrated, and mess with application env less. But your suggestion is not unreasonable, my point was that having a real 3.5.x data directory is unnecessary in this case.

**Comment by edmorley** [comment]
Many thanks :-)
