### ISSUE TITLE
Old messages are not returned on re-connecting to the same queue

### ISSUE THREAD

**Issue by darshanmehta10** [rabbitmq/rabbitmq-server#640]
RabbitMQ Version : 3.6.0

I am using SockJS to connect to queue and read the messages. Below is the code:

    var sock;
    var stomp;
    var messageCount = 0;
    var stompConnect = function() {

    sock = new SockJS(options.url);

    stomp = Stomp.over(sock);
    stomp.connect({}, function(frame) {
    debug('Connected: ', frame);
    console.log(frame);

    var id = stomp.subscribe('<url>' + options.source + "." + options.type + "." + options.id, function(d) {
        console.log(messageCount);
        messageCount = messageCount + 1;
    }, {'auto-delete' : false, 'x-queue-name' : 'test_name', ack : 'client'});
    }, function(err) {
    console.log(err);
    debug('error', err, err.stack);
    setTimeout(stompConnect, 10);
    });
    };

For the first attempt, everything works fine. Queue is created (if it doesn't exist) and messages are returned.

However, if I disconnect and reconnect to the same queue, none of the queued messages is returned. Plus, the client keeps getting disconnected from the server (resulting in an infinite loop of re-connection), following message is printed:

`Whoops! Lost connection to <url>`

If I remove the ack header, all of the existing messages are drained from queue, but not returned to the client. However, client starts getting newly published messages afterwards. Re-connection attempt succeeds only if there are less than 500 messages in the queue (and they all are retrieved), it goes into connection loop otherwise.

I have tried tweaking heart beat timeout, handshake timeout and session timeout, also set automatic  recovery of connection to true, however messages are not returned in either case.

As per the stomp [documentation](https://www.rabbitmq.com/stomp.html), if I create a durable subscription, I should be able to get all the queued messages on re-connection.

**Comment by michaelklishin** [comment]
This issue belongs to `rabbitmq-web-stomp`, and probably even `rabbitmq-users` because there is no evidence that this is a bug.

The headers you use are

```
{'auto-delete' : false, 'x-queue-name' : 'test_name', ack : 'client'}
```

which DOES NOT mean you have a durable subscription: you didn't use the `persistent` (aka `durable`) headers. Please see [STOMP documentation](http://rabbitmq.com/stomp.html) and beware of [this issue in STOMP plugin 3.6.0](https://github.com/rabbitmq/rabbitmq-stomp/issues/58).

**Comment by darshanmehta10** [comment]
Thanks for the info. So, to analyze the behavior a bit, I tried with the following examples:

- headers : `{'auto-delete' : false, 'persistent' : true , 'id' : 'unique_id'}`

This creates a queue with name stomp-subscription-*, it has durable set to true and consumer has 'T_unique_id' tag.
I am able to connect and stream the messages. On killing the script, messages get queued up on queue, and on re-connection they get drained but none reaches to my client.

- headers : `{'auto-delete' : false, 'persistent' : true , 'id' : 'unique_id', 'ack' : 'client'}`

In this case, everything is same except that when I reconnect, it gets disconnected in 10 seconds without getting any messages (although there are 1000s of messages queued up). As the script has retry mechanism, it waits for 10 seconds and tries connecting again. This goes on forever and no message is received.

So, in NONE of these cases, I am able to get the queued messages back. As per the Stomp documentation, I have tried using 'durable' header instead of 'persistent', but no luck. Also, please note that, this only happens if the number of queued messages is more than 500, in other cases, the messages do come back.

**Comment by darshanmehta10** [comment]
@michaelklishin should I open another issue in rabbitmq-web-stomp then?

thanks

**Comment by michaelklishin** [comment]
There is no evidence that this is a bug. Like I said, questions belong to rabbitmq-users.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.
