### ISSUE TITLE
Feature request: dead-lettering for exclusive, autodelete and temporary queues

### ISSUE THREAD

**Issue by EmielBruijntjes** [rabbitmq/rabbitmq-server#6812]
In the past there have been some issues and pull requests to introduce a feature to allow dead-lettering messages from temporary and exclusive queues. See for example #29, #271 and #1299. This is for example useful when a client crashes that uses a exclusive queue, so that messages in the exclusive queue are not lost but sent to a different queue instead.

Although the RabbitMQ team seemed back then positive towards the underlying principle of this feature and acknowledged the usefulness of it, the pull request was rejected because of some concerns about the possible performance penalty to publish all messages back. Also in later discussions this was brought up again as reason to not implement this, and users were advised to build a more complex topology with per-message ttls and/or other tools to achieve similar solutions to avoid message loss.

We often use per-client queues because it allows for a scalable software design. But we often indeed find ourselves writing crontab scripts to scan and clean up abandoned queues, or we use complex algorithms with per-message TTL's and messages that are being pumped around to prevent message loss. An out-of-the-box RabbitMQ feature to create a temporary exclusive queue from which messages cannot be lost would be so much more helpful.

Is this still a feature that you have on your backlog?

**Comment by michaelklishin** [comment]
There is nothing specific about dead lettering of exclusive queues.

The behavior you are referring to has a simple explanation: dead lettering is not performed when a queue is deleted. There is a good reason for this, discussed numerous times over the years: dead lettering of millions of messages can put significant stress on the cluster when the user least expects it to, so at best this feature must be used with a length limit.

But specifically with exclusive queues, you are explicitly opting in for having your queues removed when the client disconnects for any reason. It makes no sense to ask for a feature that would help you preserve data when you opt in for the most transient queue type there is.

Just use a durable queue.

**Comment by michaelklishin** [comment]
Someone has suggested that if your goal is to have a single consumer on a queue with redundancy, there are [Single Active Consumer](https://rabbitmq.com/consumers.html#single-active-consumer) and exclusive consumer flag on `basic.consume`. The former is a much more convenient option to achieve that.

**Comment by EmielBruijntjes** [comment]
Hello @michaelklishin, I don't think that the Single Active Consumer technology is a solution for this problem. Nor is "just use a durable queue".

I was writing a use case with auto-scalers and Kubernetes to explain why this feature is necessary and why the number of queues can scale, and that new clients and queues might be created on the fly and that old queues might become abandoned, and that there are cases when people want to inspect or preserve the contents of such abandoned queues, etc. But to be brutally honest here: I am pretty sure that you understand the background of this feature request, and that you don't need this explanation and that you are aware that users use TTL tricks and/or REST API workarounds to deal with abandoned queues or with lost client connections as alternative for dynamic, auto-delete and/or per-client queues. I also think that it is not that hard for you and your team to come up with a better "out-of-the-box" solution for this, _for example_ by supporting dead-lettering - but if you have an alternative/better way to create reliable dynamic, auto-delete or per-client queues, that would be just as welcome.

The "it doesn't scale with large queues" argument sounds a bit odd to me. That why we're programmers, aren't we, to solve such things? This is already an issue if you add a policy with a max-queue-length and dead-letter-exchange to a large queue, so it sooner or later requires attention anyway.

Point is that we miss this ability to create dynamic reliable queues in RabbitMQ.

**Comment by lukebakken** [comment]
The discussion in #29 does a good job enumerating the issues with such a feature.

I can guarantee that if this feature were implemented users would immediately expect thousands of messages from thousands of transient queues to magically dead-letter with no performance impact.

**Comment by EmielBruijntjes** [comment]
Of course people want this feature to perform!

But honestly, is that a show-stopper here? From a programming perspective I would assume that the data is already in an internal data structure, and that a couple of pointers and references are updated to link the data to a different queue. This feature can indeed have a massively fast implementation, because everything stays _within_ RabbitMQ. From a user perspective I would indeed be surprised if this was giving performance issues.

But then again, as a user the implementation is not my concern. Nor is this 'dead-letter-exchange' feature per sé. The real point is that I would like to have an elegant way to create scalable reliable queues, and that we can inspect or reschedule messages that end up in abandoned queues. If you have a tip on how to do this, please share it with me. My current approach with crontabs and REST API calls, or by pumping TTL'ed messages around feels conceptually wrong.

**Comment by lukebakken** [comment]
>  From a programming perspective I would assume that the data is already in an internal data structure, and that a couple of pointers and references are updated to link the data to a different queue.

No, that's not how queues are modeled nor how the Erlang VM works.

> The real point is that I would like to have an elegant way to create scalable reliable queues

Like @michaelklishin said, use durable queues. Yes there is no out-of-the-box solution for transient queues that don't lose messages and you will have to be creative.

AFAIK we just haven't gotten enough requests for this feature (especially from paying customers) to implement it.

cc @edbyford @dcarwin-pivotal

**Comment by kjnilsson** [comment]
Whilst it is true that many of the people maintaining RabbitMQ are programmers they are also product maintainers which means we try very hard _not_ to dump effort into solving every problem users run into with code. In fact I'd say not taking on  too many features is the main responsibility of a maintainer of any product.

Despite @EmielBruijntjes claims that the problem is well understood I am not so sure it is so I am going to try to re-iterate as far as I understand it:

* Some systems need to dynamically create queues representing a "session" of some bounded length of time. In this case the queue itself is a physical representation of the client session and should exist for as long as the client session exists.
* At some point the session is finished or abandoned and the session state (the queue) needs to be cleaned up (deleted).
* If at this point there are unconsumed messages in the queue this should be noted and messages may need to be archived off for off-line inspection.

Does the above sound reasonable? I shall assume it does.

A couple of observations from the above:

* Exclusive and/or transient queues are not suitable for this kind of session queues. Their lifetimes are linked to specific broker events which are not the same as a client session termination event. E.g. a connection can be lost due to networks issues. All transient queues are deleted if a RabbitMQ node crashes or is restarted for example. 

Hence queues and messages for this use case _need to be durable_.

* The broker cannot possibly deduce when the client session is finished. The broker is a generic piece of infrastructure and doesn't contain application specific logic so this decision needs to be an application concern. I.e. when a client application is finished with the session they should delete the session queue.
* Abandoned queues (where the client application either failed to complete it's work or terminated before it could clean up) can be cleaned up by setting (reasonably long) queue TTLs on the session queues. I know of a few systems that do exactly this. This is a crude mechanism but for a certain subset of client session types it may be good enough.
* Queue TTLs do not solve the archiving feature.


Going back to adding additional features that use dead lettering I could imagine a feature that allowed any messages left in the queue when the Queue TTL timer fires to be dead lettered. If the target queue was a stream I'm sure it could absorb the load even if there were many messages on the queue at the time. I would _only_ allow this at point of Queue TTL expiry, _not_ when exclusive or transient queues are deleted or any explicit deletion request is issued.

**Comment by EmielBruijntjes** [comment]
Hi @kjnilsson, 

Yes, your initial summary is essentially correct. One point of feedback though: this is not only for archiving and off-line inspection, but also for _automatic_ processing. Ideally abandoned messages can be picked up via the standard AMQP protocol.

It is good to know what you wrote about transient queues and crashing RabbitMQ nodes, because we indeed do not want to lose messages in such cases. However, as a user we of course do not _explicitly_ create single-node queues. The flags that we pass are called "durable", "exclusive" or "auto-delete" - the fact that such queues live on a single node or not is, from our user perspective, an implementation detail that we do not explicitly ask for or care about when we use the flags. In fact:

- We set up a RabbitMQ cluster because we need a reliable queuing platform.
- We create durable queues when we do not want to send a "declare-queue" frame when we make a connection to RabbitMQ.
- We create an exclusive queue when we will be the only user of the queue.
- We create an auto-delete queue when the queue can be removed when all consumers are done with it.
- We set up dead-lettering because we don't want to lose messages.

It is then, I think, up to RabbitMQ to choose the most suitable storage implementation. For some queues this could mean that they indeed only live on a single node, but other queues (for example when there is some form of dead-lettering) might need a distributed implementation.

But anyway, if it makes the implementation on your side easier, I would already be helped if dead-lettering was enabled for queue TTL's. And thanks for your contribution, also to @lukebakken, I appreciate your feedback and I realize that sometimes things just don't have priority or that you lack the time to pick up every feature request.

**Comment by kjnilsson** [comment]
Unfortunately as operators you do have to think about the durability and availability of the different queue types and options. Arguably it is too complex which I'm sure you'll be pleased to know we've deprecated transient queues (which are linked to the lifetime of a the node they're hosted on) so that that choice will from RabbitMQ 4.0 no longer be one users have to make. Also we've deprecated mirrored queues so there is no complex replication config to get right when using classic queues. 
When using quorum queues replication and thus HA is automatically set up but you do need to choose to use this queue type at declaration. 

Dead lettering isn't a good approach for not losing messages. The best option for not losing data is using a quorum queue with publisher confirms. All messages are implicitly durable when using a quorum queue.

Exclusive queues are not deprecated as they do have a lifetime bounds that you can program against. That said they are not a good option either for messages that cannot be lost.

Dead lettering before queue TTL queue deletion is a possible feature but it does add a lot of complexity. For example if some target dead letter queues aren't confirming the messages that are dead lettered should the queue still be deleted? and if so after how long? There are decisions there that ultimately would need to be surfaced to the users, either as config options or documentation.

Considering it I feel perhaps it would be better to allow applications to easier detect potentially abandoned queues so that they could the right thing for the application.

**Comment by EmielBruijntjes** [comment]
Do you mean an AMQP protocol extension that allows applications to read out queues/exchanges/etc? Like a 'list-queues' frame or so? That could indeed be helpful and is a step forward compared to using the REST API to detect abandoned queues.

Alternatively it could be an idea to have a built-in special "amq.rabbitmq.meta" exchange to which all sorts of meta-messages are published, like when a queue is declared, a consumer starts or a consumer stops, et cetera. That would allow applications to detect when a queue is abandoned by subscribing to the appropriate meta-events. That would also allow external applications to implement an _external_ dead-lettering mechanism.

Both options are helpful. But it still feels like a workaround for something that should imho be offered out of the box. Ideally, I would like to ask RabbitMQ "Hey, can you create some queues for me, and promise me to not lose my messages when something bad happend?" Because "not-losing-data" is for, I think, many users an important reason why they use RabbitMQ.

**Comment by mkuratczyk** [comment]
Such a meta exchange already exists: https://www.rabbitmq.com/event-exchange.html

As for your last comment, we do our best to not lose messages. It's just that you explicitly declare "autodelete and temporary queues" so you turn some mechanisms off.

**Comment by lukebakken** [comment]
> Hey, can you create some queues for me, and promise me to not lose my messages when something bad happens?

Here's what you need to do:
* Use a cluster of 3 or 5 nodes
* Declare a quorum queue
* Ensure you use publisher confirms correctly

That's it.

**Comment by EmielBruijntjes** [comment]
Passive-aggressive is the culture here, isn't it? Deliberately misinterpreting. That is not good. It is a bit tiresome to always run into these type of responses.

Anyway, this topic was about all sorts of dynamic queues (like with ttl, auto-delete, exclusive). For use-cases where one needs to create and delete queues on the fly, and where you still don't want to lose data when something bad happens. For example for auto-scaled Kubernetes pods. And many other use cases.

I am not a Erlang/RabbitMQ programmer. I don't know how queues are implemented. Don't expect me to get into a discussion about how queues work under the hood and why or why not this is or is not possible. As a programmer with a C++ background however, it seems to be a normal requirement that can be implement without too much of a performance penalty.

Many people have jumped into this conversation already, so I think that I have indeed addressed something. But at the same time I do not have the impression that the willingness exists to fix this. Maybe for business reasons or maybe because of personal pride? I don't know. For the time being we, and other RabbitMQ users, will have to proceed with implementing dirty tricks and workarounds to achieve this.

**Comment by michaelklishin** [comment]
@EmielBruijntjes we have provided you with an explanation of why what you are asking for does not necessarily make sense and that there are other features or combinations of features that are already present and do what you want.

It is very very likely that you do not and never have paid for RabbitMQ yet you feel incredibly privileged and seemingly assume that the core team *owes* you something. That if you ask for something, we *must* implement it. That's not the case at all.

If you know *exactly* what you need better than the core team (who's been answering user questions for 5, 6, 10+ years in some cases), go ahead and build it yourself, RabbitMQ is open source software after all.

Continue with this demanding, disrespectful tone and I will block you from ever filing an issue for any repo in this org again.
