### ISSUE TITLE
QueueDeclare for existing queue with exclusive set fails

### ISSUE THREAD

**Issue by hammett** [rabbitmq/rabbitmq-server#713]
Assume the following queue was already declared on the server previoulsy. No consumers. 

`var conn = connFactory.CreateConnection();
var model = conn.CreateModel();
var ok = model.QueueDeclare("qx.accountx.:tradacc.:0", durable: true, exclusive: true, autoDelete: false, arguments: null);`

Note that durable is set to true. 

Error message: 

> operation queue.declare caused a channel exception precondition_failed: "inequivalent arg 'durable' for queue 'qx.accountx.:tradacc.:0' in vhost 'clear_int_test': received 'false' but current is 'true'"

I've tested with two clients to make sure it wasn't the client messing the queuedeclare bits. 

Env: RabbitMQ 3.6.1, Erlang 18.1

**Comment by michaelklishin** [comment]
The `durable` flag is ignored for exclusive queues. It makes no sense for a queue to be durable and exclusive at the same time: exclusive queues cannot survive longer than their declaring connection and connections cannot survive a broker restart.

**Comment by hammett** [comment]
Ok, thanks. The way I understood the semantics of durable, auto-delete and exclusive it would make sense for a queue to exist (durable) and store the messages routed to it, but with a guarantee that at most 1 consumer (exclusive) can consume from it (no shared workers)

**Comment by michaelklishin** [comment]
@hammett you can declare a consumer as exclusive without the queue being exclusive. That said, the former is fairly rare. Exclusive queues are not particularly rare but they are supposed to be used for entirely transient data, and so the durable flag for them is intentionally reset by RabbitMQ to `false`.

Also, exclusive consumers sounds like a good (and often necessary) idea but in practice what you really want is multiple coordinating consumers. Otherwise consumer availability becomes difficult to achieve.

**Comment by hammett** [comment]
Exclusive consumer is exactly what I was looking for. thanks again!
