### ISSUE TITLE
Can rabbitmq-server resource agent support a nodename that supports cloned resources?

### ISSUE THREAD

**Issue by jmcmeek** [rabbitmq/rabbitmq-server#73]
The rabbitmq-server resource agent cannot be used to create maker cloned resources - for example, when using a mirrored rabbitmq cluster.

The default nodename - rabbit@localhost - does not work; a value like rabbit@host1 is needed.  But you cannot use rabbit@hostname with creating a separate resource for each node as well as a corresponding location constraint to force pacemaker to run the resource on th ecorrect node.

Can the behavior of the resource agent be changed to handle this scenario better?  Some suggestions have been made including changing the default node name to:
- use NODENAME from rabbitmq-env.conf if set
- use rabbit@$(hostname -s)
- support setting the resource agent nodename property to a value like "rabbit@^hostname^", where the resource agent would replace ^hostname^ with the output of hostname -s.

This is discussed in a couple of rabbitmq-users posts:
- https://groups.google.com/forum/#!topic/rabbitmq-users/VPk_ui8gGNE
- https://groups.google.com/forum/#!searchin/rabbitmq-users/pacemaker/rabbitmq-users/SFD2DXmUPSM/w3jeQCH0SCIJ

**Comment by falfaro** [comment]
What's the difference between using the OCF resource script and a plain LSB resource in pacemaker? As far as I can see, the OCF resource does not seem to figure out the right order in which cluster members shall be started.

**Comment by michaelklishin** [comment]
To clarify: RabbitMQ node names are configurable via environment variables. However, there are tools and environments in which node name is either hardcoded or has to be shared. The OCF script is in our own repo, which is why this issue is file here. In some other cases, the limitation has to be eliminated elsewhere.

@dumbbell did #189 address this in any way? If not, can we review and commit the suggestion from the mailing list (which I believe was never submitted as a PR after all)

**Comment by michaelklishin** [comment]
Given that our OCF script was completely overhauled by @bogdando and @dmitrymex, I think this should be closed now. If you have more specific improvements in mind, please file separate issues for the new version.
