### ISSUE TITLE
Message store file GC should be more resilient to file deletion failures

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#75]
See [this mailing list thread](https://groups.google.com/d/msg/rabbitmq-users/2dqZuYc_jRc/ESlLscnqCtwJ).

**Comment by simonmacmullen** [comment]
If message store GC fails with `eacces` there's a good chance lots of other things will too - there's not much point in proceeding with this issue unless you are going to tackle all of them, otherwise it will just crash a millisecond later on something else.

And in general recovering from permission failures is hard - for deletes you can just ignore the fact that the delete failed and leak a file, but what do you do if something else fails?

I don't think this is a useful thing to do, FWIW. RabbitMQ needs to be able to have full access to its own data store, patching up after the fact is intractable.

Reporting such errors better would certainly be interesting.

**Comment by michaelklishin** [comment]
It would still be a minor improvement if we ignore file deletion failures and log them as errors. At least there is *some* chance that the file store may continue working as a whole. If not, the net result for the user is the same as what we have at the moment.

**Comment by michaelklishin** [comment]
Also, Cassandra has 2 [disk failure handling strategies](http://www.datastax.com/dev/blog/handling-disk-failures-in-cassandra-1-2) to choose from: stop (the node stops itself) and "best effort" (keep going). We could introduce something similar.

**Comment by michaelklishin** [comment]
Some clarifications on how we want it to work:

 * `rabbit.disk_failure_policy` controls how I/O errors are handled, with two modes initially: `ignore`, `die`
 * `rabbit.disk_alarm_policy` controls how disk alarms are handled, with two modes: `block_publishers`, `die`

The former modes are going to work they way they do today.

**Comment by michaelklishin** [comment]
We are cleaning up issues that have been open for many years. Classic queues v2 to certain extent makes storage more resilient. Quorum queues and streams go even further (while Raft-based systems are not perfectly safe, they are sufficient safe for a lot of use cases).
