### ISSUE TITLE
Mirrors added/removed asynchronously conflict with fast policy changes

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#889]
In CI (both Concourse and Jenkins), the `random_policy` testcase in `dynamic_ha_SUITE` fails quite frequently with the following set of policies, found by PropEr:

``` erlang
[
  {nodes, [NodeA, NodeB]},
  {nodes, [NodeA]}
]
```

The test fails because the queue is still mirrored on `NodeB` at the time of the check. It's possible the `timer:sleep(2000)` is too small for the CI VMs.

The testcase was introduced with the patch to #803.

**Comment by dumbbell** [comment]
So it's not entirely a timing issue. I just had a case where after 12 seconds, the last policy was still not active.

**Comment by dumbbell** [comment]
The following failing set of policies was found on my laptop this time:
```
[
  {exactly, 3},
  undefined,
  all,
  {nodes, [B]}
]
```

**Comment by dumbbell** [comment]
And this one:
```
[
  undefined,
  undefined,
  all,
  {nodes, [NodeB]}
]
```

So basically, all sets of policies where the last policy only targets one node.

**Comment by dumbbell** [comment]
A different kind of failing set of policies on my laptop:
```erlang
[
  all,
  undefined,
  {exactly, 2},
  all,
  {exactly, 3},
  {exactly, 3},
  undefined,
  {exactly, 3},
  all
]
```

Also a set ending with the policy `{exactly, 1}` failed in Concourse, but I don't have the complete set.

**Comment by camelpunch** [comment]
We found a small sequence of policies that, when applied, cause inconsistencies between policy and actual state of HA on the queue.

For example, consider a cluster of two nodes, A and B, and the following two policies applied in a row:

1. Replicate queue on nodes A and B:

 ```erlang
[{<<"ha-mode">>, <<"nodes">>}, {<<"ha-params">>, [A, B]}]
```
2. Replicate queue on node A only:
 ```erlang
[{<<"ha-mode">>, <<"nodes">>}, {<<"ha-params">>, [A]}]
```

A slave should be started on node B, and then stopped when the second policy is applied.

What sometimes happens is that the slave is slow to start up and registers itself after policy 2 has been applied. This means that the slave is registered, the queue is replicated, but this contravenes the last policy applied.

Events in shorthand:

- set policy 1
- start slave (... takes time...)
- set policy 2
- read #amqqueue from Mnesia -> Mnesia record has no slaves
- add_mirror -> does nothing, queue already on node A
- drop_mirror -> no slave recorded, no op
- slave finishes startup -> records itself in rabbit_queue

**In database: #amqqueue's policy says "no replication", but there is a slave**

**Comment by dumbbell** [comment]
Mirrors are dropped asynchronously as well, so the same kind of scenario applies to mirrors removal:

* Set policy 1 with many slaves.
* Set policy 2 with few slaves: some slaves are asked to exit.
* Set policy 3 which includes the exiting slaves: those slaves are still recorded in the database even though they are about to exit, thus they are left alone.
* Slaves finish to exit and unregister themselves from the database.

**In database: `#amqqueue`'s policy says "replicate to `$nodes`", but those nodes don't have a slave anymore.**

Therefore, both mirrors addition and removal need to be treated synchronously.

**Comment by dumbbell** [comment]
After more time on the problem with Andrew, we believe it is larger than just rapid `set_policy` commands.

To sum up our findings and tests:
* `suggested_queue_nodes()` bases its computation on `slaves_pids` which does not account for slaves pending startup (missing from that list) or shutdown (about to be removed from that list).
* This problem can probably occur during cluster lifetime when nodes are lost and new slaves are started.
* We can't make `add_mirrors()` and `drop_mirrors()` synchronous because they are executed in the context of the queue master and block it.
* We could add lists of slaves pending startup/shutdown to the `#amqqueue` record. Unfortunately, we still have an issue with pending slaves: we can't have two processes for the same queue on a single node because they use the same `msg_store` file(s) on disk (see [#802](https://github.com/rabbitmq/rabbitmq-server/issues/802#issuecomment-227103798)). Thus we would need to wait for the terminating slave to actually exit before we spawn the new one.
* For the same reason, just unregistering a terminating slave just before sending it an exit signal is not an easy fix. And it doesn't cover the slaves pending startup: it's unclear if registering the new slave early requires changes elsewhere (eg. how about it joining the GM ring after being registered?).
* Another solution we mentioned is a separate per-queue process being responsible for doing the `suggested_queue_nodes()`/`add_mirrors()`/`drop_mirrors()` dance serially, without blocking the master.

**Comment by camelpunch** [comment]
We have a proposal for a new algorithm that deals with quick slave addition / removal in a short time window.

## Current state, and what we are trying to fix

When we want a slave:

| State                  | Current Behaviour                              | Bug?   | Expected Behaviour                        |
| ---------------------- | -----------------------------------------------|--------| ----------------------------------------- |
| Slave running          | Do nothing                                     |        |                                           |
| Slave pending startup  | Start slave (pending slave not registered yet) | YES    | Do nothing                                |
| Slave pending shutdown | Do nothing (pending slave is still registered) | YES    | Wait for exiting slave, start a new slave |
| No slave               | Start slave                                    |        |                                           |

When we no longer want a slave:

| State                  | Current Behaviour                       | Bug?   | Expected Behaviour                        |
| ---------------------- | ----------------------------------------|------- | ----------------------------------------- |
| Slave running          | Remove slave                            |        |                                           |
| Slave pending startup  | Do nothing                              | YES    | Stop slave                                |
| Slave pending shutdown | Remove slave again (probably harmless)  | MAYBE  | Do nothing (easier in new world)          |
| No slave               | Do nothing                              |        |                                           |

## Short-lived scheduler

When a change is required for a particular queue, such as mirroring to a new slave, we intend to start a process on the master node. This process will be started from the queue master process, and its pid will be recorded in the `#amqqueue` record in mnesia.

The master will continue to compute the new master and list of slaves. But, it will delegate slaves' lifecycle management to the scheduler process (starting, stopping).

The state of master and slave processes must be more detailed inside mnesia. We want to record whether a slave is pending startup or shutdown. This way, the scheduler process can be stateless.

Each scheduler process will live until the whole cluster reaches the target state for the queue. It will monitor slaves pending start/stop, and verify if a policy is fully applied each time a slave is ready or fully exited. If the cluster is fine, the process exits.

The master process and the scheduler process are `link`ed together. If the scheduler loses its link to the master, it exits (to avoid having two schedulers running, which would start multiple identical slaves). If the master loses its link to the scheduler, it spawns a new scheduler.

When a master starts and there is already a scheduler process pid in the database, it `link`s it.

## Mnesia schema change

We need to modify the `#amqqueue` record, and thus the schema. So, we'd like to take this opportunity to consolidate all the lists of slaves into a single proplist or map. This allows future changes to be made to this area of the schema without requiring a major upgrade (cluster restart / plugin changes).

Before:

```erlang
#amqqueue{
  slaves = [PidA, PidB, PidC, PidD],
  sync_slaves = [PidC, PidD],
  slaves_pending_shutdown = [PidD] % only in master
}
```

After:

```erlang
#amqqueue{
  target_slaves = [ NodeA, NodeB, NodeC ],
  slaves = [
    { PidA, starting },
    { PidB, out_of_sync },
    { PidC, synced },
    { PidD, exiting }
}
```

## Approach

- Do this in `master`. Leave pending tests as they are in `stable`. This avoids too much change on `stable`.
- Add functions to read / write slave data. Use them to implement existing behaviour.
- Implement the above
- Re-enable pending tests on `master`

**Comment by Avivsalem** [comment]
I'm encountering a similar bug using the last version (3.7.11)
After changing a policy from ha-params=exactly 2 to exactly 1 rapidly, the queue goes into a "frozen" state. 
It shows on the management ui, but with no state. Can't be deleted or used in anyway. 
The only way to "unlock" it is to restart the master node for this queue... 

Is there any fix coming to this?

**Comment by michaelklishin** [comment]
There is no easy fix to this. Policy changes are generally applied sequentially but those that can change queue master location can create a distributed race condition in queue state updates. Quorum queues in theory should be a lot less susceptible to this since they by definition pass all queue state changes through a well understood consensus algorithm log.

There is no ETA on when/if this is going to be addressed for classic queues.

**Comment by Avivsalem** [comment]
Thanks for the reply!
I solved this for now by adding a sleep between policies... 
Waiting for quorum queues... (and generally for 3.8.0, for multiple reasons)

**Comment by michaelklishin** [comment]
Yes, simply avoiding rapid policy changes that affect mirroring should be enough to avoid the problem.
