### ISSUE TITLE
Pluggable logging backends

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#94]
People keep asking for it. We should make Lager dead easy to use with RabbitMQ. Or even consider switching to it entirely.

**Comment by willejs** [comment]
:+1:

**Comment by willejs** [comment]
@michaelklishin are there plans to implement this any time soon? I am very interested in it!

**Comment by michaelklishin** [comment]
@willejs we are pretty busy with other things. It should be very realistic to ship this with `3.6.0`.

**Comment by michaelklishin** [comment]
@willejs that said, #128 is something we can finish by early may. Might give you some options.

**Comment by willejs** [comment]
Cheers @michaelklishin its good enough that this is on the horizon :) . Adding this issue to the 3.6.0 milestone would be cool ;)

**Comment by willejs** [comment]
@michaelklishin sorry to bother you! Is it on a roadmap? Is there anyway to speed this up, apart from learning erlang? ;) I'l donate to the project in any way if i can!

**Comment by videlalvaro** [comment]
There's this already that can help a bit: https://github.com/hyperthunk/rabbitmq-lager I'm using it on a plugin that I'm building

**Comment by michaelklishin** [comment]
@willejs this is not getting any attention yet for one reason: we are a tiny team. It's still on the roadmap for 3.6.0 and we'll see if we can squeeze it into the list of things for July.

**Comment by willejs** [comment]
I understand, hence apologising! July would be great!

**Comment by willejs** [comment]
@michaelklishin me again :) Hows this looking?

**Comment by michaelklishin** [comment]
@willejs it will not be in 3.6. However, now that we've moved to erlang.mk for the build system, introducing new dependencies is trivial, so this becomes easier.

**Comment by michaelklishin** [comment]
There were logging changes in Erlang/OTP 18.1, which 3.7 will likely require, that make me wonder if Lager is really necessary for this to work.

**Comment by hairyhum** [comment]
Lager receives messages from `error_logger`, so it's possible to just start lager application on rabbitmq node and set logging `app_env` and logs will go to lager. (without lagers fancy formatting, which is parse_transform).
So in first approach we can just add log location to `rabbitmq.config` to lager application.

**Comment by hairyhum** [comment]
Do anyone know why is there `append_file` and then `delete` instead of just `rename` in log rotation? https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_error_logger_file_h.erl#L170

**Comment by michaelklishin** [comment]
@hairyhum see a comment on `rabbit_file:append_file/2`.

**Comment by michaelklishin** [comment]
@hairyhum apparently the change dates back to 59d0dcc5d511570a066ec823b2c1fdbed04e808e. Also note that `rabbit_file:append_file/2` actually can perform rotation, despite the name.

**Comment by hairyhum** [comment]
We have following config variables:

RABBITMQ_LOG_BASE 
RABBITMQ_LOGS - general logs (default %RABBITMQ_LOG_BASE%\%RABBITMQ_NODENAME%.log)
RABBITMQ_SASL_LOGS - sasl logs (default %RABBITMQ_LOG_BASE%\%RABBITMQ_NODENAME%-sasl.log)

RABBITMQ_LOGS and RABBITMQ_SASL_LOGS can be set to absolute filename or `-` which means log to console.
This configs transform to application env variables `error_logger` and `sasl_error_logger`, which can be
either `tty` or `{file, FileName}`.

Lager log_root and handlers for logs can be configured from .config file for different loglevels and console/file/something else backends.
So I think it is better way to configure non-default logging, rather than env variables.
Currently log_root is set to RABBITMQ_LOG_BASE if not set in .config
handlers also can be formaed from env variables if no handlers config present.
So RABBITMQ_LOGS="-" becomes `{lager_console_backend, debug}`
RABBITMQ_LOGS="filaname" becomes `{lager_file_backend, [{file, "filename"}, {level, debug}]}`

There are change in log rotation. Customers can rely on logrotate with 'suffix', which 
is copying file to a new location and creating new empty one.

While using lager it is possible just to move file or delete it (if suffix = '')
Difference will be in that **there could be no logfile after rotating until lager log something in it**.
Lager is checking if file exist on every log and create new ones without loosing messages 

Lager itself supports log rotation by date and file size and can keep given count of
rotated files, which could be useful.
But it is possible to leave existing rotate_logs command.

So main changes so far will be:
`error_logge` app config variable is not relevant anymore.
After `rotate_logs`, there could be no log file until next log. 
Application config for `lager` will override ENV variables.

**Comment by hairyhum** [comment]
And I didn't found out yet how to separate sasl and general logs so far.

**Comment by michaelklishin** [comment]
@hairyhum note that we can log something after rotation, e.g. "opening a new log file after rotation". `error_logger` config settings are not commonly used and there is an alternative, so breaking that is fine.

**Comment by hairyhum** [comment]
Found an option to separate sasl and general logs. It is lager `sinks`. It even allows us to log different categories `rabbitmq_log:log(Category, Level, Msg)` in different files. Maybe it can be useful.

**Comment by hairyhum** [comment]
Currently lager has it's own way to format `error_logger` messages. This format skips stack trace in some cases, which could be inconvenient.

**Comment by michaelklishin** [comment]
@hairyhum can it be overridden?

**Comment by hairyhum** [comment]
@michaelklishin unfortunately, not in current implementation. And they are not too quick at accepting pull requests right now. But we can use forked version, if it's an option.

**Comment by michaelklishin** [comment]
@dumbbell @videlalvaro @essen what are your thoughts on using a Lager fork to get more informative crash reports (with stack traces)?

@hairyhum can you be more specific what the "some cases" are?

**Comment by hairyhum** [comment]
As I can tell from code, stacktraces are omitted if errors are from `gen_server`, `state_machine`, `en_event` and `supervisor`. So it's should be OTP messages

**Comment by michaelklishin** [comment]
We can live without stack traces in the regular log but SASL log really could benefit from having stack traces. I'm not a fan of using forks but if that's what we have to do, I'm fine with it.

**Comment by videlalvaro** [comment]
I think whatever we fork we should actively try to incorporate upstream,
otherwise not sure the team should invest resources on maintaining a fork.

**Comment by hairyhum** [comment]
I mentioned fork because lager team are too busy right now to deal with PR, like they said. So I hope it could be merged eventually.

**Comment by michaelklishin** [comment]
This is on its finish line. As part of this, we will pipe the majority of log entries (everything but Erlang process crash reports) to `rabbit.log` and get access to the `debug` level, which is quite verbose.

See #491 for more details.
