### ISSUE TITLE
Nack messages that cannot be deposited to all queues due to max length reached

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-server#995]
Under publisher confirms, messages are nacked when the broker could not process them. This issue requests to optionally treat "at least one queue is full" as one of the reasons when the broker could not process a message, instead of discarding old messages, which is the current behavior that may remain the default. 

See also: https://groups.google.com/forum/#!topic/rabbitmq-users/Fzsdx1CEiWA

**Comment by michaelklishin** [comment]
Similar in spirit to #499, should be evaluated together with it.

**Comment by kjnilsson** [comment]
Just to make sure my understanding of the request is correct, the feature requested is to be able to configure a queue with a queue length limit to discard incoming messages (rather than from the head of the queue) and hook into the publisher confirm mechanism to `nack`  when a routable queue is unable to accept a message due to the queue being "full"? Similarly to what may happen if the queue process crashes during processing.

**Comment by uvzubovs** [comment]
You got it, Karl! Thank you very much for your insight.

**Comment by peaksnail** [comment]
It will make sence! Thumbs up!

**Comment by jrlog** [comment]
Seconded. The message-discarding behavior has been universally unexpected among people I've talked with about it, and it would make sense to add this as an (at least optional) feature.

**Comment by hsquirrel** [comment]
Yes, please! I have systems that are far more complicated than they need to be because of the default behavior. This one feature would would be a godsend for me. Keep the default, but make it an option.

**Comment by smnirven** [comment]
I too would love to see this feature

**Comment by chadrik** [comment]
+1

**Comment by ben-spiller** [comment]
How does this look to a JMS publisher? Would it get an easy-to-handle exception?
